### ISSUE TITLE
bower-asset path has a problem

### ISSUE THREAD

**Issue by bingoyan** [yiisoft/yii2-app-advanced#107]
can't find /vendor/bower/bootstrap,

when update composer,bower/bootstrap path has changed，now in vendor/bower/bower-asset/bootstrap

please update!

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer

**Comment by samdark** [comment]
composer global require "fxp/composer-asset-plugin:~1.1.1"

**Comment by LAV45** [comment]
@samdark , может стоит наглухо зашить в composer.json что бы больше не возникало таких проблем. Я понимаю что можно просто ткнуть в документацию но эта проблема уж очень часто возникает у новичков или когда на prod выкатываешь свою поделку.

**Comment by samdark** [comment]
@LAV45 не выйдет. Плагин работает только когда поставлен глобально :(

**Comment by bingoyan** [comment]
ok  tks
