### ISSUE TITLE
Documentation issue on using the yii migrate command

### ISSUE THREAD

**Issue by pkanane** [yiisoft/yii2-app-advanced#108]
After the first time installation of the yii2-app-advanced  on a LAMP server on Ubuntu 14.04 I could not run the migration with the command documented here. 
I.e the instruction to run **_yii migrate_**

I was able to get the migrations to run by typing **_./yii migrate_**

I don't know if it's an issue with the PATH but I believe the second option of the *./yii* should be added to this documentation

**Comment by samdark** [comment]
Nah, it's not. It depends on flags you set on your files and is linux command line basics. Not sure we should cover it in Yii guide. Probably not.

**Comment by pkanane** [comment]
OK thanks.

Loving the new Yii2 though. Great work
