### ISSUE TITLE
Sessions are shared between backend and frontend

### ISSUE THREAD

**Issue by mytskine** [yiisoft/yii2-app-advanced#110]
Install yii2-app-advanced, create user accounts, fill up the login form in the frontend application.
Now open the backend application: no login needed, authentication is shared!

The problem is that PHP sessions are shared by default among all the PHP pages. This means that authenticating in one application on the server may induce authentication in other applications (you may need to alter the "domain" part of the cookie, if the access goes through distinct virtual hosts on the same PHP server).

The solution is to save sessions in directories local to each application. PR follows.

**Comment by klimov-paul** [comment]
You should setup different session names in this case

**Comment by mytskine** [comment]
I respectfully object to keeping this default behavior. The default behavior of yii2-app-advanced has a huge security risk. The solution may seem obvious to experienced Yii2 users, but I guess many developers won't realize it and will blame yii2-app-advanced or Yii2.

By the way, your "solution" provides almost no security gain: the session name is just a property name in the cookie. One can easily change it. An attacker that can find or guess the backend session name can convert a frontend session into a backend session.

**Comment by klimov-paul** [comment]
> By the way, your "solution" provides almost no security gain: the session name is just a property name in the cookie.

Just as well as 'domain'.

You should setup different `yii\web\User::idParam` for admin application, in this case even if front-end and back-end users have same ID they cann't share session identity.

**Comment by klimov-paul** [comment]
I suppose `yii\web\User::idParam` should be adjusted for 'backend' by default.

**Comment by samdark** [comment]
Yes, looks like a good idea considering the number of issues arising...

**Comment by SDKiller** [comment]
This issue have been discussed many times and actually is **not an issue**.

Developer should consider setting different `session.name`, `request.csrfParam` and `request.cookieValidationKey` for frontend and backend to separate backend and frontend. 

As for forging cookie name - malicios user will gain nothing if application logics is correct.

It's obvious that **access rules** should be different for backend and frontend - and advanced app provides such property as `role` in user model which can be used for that purpose.

**Comment by cebe** [comment]
@SDKiller it is not a serious issue but it would be good to have a config that avoids it by default.

**Comment by WadeShuler** [comment]
It used to be, that stock Yii2 Advanced, you could login as the first user (in user table) with id of 1. If you had an admin of 1 in another table (admin), he could go to the backend and be logged in. +

I am not sure if that has been fixed? I hope/assume it has with the auth token and cookie verification?

I believe there should be (out of the box) the config to separate them though.

Here is my setup:

### My `/backend/config/main.php`:

    return [
        'id' => 'app-backend',
        // ...
        'components' => [
            'user' => [
                'identityClass' => 'common\models\Admin',
                'enableAutoLogin' => true,
                'identityCookie' => [
                    'name' => '_backendUser', // unique for backend
                ]
            ],
            'session' => [
                'name' => 'PHPBACKSESSID',
                'savePath' => sys_get_temp_dir(),
            ],
    // ..
    ];

### My `/frontend/config/main.php`:

    return [
        'id' => 'app-frontend',
        'components' => [
            'user' => [
                'identityClass' => 'common\models\User',
                'enableAutoLogin' => true,
                'identityCookie' => [
                    'name' => '_frontendUser',
                ]
            ],
            'session' => [
                'name' => 'PHPFRONTSESSID',
                'savePath' => sys_get_temp_dir(),
            ],

As you can see, I also have a separate model for backend, named `Admin`. This is a copy of the User model, modified for Admin. My Yii init migration (where it makes the user table), I also have it make an admin table. Where my Admin model looks for admin users.

With this setup:
 - my admins login via the backend and the admin table. They can't access the frontend.
 - my users login via the frontend and the user table. They can't access the backend.

You could create a script in the frontend to create a cookie and log you in as the user, if you wanted the ability to login to user's accounts from the Admin area. It would require additional coding lol, but it is possible.

**Comment by cebe** [comment]
fixed by setting the default cookie names differently on backend and frontend. the cookie validation keys have been different before anyway.
