### ISSUE TITLE
Bootstrap extension version 2.0.5 is not synchronised with yii's version

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2-app-advanced#112]
In documentation for :
 - yii\bootstrap\BaseHtml (http://www.yiiframework.com/doc-2.0/yii-bootstrap-basehtml.html)
 - yii\bootstrap\Html (http://www.yiiframework.com/doc-2.0/yii-bootstrap-html.html)

It is stated "Available since version	2.0.5"...

But as yii version 2.0.6 bundle in yii-advanced-app-2.0.6 (same in yii-basic-app-2.0.6), they are not included yet.

I feel like this discrepancy doesn't make sense. Maybe the availability in documentation might gain to be changed and stated for the next version? Or the bundles updated?

I finally start to think that yii numbering version 2.0.6 has no direct relation with yii-bootstrap numbering version 2.0.5.
In this case, the documentation might be clearer on which version it is speaking. It is not obvious to dive into each component to know the version running into the main yii version we are developping (so it would rather be a guide issue).

**Comment by samdark** [comment]
Yes. Extensions are released and numbered separately.

**Comment by CedricYii** [comment]
May i suggest these small improvements in the guide for all extensions:

1. change "Available since version..." by "Available since extension version..."
so that readers have a hint on what's going on there.

2. At the top of each class's page, change the link behind "All classes": 
 -> http://www.yiiframework.com/doc-2.0/index.html (you may also note that when clicking on "all classes" you actually can't come back on the class you were reading)
by 
 -> http://www.yiiframework.com/doc-2.0/ext-bootstrap-index.html (in my example)
so that it would avoid confusion and mixing unrelated matters.
