### ISSUE TITLE
The missing '@' prefix of setAlias('common', ...)

### ISSUE THREAD

**Issue by drodata** [yiisoft/yii2-app-advanced#113]
I'm puzzled about the usage of `setAlias()` in `common/config/bootstrap.php`:

```php
Yii::setAlias('common', dirname(__DIR__));
...
```

That is, the `common` argument doesn't have a `@` prefix. The API of `BaseYii::setAlias()` has emphasized that the `@` prefix is required:

> the alias name (e.g. "@yii"). It **must start with a '@' character**.
> 
> [`BaseYii.php` Line 199](https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L199)

Although 

> Alias defined without leading `@` will be prefixed with `@` character.
>
> [Guide 2.0 Key Concepts - Aliases](http://www.yiiframework.com/doc-2.0/guide-concept-aliases.html)

, it would be better that we always prefix a `@` character when setting aliases.

**Comment by samdark** [comment]
Feel free to pull request.
