### ISSUE TITLE
 "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0

### ISSUE THREAD

**Issue by ipppinto** [yiisoft/yii2-app-advanced#117]
When I do in composer:
composer global require "fxp/composer-asset-plugin:~1.1.1"

I have this error:
The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2-composer/issues/4

**Comment by ipppinto** [comment]
Thanks
