### ISSUE TITLE
helpers\Html -> bootstrap\Html

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#121]
Since `yii2-app-advanced` is Bootstrap-based things like:
```
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
```
should be changed to
```
use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;
```
etc.

**Comment by radiocity** [comment]
no way!

**Comment by samdark** [comment]
@radiocity ?

**Comment by klimov-paul** [comment]
It is hard to tell if such changed should be made.
While it seems to be logical - it produces extra wor in case you don't want to use Bootstrap in your project.

**Comment by PowerGamer1** [comment]
> While it seems to be logical - it produces extra wor in case you don't want to use Bootstrap in your project.

There is already a LOT of work to be done to make app template "non-bootstrap" (change all `yii\bootstrap\ActiveForm` to `\yii\widgets\ActiveForm`, modify app.css, modify layout.php, etc) so I don't think this should be a consideration at all (i.e. the app template is bootstrap-based by design and period).

**Comment by samdark** [comment]
I'd leave it as is.
