### ISSUE TITLE
Docs Installation db setting in env folder

### ISSUE THREAD

**Issue by kmergen** [yiisoft/yii2-app-advanced#123]
In installation guide `Create a new database and adjust the components['db'] configuration in common/config/main-local.php accordingly.`

I think it is better to set it in environment folder.

**Comment by samdark** [comment]
For development — nope.

**Comment by kmergen** [comment]
What is when I have a third env e.g. 'blog' and annother db config for the blog.
I switch to blog env and when I override all my config gone away.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/issues/120

**Comment by kmergen** [comment]
That means when you have choose an environment than you should never switch it to annother environment in the same project folder. Because when you do this the whole configuration in the `project-folder/common/config/main-local.php` will be overriden by the `environment /env/config/main-local.php`:

**Comment by samdark** [comment]
Well, it asks you what do you want to override. Also there's an option to always skip local files.

**Comment by kmergen** [comment]
Ok. It make sense to use it only once with application init.
Is it right when I say the `environment /dev/config/local-main.php` file is only an example configuration file to use it once init the applications environment and the workflow is as follow:

1. init env (e.g. dev)
2. make changes in `project-folder/common/config/def/main-local.php.`
3. If I want I can copy my configuration to `environment /dev/config/local-main.php` to archive it.
