### ISSUE TITLE
PHP Warning – yii\base\ErrorException  Expected array for frame 0

### ISSUE THREAD

**Issue by deplop** [yiisoft/yii2-app-advanced#128]
When I do this command

sudo chown -R deplop yii-application

I got this
PHP Warning – yii\base\ErrorException  Expected array for frame 0 

If I put die() in site/index action, I got more detail that the error comes out from this file
vendor/yiisoft/yii2/log/Target.php (line 243)

**Comment by cebe** [comment]
please paste the stack trace of the error.

**Comment by SilverFire** [comment]
I've faced this problem when PHP is unable to write in dirs under `runtime`. Please, make sure that web server process has enough permissions

**Comment by mrsombre** [comment]
This error related to php cli, debug mode and xdebug enabled. Maybe only for PHP version 7.
BTW "Expected array for frame 0" came from \yii\base\ErrorException:45. After i switch ErrorHandler to custom using ErrorException without xdebug related code error is gone.

**Comment by sergebezborodov** [comment]
have the same problem, yii ErrorException constructor fails with xdebug and php7, as @mrsombre switch to my version without 'if (function_exists('xdebug_get_function_stack')) {' block

**Comment by cebe** [comment]
could somebody reopen this issue on yii2 main repo and provide steps to reproduce?

**Comment by samdark** [comment]
@sergebezborodov ↑

**Comment by sergebezborodov** [comment]
try to do this

**Comment by mrsombre** [comment]
@samdark https://github.com/yiisoft/yii2/issues/11120

**Comment by chiefmc** [comment]
hey guys, same situation here:  PHP Warning – yii\base\ErrorException Expected array for frame 0

Happens during PHPUnit code coverage phase on our GitLab CI server.

PHP 7.0.4 + XDebug 2.4.0 + Yii 2.0.7 on FreeBSD

**Comment by gbespyatykh** [comment]
Same situation in console and web application on ErrorException

PHP 7.0.5 + xdebug 2.4.1-dev + Yii 2.0.7

**Comment by cebe** [comment]
please keep discussion to one issue: https://github.com/yiisoft/yii2/issues/11120
