### ISSUE TITLE
Password reset page can be accessed by logged in user

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#130]
Password reset page can be accessed by logged in user. Shouldn't it be not found, access denied or redirect to home page instead?

**Comment by samdark** [comment]
Not really. Why?

**Comment by PowerGamer1** [comment]
Because if he managed to log in he remembers his password. And if he wants to change the password while remembering the old one and being already logged in it is better to allow him to do it on some page without making him enter his email, mailing a message with link that he must open and click just to change the password (while on some page he could simply entered an old password and then the new one).

**Comment by samdark** [comment]
Maybe he just want to change the password while being logged in. That's a valid use case to me.

**Comment by sokoji** [comment]
+1 for @PowerGamer1 
If I want to change my password, I will use change password form while being logged in, not "remember password" form. I think, it should be different forms. The first one will send only notification — "Your password was changed", the "remember me" form will send a link with hash.

**Comment by samdark** [comment]
Both should send a link with a hash. Changing password is critical operation security-wise so extra verification is required. Logged in state could be obtained, for example, by stealing cookies via MITM attach in an insecure environment.
