### ISSUE TITLE
Out of memory error when running a test suite

### ISSUE THREAD

**Issue by dmitry-kulikov** [yiisoft/yii2-app-advanced#145]
See issue in [Codeception](https://github.com/Codeception/Codeception/issues/2516) and my [comment](https://github.com/Codeception/Codeception/issues/2516#issuecomment-209700502).
Although it is not bug in this repository, it affects it, I suggest to revert 9607bc0b2391c5ce49eed1eee202a4913386266f, at this moment Codeception 2.0.* should be recommended for Yii 2.

**Comment by samdark** [comment]
Are you using `Codeception\Specify`? If so, try adding

```php
\Codeception\Specify\Config::setDeepClone(false);
```

to `_bootstrap.php`.

**Comment by samdark** [comment]
https://github.com/Codeception/Codeception/issues/2516

**Comment by dmitry-kulikov** [comment]
Yes, using of
`\Codeception\Specify\Config::setDeepClone(false);`
in
```
tests/codeception/backend/_bootstrap.php
tests/codeception/common/_bootstrap.php
tests/codeception/console/_bootstrap.php
tests/codeception/frontend/_bootstrap.php
```
solved problem.
Thank you!

**Comment by samdark** [comment]
Worth having it in the docs...

**Comment by samdark** [comment]
Should be addressed by https://github.com/yiisoft/yii2-app-advanced/pull/190
