### ISSUE TITLE
config-local.php file not found

### ISSUE THREAD

**Issue by doubleh-rajput** [yiisoft/yii2-app-advanced#147]
While creating a database for tests, adjust the `components['db']` configuration in `tests/codeception/config/config-local.php`,

   ```
   codeception/bin/yii migrate
   ```
Fatal error: require(): Failed opening required 'C:\wamp\www\yii2-projects\tests\codeception/config/config-local.php' (include_path='.;C:\php\pear') in C:\wamp\www\yii2-projects\tests
\codeception\bin\yii on line 20

```
please update your .gitignore file in tests\codeception\config\ folder

```
remove config-local.php from .gitignore file

**Comment by cebe** [comment]
`/config-local.php` will be generated by init command, which has to be run first.
