### ISSUE TITLE
SignupForm.php filter vs. trim validator

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#152]
SignupForm.php has:
```PHP
['username', 'filter', 'filter' => 'trim'], 
['email', 'filter', 'filter' => 'trim'], 
```
Since there is a special `trim` validator in the framework it should be used instead of longer `filter` validator:
```PHP
['username', 'trim'], 
['email', 'trim'], 
```
Alternatively, `trim` validator should be removed from the framework altogether since more generic `filter` validator can do the same. But using `filter` validator for trimming when there is a `trim` validator just does not make sense to me - i.e. why implement a feature (`trim` validator) in the framework that you yourselves won't use?

**Comment by cebe** [comment]
the trim validator is just a preconfigured shortcut name for the filter validator, there is no trimvalidator class: https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L78-L82

Its just a different notation for the same thing. If you want to change it, you can send a pull request.

**Comment by PowerGamer1** [comment]
Fixed in https://github.com/yiisoft/yii2-app-advanced/pull/154
