### ISSUE TITLE
Issue with new users creation in the frontend

### ISSUE THREAD

**Issue by p3ll3** [yiisoft/yii2-app-advanced#164]
### What steps will reproduce the problem?
Try to create a new user in the frontend signup form
### What's expected?
Create the user correctly

### What do you get instead?
We get null value of the column "password_reset_token"

### Additional info
Yii  2.0.8
5.5.9
Ubuntu 14.04

**Comment by samdark** [comment]
That's expected. Token is generated when password reset is requested: https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/models/PasswordResetRequestForm.php#L51

**Comment by p3ll3** [comment]
But what happen if it's a new user ?
We can't expect to reset the password when we're creating a **new user** , how that's possible?

**Comment by samdark** [comment]
New user enters his password in signup form, he's not using reset form for that.
