### ISSUE TITLE
Copyright header in Alert.php

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#165]
`/common/widgets/Alert.php` is the only file in the `yii2-app-advanced` that comes with a copyright header at the beginning of the file (as if that file is part of the Yii2 framework itself):
```PHP
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
```
Why is that? This comment should either be removed or added to every file of `yii2-app-advanced`. Or maybe Alert.php should become a part of the framework itself?

**Comment by samdark** [comment]
Yes, it could be removed.
