### ISSUE TITLE
Exception 'yii\db\Exception' with message 'could not find driver'

### ISSUE THREAD

**Issue by rushian** [yiisoft/yii2-app-advanced#166]
### What steps will reproduce the problem?
I am accessing the project directory C:\wamp64\www\learning  and using the follow command: 
`php7 yii migrate`
### What's expected?
I wanna create a migrate with pgsql connection
### What do you get instead?
Yii return Exception 'yii\db\Exception' with message 'could not find driver'

Another project, with Yii 1.0 connects right...

I take a screenshot of pdo driver configuration... https://goo.gl/photos/sBFipVkrNKEMic7S8, what I need change to connect??? when I try to connect to mysql there is no problem

### Additional info

| Q                          | A
| ---------------------- | ---
| Yii vesion              | 2.0.8
| PHP version         | 7.0.0
| Operating system | Windows 7 sp1

**Comment by cebe** [comment]
are you sure these are part of the console binary as well?
Check the output of `php -m`.

**Comment by rushian** [comment]
Thank for your tip, with php -m I see the real php.ini
I am using the newst version of wamp, and there are php7 e php5 in this manager... the wamp php.ini shortcut show a php.ini, but I should uncomment in file php.ini of both version folder...

**Comment by ahmadfauzirahman** [comment]
Yii Migration Tool (based on Yii v2.0.11)

Exception 'yii\db\Exception' with message 'could not find driver'

in /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Connection.php:568

Stack trace:
#0 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Connection.php(896): yii\db\Connection->open()
#1 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Connection.php(883): yii\db\Connection->getMasterPdo()
#2 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#3 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Command.php(896): yii\db\Command->prepare(true)
#4 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/mysql/Schema.php(199): yii\db\Command->queryAll()
#6 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/mysql/Schema.php(98): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#7 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/db/Schema.php(152): yii\db\mysql\Schema->loadTableSchema('migration')
#8 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/console/controllers/MigrateController.php(199): yii\db\Schema->getTableSchema('{{%migration}}', true)
#9 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(774): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
#10 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(138): yii\console\controllers\BaseMigrateController->getNewMigrations()
#11 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#12 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#14 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#15 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#16 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#17 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#18 /opt/lampp/htdocs/yii_advanced/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /opt/lampp/htdocs/yii_advanced/yii(27): yii\base\Application->run()
#20 {main}

somebody help me, i can't fix this problem ...
