### ISSUE TITLE
Please update yii2-app-advanced/docs/guide/start-installation.md

### ISSUE THREAD

**Issue by gitowiec** [yiisoft/yii2-app-advanced#170]
### What steps will reproduce the problem?
Try to bring up developed sources from git repository (git clone, composer install, init...) or
install yii2-app-advanced from scratch with [Installing using composer](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#installing-using-composer)

### What's expected?
Working yii2-app-advanced

### What do you get instead?
```
Problem 1
- yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
- yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
- yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
- yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
- Installation request for yiisoft/yii2 >=2.0.5 -> satisfiable by yiisoft/yii2[2.0.5, 2.0.6, dev-master, 2.0.x-dev].
```

### Additional info
Here is resolution to this issue http://stackoverflow.com/a/36498658/340142

| Q                | A
| ---------------- | ---
| Yii vesion       | >=2.0.6
| PHP version      | 7.0.5
| Operating system | Windows 10 64bit

**Comment by samdark** [comment]
It's already covered: https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#installing-using-composer

**Comment by gitowiec** [comment]
errr it is covered, but it is outdated and makes no statements if above error occurs. My point is, that Yii2 Composer installation depends on third party plugin fxp/composer-asset-plugin which sometiomes brakes the installation procedure (see above)

**Comment by samdark** [comment]
It's not outdated. `~1.1.1` means latest `1.1.x` version.
