### ISSUE TITLE
Run `fixture/load User` fails to load User data

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2-app-advanced#172]
### What steps will reproduce the problem?

Execute `php yii fixture/load User`;
### What's expected?

Data from `tests\codeception\common\fixtures\data\init_login.php` should be loaded to `db`;
### What do you get instead?

Not loaded.
### How to fix:

Set `public $dataFile = __DIR__ . '/data/init_login.php';` inside `UserFixture`
### Additional info

| Q | A |
| --- | --- |
| Yii vesion | 2.0.8 |
| PHP version | 7.0.4 |
| Operating system | Ubuntu 16.04 |

**Comment by slinstj** [comment]
The `ActiveFixture::getData()` tries to guess the file name using sub folder `data` followed by the table name (`user`, in this case), i.e `data/user.php` that does not exists in app-advanced.

**Comment by AlekseyBykov** [comment]
Thank you for your posting! Works perfectly with MySQL, but don't work with MS SQL Server..

**Comment by samdark** [comment]
@AlekseyBykov how exactly it doesn't work?

**Comment by AlekseyBykov** [comment]
Hi, samdark! Thank you for your reply! I installed advanced application template, created two databases yii2advanced: one in the local MySQL another in the remote MS SQL Server. Applied the migration on both the databases. Next, I loaded fixture into the MySQL table tbl_user, the data is loaded successfully. Then tried to load fixture into the MS SQL Server's table [dbo].[tbl_user] but get exception:

> Exception 'yii\base\InvalidParamException' with message 'Table not found: []'

Tried to define the table name as described below, several variants, all the have not helped:

```
public static function tableName()
{
    return 'dbo..tbl_user'
}
...
public static function tableName()
{
    return 'dbo.sa.tbl_user'
}
...
public static function tableName()
{
    return '{{dbo.sa.%user}}'
}
...
```

**Comment by AlekseyBykov** [comment]
I execute `yii fixture/load User` with the following configuration:

```
'components' => [
    'db' => [
        'class' => '\yii\db\Connection',
        'dsn' => 'sqlsrv:Server=...;Database=yii2advanced',
        'username' => 'sa',
        'password' => '...',
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
],
```
Full stacktrace and command output:
```
C:\php-projects\advanced\tests\codeception\bin>yii fixture/load User
Fixtures namespace is:
        tests\codeception\common\fixtures

Global fixtures will be used:

        1. yii\test\InitDb

Fixtures below will be loaded:

        1. User

Be aware that:
Applying leads to purging of certain data in the database!

Load above fixtures? (yes|no) [no]:yes

Exception 'yii\base\InvalidParamException' with message 'Table not found: []'

in C:\php-projects\advanced\vendor\yiisoft\yii2\db\mssql\QueryBuilder.php:182

Stack trace:
0 C:\php-projects\advanced\vendor\yiisoft\yii2\db\Command.php(754): yii\db\mssql\QueryBuilder->checkIntegrity(false, '', '')
1 C:\php-projects\advanced\vendor\yiisoft\yii2\test\InitDbFixture.php(94): yii\db\Command->checkIntegrity(false, '')
2 C:\php-projects\advanced\vendor\yiisoft\yii2\test\InitDbFixture.php(76): yii\test\InitDbFixture->checkIntegrity(false)
3 C:\php-projects\advanced\vendor\yiisoft\yii2\test\FixtureTrait.php(114): yii\test\InitDbFixture->beforeUnload()
4 C:\php-projects\advanced\vendor\yiisoft\yii2\console\controllers\FixtureController.php(159): yii\console\controllers\FixtureController->unloadFixtures(Array)

5 [internal function]: yii\console\controllers\FixtureController->actionLoad('User')
6 C:\php-projects\advanced\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
7 C:\php-projects\advanced\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
8 C:\php-projects\advanced\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('load', Array)
9 C:\php-projects\advanced\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('load', Array)
10 C:\php-projects\advanced\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('fixture/load', Array)
11 C:\php-projects\advanced\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('fixture/load', Array)
12 C:\php-projects\advanced\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
13 C:\php-projects\advanced\tests\codeception\bin\yii(23): yii\base\Application->run()
14 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.7-dev
| PHP version      |5.4.45
| Operating system |Windows 7 Home Basic  or Windows 10 Pro

**Comment by AlekseyBykov** [comment]
How to load fixture's data to the MS SQL Server database?

**Comment by samdark** [comment]
Testing bolilerplate was refactored. Is it still an issue?

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.

**Comment by boboldehampsink** [comment]
This is still an issue

**Comment by boboldehampsink** [comment]
I've created a fix for this: https://github.com/yiisoft/yii2/pull/13572

**Comment by SilverFire** [comment]
The PR https://github.com/yiisoft/yii2/pull/13572 is merged. Is the issue resolved?

**Comment by eliofery** [comment]
Use Yii version 2.0.51, advanced template.

**From the documentation:** [Link to guide](https://www.yiiframework.com/doc/guide/2.0/en/test-fixtures#defining-a-fixture)

> The fixture data for an ActiveFixture fixture is usually provided in a file located at **fixturepath/data/tablename.php**, where fixturepath stands for the directory containing the fixture class file, and **tablename** is the **name of the table associated** with the fixture. In the example above, the file should be **@app/tests/fixtures/data/user.php**. 

**My observations:**

The **common/fixtures** directory contains the file **UserFixture.php**.

```php
class UserFixture extends ActiveFixture
{
    public $modelClass = 'common\models\User';
}
```

The **common/tests/_data** directory contains the file **user.php**.

```php
return [
    [
        'username' => 'bayer.hudson',
        'auth_key' => 'HP187Mvq7Mmm3CTU80dLkGmni_FUH_lR',
        //password_0
        'password_hash' => '$2y$13$EjaPFBnZOQsHdGuHI.xvhuDp1fHpo8hKRSk6yshqa9c5EG8s3C3lO',
        'password_reset_token' => 'ExzkCOaYc1L8IOBs4wdTGGbgNiG3Wz1I_1402312317',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'email' => 'nicole.paucek@schultz.info',
    ],
];
```

**When executing the command:**

```bash
php yii fixture/load User
```

Following the previous paragraph from the documentation, I expect that the data from the **common/tests/_data/user.php** file will be imported into the **user** table. But this does not happen, although the command runs without errors or warnings.

I tried renaming the **_data** directory to **data**, the result is the same. 

The issue was resolved by adding the following line of code to the **common/fixtures/UserFixture.php** file:

```php
class UserFixture extends ActiveFixture
{
    public $modelClass = 'common\models\User';
    public $dataFile = '@common/tests/_data/user.php'; // solves the problem
}
```

I'm surprised that the default **UserFixture** implementation that comes out of the box doesn't work without some extra work from the user. Although according to the documentation it should work, since the condition for naming files and database tables is met.

**Comment by machour** [comment]
@eliofery You're commenting on a 7 years old, closed, issue.
Please consider [opening a new issue](https://github.com/yiisoft/yii2-app-advanced/issues/new/choose) if you want to report a bug.
