### ISSUE TITLE
Fixture “User” loaded in MySQL but not loaded in MS SQL Server

### ISSUE THREAD

**Issue by AlekseyBykov** [yiisoft/yii2-app-advanced#173]
### What steps will reproduce the problem?

Execute `yii fixture/load User` with the following configuration:

```
'components' => [
    'db' => [
        'class' => '\yii\db\Connection',
        'dsn' => 'sqlsrv:Server=...;Database=yii2advanced',
        'username' => 'sa',
        'password' => '...',
        'charset' => 'utf8',
        'tablePrefix' => 'tbl_',
    ],
],

```
### What's expected?

Fixture's data should have been loaded into the database. If I switch to the local MySQL database, the data is loaded successfully.
### What do you get instead?

> Exception 'yii\base\InvalidParamException' with message 'Table not found: []'
### Additional info

| Q | A |
| --- | --- |
| Yii vesion | 2.0.7-dev or 2.0.8 |
| PHP version | 5.4.45 |
| Operating system | Windows 7 Home Basic or Windows 10 Pro |

**Comment by AlekseyBykov** [comment]
See [Run `fixture/load User` fails to load User data #172](https://github.com/yiisoft/yii2-app-advanced/issues/172#)

**Comment by samdark** [comment]
Works well with current master.
