### ISSUE TITLE
App domain

### ISSUE THREAD

**Issue by cyrexcyborg** [yiisoft/yii2-app-advanced#179]
How to get an application domain? For example i need serve contents of front.dev/img/ to back.dev

**Comment by cyrexcyborg** [comment]
I think this is simple, i have a misunderstandings. So, figured out how to serve images to admin(backend). How can i get images from backend? I need it like `<img src="http://front.dev/uploads/img/img.png">` but being served from backend.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-link-backend-frontend.md
