### ISSUE TITLE
FR: "Skip if exists" for init-command

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2-app-advanced#18]
I would like to be able to skip files if they exist during init. 

Because of security I do not store my database password files in source control. too many people cooperate on the project that do not need them. Instead my environments folder contains a template configuration file but with "<FILL ME>" instead of the passwords.

The files are initially installed as part of the init command (which I LOVE btw!) and then get updated on the server itself. These don't often change (only when we rotate passwords), but the regular config does once in a while, requiring a new init to put them in place.

I would love to be able to say that "if this file exists, never overwrite this", so that I don't have to update the passwords file every time this happens. I can implement this myself (perhaps a "locked" config entry) and issue a PR if it is deemed useful here.

**Comment by samdark** [comment]
I'd suggest a simple array with ignored file paths at the very top of `init`.

**Comment by samdark** [comment]
PR would be great.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/pull/19
