### ISSUE TITLE
Creating links from backend to frontend

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2-app-advanced#186]
Current documentation regarding the topic is no accurate if I'm not mistaking.

In a normal scenario when `backend` and `frontend` applications reside on different domains

~~~php
echo Yii::$app->urlManagerFrontend->createUrl(...);
~~~

will create a relative link to a `backend` domain. `UrlManager::createAbsoluteUrl()` should be used instead and `UrlManager::$baseUrl` should point to the `frontend` domain.

**Comment by samdark** [comment]
Yes. You're right. Thanks!
