### ISSUE TITLE
wrong config file in frontend/web/index-test.php

### ISSUE THREAD

**Issue by fbarrento** [yiisoft/yii2-app-advanced#192]
after init the application in Development environment the index-test.php file have this line

`$config = require(__DIR__ . '/../../tests/codeception/config/frontend/acceptance.php');`

it must be 

`$config = require(__DIR__ . '/../config/test.php');`

yii2-app-advanced @master

**Comment by samdark** [comment]
Fixed. Thanks for reporting.
