### ISSUE TITLE
missing AcceptanceTester

### ISSUE THREAD

**Issue by fbarrento** [yiisoft/yii2-app-advanced#193]
It's missing the AcceptanceTester under frontend/tests/_support

**Comment by samdark** [comment]
Have you executed `composer exec codecept build`?

**Comment by samdark** [comment]
@DavertMik http://codeception.com/docs/02-GettingStarted says actor classes should be built automatically but it seems it's not what actually happens. Any idea why? Should `composer exec codecept build` be added to readme?

**Comment by fbarrento** [comment]
@samdark when I run `composer exec codecept build` the AcceptanceTester is build and the acceptance tests can be run in the frontend suite. 

I suggest to fix the docs and add a new point under 

> To execute acceptance tests do the following:  

6. Build the test suite:
`composer exec codecept build`

Or add the file to the project as the FunctionalTester and UnitTester are.
