### ISSUE TITLE
Bad submission error - something to do with _csrf-frontend?

### ISSUE THREAD

**Issue by cchandel** [yiisoft/yii2-app-advanced#194]
### What steps will reproduce the problem?
Using latest yii2-app-advanced and posting an Ajax request causes a bad submission error even when the csrf token is being posted (obtained by yii.getCsrfToken()).

### What's expected?
That the Bad submission error not be triggered.

### What do you get instead?
I get the bad submission error.

### Additional info
There is a new config setting         
'request' => [
             'csrfParam' => '_csrf-frontend',
 ],
 Commenting the 'csrfParam' =>'_csrf-frontend' line gets things going as expected.
 
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 7.0.9
| Operating system | Arch Linux

**Comment by cebe** [comment]
have you used `yii.getCsrfParam()` to obtain the name of the POST field?

**Comment by cchandel** [comment]
Yes. For now the POST req is 
_csrf:<the CSRF Token>

**Comment by cebe** [comment]
it should send `_csrf-frontend: ...`

**Comment by cchandel** [comment]
It's working if I use _csrf-frontend.

Something ws broken in my install -  a fresh install shows the POST field as _csrf-frontend.

This issue is solved. Thanks.
