### ISSUE TITLE
./yii serve only serves the console app

### ISSUE THREAD

**Issue by igravity** [yiisoft/yii2-app-advanced#196]
### What steps will reproduce the problem?

 - Go into the folder with a shell
 - `./yii serve localhost:8888 --docroot:"frontend\web"

### What's expected?
The `frontend` app should he served using the PHP inbuilt server. I should be able to access this using the address provided.

### What do you get instead?
Document root "C:\xampp\htdocs\mtnt-2\console/web" does not exist.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.6.24
| Operating system | Windows 7

**Comment by samdark** [comment]
Parameters are specified in format of `--name="value"`. You've used `:` instead of `=`.
