### ISSUE TITLE
how to create tests application?

### ISSUE THREAD

**Issue by zplzpl** [yiisoft/yii2-app-advanced#198]
### What steps will reproduce the problem?
use tests;

### What's expected?
create api application on the codeception dir;

### What do you get instead?
i don't know how to create;

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.5
| Operating system | windows 7_X64

**Comment by zplzpl** [comment]
Can be automatically generated applications?

**Comment by zplzpl** [comment]
tests/
-codeception
--api
--service
--backend
--common
--console

like this;

**Comment by samdark** [comment]
Same as the one in `frontend`: https://github.com/yiisoft/yii2-app-advanced/tree/master/frontend/tests

I think it should be somehow documented...

**Comment by zplzpl** [comment]
I should copy the frontend application and change the application name to api?

Can be automatically generated applications?

**Comment by zplzpl** [comment]
my yii2 version as v2.0.9;

directory structure different of master branch;

**Comment by samdark** [comment]
Adding another tier isn't currently a feature of advanced template and I don't think it should be. It's already complex enough.

master has testing framework refactored. It will be released soon.

**Comment by zplzpl** [comment]
thank you for your job.
