### ISSUE TITLE
CSS changes not reflected in browser (nginx config + Vagrant issue)

### ISSUE THREAD

**Issue by codermaverick** [yiisoft/yii2-app-advanced#205]
### What steps will reproduce the problem?
Default Vagrant installation (php, mysql, nginx, etc. all provisioned via provided vagrant script).

### Description
Changes in CSS files are *sometimes* not reflected in the browser - it seems like previous CSS files are cached somewhere.
According to what I found online, it seems like this is a common issue when using nginx with Vagrant/VirtualBox.

### Proposed solution
"sendfile" should be set to "off" in nginx.conf to avoid this issue.

Good description of the problem here:
https://jeremyfelt.com/2013/01/08/clear-nginx-cache-in-vagrant/

**Comment by SilverFire** [comment]
Fixed, thank you

**Comment by subhadeepchowdhury41** [comment]
Saved me
