### ISSUE TITLE
No mention of cookie requests

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-app-advanced#210]
### What steps will reproduce the problem?

Documentation - no repro
Referring to this page: https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md
### What's expected?

This article on Yii2 basic mentions ... manual cookie request setup
https://github.com/yiisoft/yii2/blob/master/docs/guide/start-installation.md#installing-via-composer

Modify the config/web.php file by entering a secret key for the cookieValidationKey configuration item (this is done automatically if you are installing Yii using Composer):

// !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
'cookieValidationKey' => 'enter your secret key here',
### What do you get instead?

No mention
### Additional info

| Q | A |
| --- | --- |
| Yii vesion |  |
| PHP version |  |
| Operating system |  |

**Comment by samdark** [comment]
There should be no need to. When installed via composer it should generated the key automatically.

Which commands were executed exactly?

**Comment by samdark** [comment]
This one was part of yii2-composer which is fixed by recent release.
