### ISSUE TITLE
Please update testing docs

### ISSUE THREAD

**Issue by Gourmentt** [yiisoft/yii2-app-advanced#211]
Hi there,

in [this](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-testing.md) doc mentioned `yii_test` and `yii_test.bat`, but this files not exists. However, we have `/tests/codeception/bin/yii`, and seems that it meant to be used for tests.

So pls update testing doc, I am not so familiar with testing, and it's bad to start from confusing docs.
Thanks

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.6
| Operating system | Ubuntu 16.04 LTS

**Comment by samdark** [comment]
It's correct. `yii_test` and `yii_test.bat` will be there after you'll `init` your app with dev environment.

**Comment by Gourmentt** [comment]
Sorry but `yii_test` not created even after I inited with `init`

**Comment by samdark** [comment]
Are you init-ing with dev environment? https://github.com/yiisoft/yii2-app-advanced/tree/master/environments/dev

**Comment by Gourmentt** [comment]
Yep, but I haven't that files that you have:

```
/environments/dev# ls
backend  common  console  frontend  tests  yii
```


I installed yii2 as described in [installation guide](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md)

`composer global require "fxp/composer-asset-plugin:^1.2.0"
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application`

then cd into root of app and

`init`, selected 'dev'

Then set up db and migrate. My environment dir differs from repo version. 
I'll try to install yii app into another empty dir to reproduce this thing

**Comment by samdark** [comment]
These files are in the next release which will happen soon.

**Comment by Gourmentt** [comment]
Heh, okay
