### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2-app-advanced#214]
Hi,

Can we get official docker image for yii2 advanced template like vagrant??

**Comment by bscheshirwork** [comment]
docker-compose image group may be? Or php based single image?

**Comment by bscheshirwork** [comment]
Hi! 

See https://github.com/bscheshirwork/docker-yii2-app-advanced

**Comment by schmunk42** [comment]
Related: https://github.com/yiisoft/yii2-app-basic/pull/157
