### ISSUE TITLE
Init script and files not in all environments

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#215]
Lets say env1 has a file "somefile" not present in env2. When initializing env1 and then initializing env2 the file "somefile" must be removed by init script.

**Comment by samdark** [comment]
I'm not sure about that... how about files which are not part of any environments?

**Comment by PowerGamer1** [comment]
> how about files which are not part of any environments?

Don't touch those files of course. Init should only remove the files present in the other environments but not in the environment being currently initialized.

**Comment by samdark** [comment]
@yiisoft/core-developers need opinions.

**Comment by cebe** [comment]
@PowerGamer1 what is the use case for such behavior?

**Comment by PowerGamer1** [comment]
> what is the use case for such behavior?

`yii-app-advanced` already has a file used in dev environment but not used in prod environment: `environments/dev/frontend/web/index-test.php`.

Another example, one environment uses `enablePrettyUrls` and as such needs `.htaccess` and the other environment does not use `enablePrettyUrls` so it needs no `.htaccess` file.

Yet another example: prod environment needs `maintenance.html` file (for closing site access for maintenance) but dev environment does not need that file.

Etc.

`Init` script should clean up the files not used in the environment being initialized.

**Comment by cebe** [comment]
makes sense to me.

**Comment by dynasource** [comment]
> Init script should clean up the files previously deployed from the environments folder that are not used in the environment being initialized.

this is risky if someone has customized files. If this is done, this should be done in a safe way.

**Comment by PowerGamer1** [comment]
> this is risky if someone has customized files. If this is done, this should be done in a safe way.

No more risky than overwriting existing customized files as `init` script does now so a clean up could be done in a similar way with a prompt.

**Comment by samdark** [comment]
Thought more about it. This one could be implemented and will be merged.

**Comment by WadeShuler** [comment]
The init leaves behind files that aren't replaced by the following init.

To see this happen, init your app into `dev` then init it into `production`. You will see `yii_test` and `yii_test.bat` are left behind from the `dev` init. I assume other files as well.

We need a way to clean this up... Either a `deleteFiles` array in `environments/index.php` or for Yii to be intuitive enough to know what it is currently initialized as (ie: Yii knows it is in `dev`). Then when you init into production, it looks through the `environments/dev` to build a `deleteFiles` array, and deletes the files from the app. Then inits into production.
