### ISSUE TITLE
Cannot install advanced template via composer

### ISSUE THREAD

**Issue by iSynth** [yiisoft/yii2-app-advanced#218]
$ composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application

Installing yiisoft/yii2-app-advanced (2.0.10)
  - Installing yiisoft/yii2-app-advanced (2.0.10)
    Downloading: 100%

Created project in yii-application
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

  [ErrorException]
  zlib_decode(): data error

**Comment by samdark** [comment]
Looks like Composer issue. Report to https://github.com/composer/composer
