### ISSUE TITLE
Installing Messages

### ISSUE THREAD

**Issue by olissongs** [yiisoft/yii2-app-advanced#225]
### What steps will reproduce the problem?

composer create-project --prefer-dist yiisoft/yii2-app-advanced myproject

### What's expected?

no console messages, like many times before

### What do you get instead?

symfony/browser-kit suggests installing symfony/process ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.4.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
codeception/base suggests installing codeception/specify (BDD-style code blocks)
codeception/base suggests installing flow/jsonpath (For using JSONPath in REST module)
codeception/base suggests installing phpseclib/phpseclib (for SFTP option in FTP Module)
codeception/base suggests installing league/factory-muffin (For DataFactory module)
codeception/base suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge support)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| PHP version      | 7.0.8
| Operating system | Ubunt 16.04

**Comment by olissongs** [comment]
so when are these suggestions necessary to install additional pakages?

**Comment by cebe** [comment]
> so when are these suggestions necessary to install additional pakages?

if you want to use them ;) this is only for your information that they exist. None of these are related to yii though.
