### ISSUE TITLE
Codeception CodeCoverage 0/0

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-app-advanced#234]
### What steps will reproduce the problem?
codecept run --coverage --coverage-xml --coverage-html

### What's expected?
code coverage result != 0/0. 

### What do you get instead?
```
Time: 11.38 seconds, Memory: 32.00MB
OK (24 tests, 67 assertions)
Code Coverage Report:  
  2017-01-27 11:06:47  
 Summary:              
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)
```

I add 
```
coverage:
    enabled: true
```
into global `codeception.yml` or frontend `frontend/codeception.yml` or suite 'frontend/test/functional.suite.yml';

additional add `white_list` (in each variant)
```
    white_list:
        include:
            - ../frontend/models/*
            - ../frontend/controllers/*
            - ../common/models/*
            - ../common/controllers/*
            - ../backend/models/*
            - ../backend/controllers/*
```

but has no effect.

**Any idea?**

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  51bcb06ecfebf718bad102fc3a8011fd0eb091dd
| PHP version      | 7.1
| Operating system | debian (docker image here https://github.com/bscheshirwork/docker-yii2-app-advanced)

**Comment by samdark** [comment]
Do you have XDebug installed and configured properly?

**Comment by samdark** [comment]
I've seen it in the docker config but it worth validating.

**Comment by bscheshirwork** [comment]
I updated the environment and clear the xdebug config string.

some problem, nothing changes.
all test is ok, but codecoverage 0/0

**Comment by bscheshirwork** [comment]
```
Time: 11.63 seconds, Memory: 32.00MB

OK (24 tests, 67 assertions)


Code Coverage Report:  
  2017-02-07 08:20:33  
                       
 Summary:              
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)

Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
XML report generated in coverage.xml
root@3ea47d386b54:/project# php -i|grep xdebug
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
xdebug
xdebug support => enabled
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.extended_info => On => On
xdebug.file_link_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.halt_level => 0 => 0
xdebug.idekey => PHPSTORM => PHPSTORM
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_aggregate => Off => Off
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /tmp => /tmp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => Off => Off
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => localhost => localhost
xdebug.remote_log => no value => no value
xdebug.remote_mode => req => req
xdebug.remote_port => 9001 => 9001
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3

```

**Comment by Faryshta** [comment]
i can confirm this issue.

`./vendor/bin/codecept run --coverage --coverage-xml`

doesn't generate any report of coverage or file report not even on a clean clone of yii2-app-advanced.

I though it was due to phpunit upgrade but today codeception 2.2.11 was released and it doesn't have any dependency to phpunit 6 anymore so that is no longer a possibility.

`./vendor/bin/codecept run -c backend/ --coverage --coverage-xml`

fails too so its not just the `codeception.yml` file.

**Comment by harpcio** [comment]
I have the same issue but only on Unix system. 
When I fire the codeception in docker on Mac, everything is ok.

**Comment by BAWES** [comment]
Works for me when defining as follows:
```
coverage:
    enabled: true
    include:
        - /*
```

**Comment by hofrob** [comment]
I'm not sure if this helps or what exactly is going on. But I can only add the following:

- The header "HTTP_X_CODECEPTION_CODECOVERAGE" is not set during acceptance and functional testing. So c3.php is not collecting any info.
- But even when I manually set this header like so `$I->haveHttpHeader('X_CODECEPTION_CODECOVERAGE', 'something');` code coverage is still zero.
- A clean project (no framework, just codeception, one entryscript and one class) does not give the desired result when using the recommended setup (separate docker container for web server, application (php-fpm) and database).

So this may not be a problem with Yii itself, but with the way c3.php collects and delivers coverage data.

Does anyone have any info on what the problem is with code coverage when using a separate (nginx) container for web?

**Comment by samdark** [comment]
@DavertMik ?

**Comment by schmunk42** [comment]
@bscheshirwork `white_list` should be `whitelist`, see https://github.com/yiisoft/yii2-app-basic/pull/70/files

For an example acceptance testing configuration with coverage (Docker) you can have a look at phd5:
- https://github.com/dmstr/phd5-app/blob/master/web/index.php#L17-L22
- https://github.com/dmstr/phd5-app/tree/master/tests/codeception

**Comment by samdark** [comment]
Thanks @schmunk42.

**Comment by bscheshirwork** [comment]
Once upon time...

I can see is [some changes](http://codeception.com/docs/11-Codecoverage) now.

I try it again

**Comment by bscheshirwork** [comment]
Without directly set `include` again 0/0; and not touch c3.php outside.
```sh
Code Coverage Report:  
  2017-11-07 09:29:15  
                       
 Summary:              
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)

Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
XML report generated in coverage.xml

```
work with `include`/`exclude` in frontend/backend `codeception.yml`
```
    include:
        - models/*
        - controllers/*
    exclude:
        - assets/*
        - config/*
        - runtime/*
        - views/*
        - web/*
        - tests/*
```
```sh
Code Coverage Report:    
  2017-11-07 09:46:55    
                         
 Summary:                
  Classes: 33.33% (1/3)  
  Methods: 60.00% (6/10) 
  Lines:   40.82% (20/49)

\frontend\controllers::SiteController
  Methods:  75.00% ( 3/ 4)   Lines:  92.31% ( 12/ 13)
\frontend\models::ContactForm
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% (  8/  8)
Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
XML report generated in coverage.xml
```
