### ISSUE TITLE
bug: `User` fixture not found 

### ISSUE THREAD

**Issue by Nicolai6120** [yiisoft/yii2-app-advanced#235]
### What steps will reproduce the problem?

1. install default advanced template
2. try to load User fixture by command

`php yii fixture/load User --namespace='common\fixtures'`

### What's expected?

Fixtures were successfully loaded from namespace: "common\fixtures"

### What do you get instead?

Some fixtures were not found under path:
        /var/www/t.dev/common/fixtures

Check that they have correct namespace "common\fixtures" 
        1. User

Error: No files were found for: "User".
Check that files exist under fixtures path: 
"/var/www/t.dev/common/fixtures".

## `**Please rename User.php to UserFixture.php, change class name accordingly.**`

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| PHP version      | 5.6
| Operating system | Centos 7

**Comment by samdark** [comment]
Fixed. Thanks for reporting.
