### ISSUE TITLE
composer.lock must be under git or under .gitignore

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2-app-advanced#237]
### What steps will reproduce the problem?

Install yii2-app-advanced.

### What's expected?

There aren't any uncommited files in project.

### What do you get instead?

There is uncommited file **composer.lock** in project.

**Comment by samdark** [comment]
That's expected. It should be in your own git, not in template's one.

**Comment by rugabarbo** [comment]
> It should be in your own git, not in template's one.

Then... it should be **under .gitignore**

**Comment by samdark** [comment]
No.

**Comment by cebe** [comment]
https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file
