### ISSUE TITLE
[bug?] Backend renders "<?php" into every empty controller

### ISSUE THREAD

**Issue by panique** [yiisoft/yii2-app-advanced#24]
There's a weird little issue in the advanced version of Yii 2.0.3:

In the backend, every controller renders a response than ALWAYS has "<?php" in the beginning. You can test this by creating an empty controller, running it and looking at the output source (CTRL+U in firefox).

You'll probably just see `<?php`.

This get problematical when rendering out files that seriously brake when starting with <?php.

You can "fix" this by commenting out the line
```
require(__DIR__ . '/../config/bootstrap.php');
```
in the backend's index.php or by adding a `return` to the bootstrap,.php

Can somebody confirm ?
Have a great day guys.

**Comment by githubjeka** [comment]
Something that I have met.
https://github.com/githubjeka/yii2-rest/issues/3

**Comment by dguhl** [comment]
The opening tag of a PHP source file requires one additional whitespace character, currently missing in bootstrap.php files.
http://php.net/manual/en/language.basic-syntax.phptags.php#116883

**Comment by samdark** [comment]
I can't reproduce it. Also there are newlines right after `<?php` tags in `bootstrap.php` files.

**Comment by githubjeka** [comment]
Yes. Perhaps you stumbled on something else I once wrote.
