### ISSUE TITLE
Composer "extra.asset-installer-paths" option deprecated

### ISSUE THREAD

**Issue by p2made** [yiisoft/yii2-app-advanced#243]
On running `composer update` on my Yii2 projects, Composer now reports `The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option`.

So should the default `composer.json` be updated to reflect this?

This modification produces correct results for me...

```
  "config": {
    "fxp-asset": {
      "installer-paths": {
        "npm-asset-library": "vendor/npm",
        "bower-asset-library": "vendor/bower"
      }
    },
    "process-timeout": 1800
  },
  "extra": {
  },
```

**Comment by p2made** [comment]
Thanks @samdark :)

**Comment by samdark** [comment]
You can speed things up by doing a pull request.

**Comment by cebe** [comment]
Quite sure that changing this will break a lot of things. If we do it, it should be in 2.1.

**Comment by fbens** [comment]
I encountered this problem too.

**Comment by cebe** [comment]
switched to asset-packagist, so this issue is not relevant anymore: https://github.com/yiisoft/yii2-app-advanced/commit/4a892a65c122bcea294fd93fc4fb860b2789dd58

**Comment by mirkhamidov** [comment]
And how to upgrade existing project?

**Comment by schmunk42** [comment]
> And how to upgrade existing project?

@mirkhamidov What do you mean, did you update `fxpio/cap`? What's your issue with upgrading a project?

For the record: If using `fxpio/cap` I'd also strongly recommend to update to `1.4.1` (globally) and add these options:

```
            "vcs-driver-options": {
                "github-no-api": true
            },
            "git-skip-update": "2 days",
            "pattern-skip-version": "(-build|-patch)"
```

**Comment by cebe** [comment]
> And how to upgrade existing project?

depends on what you want to do:

- if you want to switch to asset-packagist, add the repository as described on https://asset-packagist.org/ and configure aliases properly: https://github.com/yiisoft/yii2-app-advanced/blob/4ab8ac7d8884e8e959d42c13e8d7cb30ef3475e4/common/config/main.php#L3-L6

- if you want to stay with composer asset plugin, you need to add up-to-date configuration:

https://github.com/yiisoft/yii2-app-basic/blob/0c87fab0c3c9d0ada04a85f4982aeffc08b76cc7/composer.json#L31-L39

**Comment by mirkhamidov** [comment]
@cebe thanx!

**Comment by MichalYosef** [comment]
Hello, i'm having this problem.

added as reccomended here to the composer.json config:

"fxp-asset":{
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            }

I still get this when running composer update:  

The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option

What should I do?

**Comment by schmunk42** [comment]
You can still use these options, it's "just" a warning. 
Please note that, if there is a `"config" : {"fxp-asset"` section, it will take precedence.

More details ... https://github.com/fxpio/composer-asset-plugin/issues/293

**Comment by MichalYosef** [comment]
the composer update runs ok now
but i get this when running on xampp:

Invalid Parameter – yii\base\InvalidParamException

The file or directory to be published does not exist: C:\xampp\htdocs\yii2\NEW\project-3-john-bryce-error-composer\_protected\vendor\bower/jquery/dist
1. in C:\xampp\htdocs\yii2\NEW\project-3-john-bryce-error-composer\_protected\vendor\yiisoft\yii2\web\AssetManager.php at line 456

**Comment by schmunk42** [comment]
You have mixed `\` and `/` in your path, actually this should be converted automatically... 

CC: @cebe we had a similar issue before, you had a solution I can't dig up :)

**Comment by MichalYosef** [comment]
yeah well it was generated by composer i guess
don't know how to fix it...

**Comment by ctala** [comment]
So at the end how we fix it ? xD

**Comment by turb0bur** [comment]
Changed composer.json file in accordance to the current version in sources. And it totally decreased the time of installing composer dependencies.
`"config":            {
    "process-timeout": 1800,
    "fxp-asset":       {
      "enabled": false
    }
  },
  "repositories":      [
    {
      "type": "composer",
      "url":  "https://asset-packagist.org"
    }
  ],`
