### ISSUE TITLE
Feature Request : Adding a docker setup.

### ISSUE THREAD

**Issue by sazo** [yiisoft/yii2-app-advanced#244]
Hallo,

Is their any interest in making a docker-compose file for spinning up a docker container environment.
If the maintainers think it is a good idea then i will make a PR for it.

Will make it as easy as running the command "docker-compose up yii2-app-frontend yii2-app-backend" and then you have a running environment.

Running the yii-cli will be "docker-compose run --rm yii".

Will make it work for linux, windows(Docker for Windows) and mac(Docker For Mac). :)

Just give me the go and i will make it.

**Comment by cebe** [comment]
I think it would be a useful addition, we have Vagrant already so we should add docker too.

**Comment by samdark** [comment]
Duplicated of https://github.com/yiisoft/yii2-app-advanced/issues/214
