### ISSUE TITLE
-local configs from environments not protected by .gitignore

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#245]
According to https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md:

> For example, production database connection could be in  prod  environment  -local.php  config. These local configs are added to  .gitignore  and never pushed to source code repository.

Such local configs inside `frontend/config`, `backend/config`, `common/config` folders are protected from getting into source code repository by .gitignore present in those folders. Yet the very same copies of those local configs are still getting into a source code repository from the `environments` folder.

I think this should be solved by adding .gitignore into the environments folder to protect local configs there. Not sure what effect it will have on `init` script (like will the `init` script copy the .gitignore along with configs from `environments` folder, etc).

**Comment by samdark** [comment]
Why do you have local configs in environments?

**Comment by PowerGamer1** [comment]
> Why do you have local configs in environments?

What do you mean? The local configs are the only configs present in environments folder. The yii2-app-advanced template has them, for example:
https://github.com/yiisoft/yii2-app-advanced/tree/master/environments/prod/frontend/config

**Comment by samdark** [comment]
Ah. These are templates, not final configs.

**Comment by PowerGamer1** [comment]
These "config templates" are changed from time to time too. Are you suggesting that when such a config needs to be changed it should be edited directly on production site? In practice it is much more convenient to keep and edit complete and latest versions of all configs inside environment folder.

This also enables easy transfer of new app build to prod server: you just archive the whole root folder (containing frontend, common, etc) which locally is inited to dev configs, transfer archive to prod server, extract and use init script to setup prod configs.

If, as you suggest (if that's what you suggest), prod configs should exist only on prod, then it would be too tedious to transfer new app build on prod, since there are too many different configs in different subfolders (frontend/config, common/config, etc) and a lot of care will need to be taken to not include local dev configs spread around different folders in app archive being transferred to prod server.

**Comment by samdark** [comment]
Yes, I am suggesting exactly that. Local stuff is what's kept secretly out of repository.

**Comment by PowerGamer1** [comment]
There are way too many -local config files:
```
backend\config\main-local.php
backend\config\params-local.php
common\config\main-local.php
common\config\params-local.php
console\config\main-local.php
console\config\params-local.php
frontend\config\main-local.php
frontend\config\params-local.php
```

As I explained above it is very inconvenient to keep them only on the server and each time a new app version should be deployed to watch to not accidentally overwrite any of those files. It is much more convenient to keep these configs in `environments` folder and use `init` script on server during deployment of new version.

I don't see any reason why you don't want to support such scenario (when `environments` folder has actual config files for all environments, not just half-empty "templates"). All that is needed is protect those files inside `environments` folder from getting into source code repo with .gitignore - absolutely the same way it is ALREADY done for copies of those configs in other app folders.

**Comment by samdark** [comment]
If you keep these in `environments`, these are getting into source control that is not what these are intended for.

**Comment by mikk150** [comment]
I suggest doing what I am doing right now.
environment configs are not `-local.php` but rather `-env.php` that are in CVS and are merged with `-local.php` configs that are just symlinked files

Because of that, [Deployer](https://github.com/deployphp/deployer/) can manage deployments pretty much automatically without me worring if DB credentials go to CVS or not
