### ISSUE TITLE
couple of bugs in tests codecept

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2-app-advanced#247]
### What steps will reproduce the problem?
codecept build / codecept run
### What's expected?

success

### What do you get instead?

errors

### Additional info

1) in backend is not creating the acceptance tester,etc (where is the acceptance.suite.yml)
2) in frontend (where is the config/test.php)
3) syntax in unit tests are old

example (LoginFormTest.php)
actual:
expect('model should not login user', $model->login())->false();
expected:
$this->assertFalse($model->login(),'model should not login user');

i will continue testing

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11
| PHP version      | 5.6
| Operating system | XXXXX

**Comment by moltam** [comment]
Syntax is not old, the `expect` functions are provided by [Codeception/Verify](https://github.com/Codeception/Verify) package. I don't get any errors with the tests.

**Comment by samdark** [comment]
Can't reproduce as well.
