### ISSUE TITLE
user table insecure

### ISSUE THREAD

**Issue by hbschr** [yiisoft/yii2-app-advanced#25]
in table `user` the columns `username` and `password_reset_token` should be given an unique key. otherwise the implementations of `findByUsername` and `findByPasswordResetToken` could return unexpected results.

**Comment by githubjeka** [comment]
`username` and `email` unique through validation. The validation is easy to change, according to how you want. The table needs to be changed migration - more difficult.
See https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/models/SignupForm.php#L25

`password_reset_token ` it remains valid for some time and is generated based on the timestamp, so unique in its kind too.

The issue can be closed.:balloon:

**Comment by cebe** [comment]
while there is a validation in the model it is still good to force some basic constraints in the database which will catch bugs that may have been introduced at application level.

**Comment by hooman-pro** [comment]
And i think thant it's beter to, auth_key filed be a unique filed and tow user can not have same auth_key, 
generateAuthKey function should check it, and generate unique auth_key.
becaus  login  mecanisme use it to find one user and if tow user have same auth_key it's possible to have table bug (one user login Instead another user because same auth_key). that's currect? or i'm in mistake?? 
if i'm correct add this issue, else explane me 

with respect "hooman mirghasemi"

**Comment by githubjeka** [comment]
`auth_key` used for "remember Me" cookie:

```php
protected function sendIdentityCookie($identity, $duration)
    {
        $cookie = new Cookie($this->identityCookie);
        $cookie->value = json_encode([
            $identity->getId(),
            $identity->getAuthKey(),
            $duration,
        ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        $cookie->expire = time() + $duration;
        Yii::$app->getResponse()->getCookies()->add($cookie);
    }
```
`auth_key` with `id` is unique. Because column is not unique. 

You should check `reffer-attrib` (e.g. `email`) when you use `auth_key`  in other cases

**Comment by hbschr** [comment]
to prevent confusion: i wasn't talking about `auth_key` for "rember Me" cookie. i was talking about the columns which are used in any kind of `findBy*`. afaik these are `user.username` and `user.password_reset_token`.

since uniqueness is ensured in php code @githubjeka is right: this issue could be closed. personally i agree with @cebe (ensuring uniqueness on db level in case of bugs in php code), but decision is yours ;-)
