### ISSUE TITLE
Could not send activity mail to: (Calling unknown method: yii\console\Request::get())

### ISSUE THREAD

**Issue by kpankrath** [yiisoft/yii2-app-advanced#253]
Hi,

i'm using version 1.2.0-beta.3

The daily cronjob produces the following error message in the log:

"Could not send activity mail to: [NAME OF THE USER] (Calling unknown method: yii\console\Request::get())"

Does anyone know how to fix this`?

**Comment by samdark** [comment]
Seems it's connected with the code of your application, not the framework itself. Try asking at forums or at #yii IRC channel at frenode.
