### ISSUE TITLE
New Apps - Don't work until you create alias in common/config/bootstrap.php

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2-app-advanced#257]
### What steps will reproduce the problem?
Take the "frontend" directory and duplicate it as "mainsite" or "api" or whatever you want. Try to access the newly created app in your browser, ie: `localhost/yii2-advanced/mainsite/web/`

### What's expected?
I expected the stock yii2 app page exactly like the `frontend`.

### What do you get instead?

    An Error occurred while handling another error:
    exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "site/error".' in /Applications/XAMPP/xamppfiles/htdocs/yii2-members-system/vendor/yiisoft/yii2/base/Module.php:532

### Additional info

To get your new app to work, open `common/config/bootstrap.php` and add an alias to your new app like so:

    Yii::setAlias('@mainsite', dirname(dirname(__DIR__)) . '/mainsite');

You have to create an alias for every new app that you create!

Maybe the docs should have a link to it in the installing yii2 advanced section. A blue note box, letting them know that if they want to create more apps by duplicating frontend/backend/etc; that they must create an alias in `common/config/bootstrap.php`.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11.2
| PHP version      | 5.6.21
| Operating system | macOS Sierra 10.12.3

**Comment by samdark** [comment]
It's documented: https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-adding-more-apps.md
