### ISSUE TITLE
Logic behind post-install-cmd

### ISSUE THREAD

**Issue by bizley** [yiisoft/yii2-app-advanced#259]
What is the exact reason behind this line in `composer.json` for Advanced Project Template:

    "scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=n"
    }

1. For `composer create-project` is does not work.
- composer runs `install`,
- there is no `composer.lock` file (good, it's template, there should not be one) so `post-install-cmd` is [not called](https://getcomposer.org/doc/articles/scripts.md#command-events),
- `composer.lock` is created (too late for script).
2. For next `composer install` it works (`composer.lock` is present) but it sets "Development" environment.
- `composer.json` is shared amongst environments,
- `composer.lock` should be shared as well,
- `composer install` should be run for each environment to make sure the same versions are used,
- `init` with "Development" settings makes no sense for Production env.
3. Documentation says to run `init` anyway.

So the question is - **why is this command there by default**?

**Comment by WadeShuler** [comment]
### What it is for

When you install Yii for the first time, and run `composer install`, it is supposed to init into development for you. Maybe the Yii team was wanting to cut down on support issues from noobs using Yii for the first time and not knowing to run init? :)

If you read the Composer docs: https://getcomposer.org/doc/articles/scripts.md

> post-install-cmd: occurs after the `install` command has been executed with a lock file present.

Also, I don't think composer will run the scripts IF the lock file is not present. Composer install should run the scripts, however those are only ran IF the lock file is there.

From the docs:

> If there is no composer.lock file, Composer will create one after dependency resolution

It seems that this is just how Composer behaves on your first `install` when there is no lock file. Try running `composer update` on a fresh copy of Yii, then run `composer install`, and see if this still happens.

---

So if you want to run `composer install` and not have Yii run the init for you, run this:

    composer install --no-scripts

Generally, when you push live, you should use this:

    composer install --no-dev --no-scripts

Also, if you look here, https://github.com/composer/composer/issues/5070, there was an issue with the post command running when it should. A Google search reveals there have been numerous issues regarding the post command running. From a bug in specific versions of Composer, to hosts such as Heroku. Is your Composer version old? Maybe the issue isn't fixed? Just tossing some things out there...


### My Opinion

I think the post install command should be removed. It adds unnecessary overhead when pushed live. If I push to my host using just `composer install`, it inits into dev. Then my hooks run init into production. So, when live in production, Yii inits twice. While it is just swapping files around, it is unnecessary.

As I listed above, I run `composer install --no-dev --no-scripts` when pushing live. While many of us know how to handle this... I think that the post install script should be removed. Let us handle what we need, when we need it.

**Comment by samdark** [comment]
> Maybe the Yii team was wanting to cut down on support issues from noobs using Yii for the first time and not knowing to run init? :)

Yes.

**Comment by samdark** [comment]
Agree overall.
