### ISSUE TITLE
FixtureHelper does not run InitDbFixture

### ISSUE THREAD

**Issue by daniel-mc** [yiisoft/yii2-app-advanced#26]
The `FixtureHelper` does not run `InitDbFixture` and it does not disable integrity checks during the initialization resulting in `yii\db\IntegrityException` when clearing tables with foreign keys.

The issue does not appear with unit tests, only with functional and acceptance tests.

What would be the suggested workaround for this? The db object cannot be accessed in `FixtureHelper` so adding `checkIntegrity(false/true)` wrappers around the `load/unloadFixture` calls does not work.

**Comment by githubjeka** [comment]
@Ragazzo

**Comment by Ragazzo** [comment]
@daniel-mc it will not, since `InitDbFixture` is used by default only in [`DbTestCase`](https://github.com/yiisoft/yii2-codeception/blob/master/DbTestCase.php), you should include manually `InitDbFixture` in your `FixtureHelper` class file in `fixtures()` method

**Comment by daniel-mc** [comment]
That works, thank you. Shouldn't this be there by default since there's a DB fixture in there by default as well?

**Comment by Ragazzo** [comment]
Not sure about that, however if you will make a `PR` we can discuss it
