### ISSUE TITLE
index-test.php dropped on next page with pretty urls htaccess file

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2-app-advanced#264]
### What steps will reproduce the problem?

Enable pretty URLs, including the htaccess file in the web directory. Go to `http://yoursite.dev/frontend/web/index-test.php`. Now click a link, like `About` or `Contact`. The `index-test.php` will be dropped from the URL.

Is the problem the htaccess file?:

    RewriteEngine on
    
    # If a directory or a file exists, use it directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    
    # Otherwise forward it to index.php
    RewriteRule . index.php

It obviously tells it to redirect everything through `index.php`.

So while testing, can I not manually use this `index-test.php` in my browser? Would this break Codeception tests?

### What's expected?

It should retain `index-test.php` in the URL.

### What do you get instead?
Drops `index-test.php` and redirects back to the main `index.php` file.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11
| PHP version      | 5.6.30
| Operating system | macOS Sierra

**Comment by rob006** [comment]
http://www.yiiframework.com/doc-2.0/yii-web-urlmanager.html#$showScriptName-detail - set it to `true`.

**Comment by WadeShuler** [comment]
Perfect, thanks!

Wouldn't it make sense to add the following to `common/config/test.php`?

    'urlManager' => [
        'showScriptName' => true,
    ],

or at least comment it out similar to how pretty urls is commented out in `main.php`?

**Comment by samdark** [comment]
Yes, it would make sense.
