### ISSUE TITLE
amOnRoute/amOnPage - Functional tests fail with external url rules when enablePrettyUrl = true

### ISSUE THREAD

**Issue by MatthewDaize** [yiisoft/yii2-app-advanced#267]
I am trying to build out and application and run into a pretty tough bug to pin... Some help would be great :)

I am trying to organise URL rules in an external file for cleanliness purposes. When doing so, the codeception functional tests completely stop working if pretty URLs are enabled. I have to disable pretty url or move routes into the configuration file for it to work.

This happens on an un-modified clone of the app (obviously excluding enabling prettyUrl and moving URL rules into external file).

Thanks!

### What steps will reproduce the problem?
Configure Yii2 Advanced App:
* Clone advanced app (latest)
* Create external url_rules file -- simple return array
```
<?php
return [];
```
* Change config.url so enablePrettyUrl is turned on, require_once the new external url_rules file
```
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => require_once 'url_rules.php'
        ],
```
* Run Codeception (functional) tests -- have at least one that uses amOnRoute helper function.

### What's expected?
functional tests should succeed. Tests that use amOnRoute/amOnPage direct tests to route

### What do you get instead?
```
frontend\tests\functional\AboutCest::checkAbout()
yii\base\ErrorException: Invalid argument supplied for foreach()
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/base/Object.php:107
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/di/Container.php:381
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/di/Container.php:381
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/di/Container.php:156
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/BaseYii.php:344
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/di/ServiceLocator.php:135
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/vendor/yiisoft/yii2/base/Application.php:568
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/frontend/tests/_support/_generated/FunctionalTesterActions.php:643
/home/mdaize/Projects/Deadcheck/yii2-app-advanced/frontend/tests/functional/AboutCest.php:10
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.11
| PHP version      |5.6.30
| Operating system |Fedora 25

**Comment by samdark** [comment]
You should use `require` since `require_once` will return `true` if called more than once.
