### ISSUE TITLE
Met problem when Installing from an Archive File 

### ISSUE THREAD

**Issue by xeoshow** [yiisoft/yii2-app-advanced#275]
### What steps will reproduce the problem?
https://github.com/yiisoft/yii2/blob/master/docs/guide/start-installation.md#installing-from-an-archive-file-
Following above link, will get problem:
Warning: require(D:\phpStudy\WWW\testcloud\backend\web/../../vendor/autoload.php): failed to open stream: No such file or directory in D:\phpStudy\WWW\testcloud\backend\web\index.php on line 5

### What's expected?
Open the correct page

### What do you get instead?
Warning: require(D:\phpStudy\WWW\testcloud\backend\web/../../vendor/autoload.php): failed to open stream: No such file or directory in D:\phpStudy\WWW\testcloud\backend\web\index.php on line 5

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | yii2-app-advanced-2.0.11
| PHP version      |5.5.38
| Operating system |windows 7

**Comment by sazo** [comment]
You are missing composer installing :)

**Comment by xeoshow** [comment]
Oh, I thought by using zip file, composer is then not necessary... 
Could you kindly add how to use composer in this section?
Thanks!

**Comment by sazo** [comment]
https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md

**Comment by Ravshanjon** [comment]
You must
1.Composer install https://getcomposer.org/
2.http://www.yiiframework.com/download/
3.composer.phar create-project yiisoft/yii2-app-advanced advanced 2.0.11
 OR composer.phar create-project yiisoft/yii2-app-basic basic 2.0.11


2017-05-23 17:59 GMT+05:00 xeoshow <notifications@github.com>:

**Comment by xeoshow** [comment]
Looks better now, I will try to create a GitHub OAuth token first and report back, thanks! ...

D:\phpStudy\WWW>composer.phar create-project yiisoft/yii2-app-advanced advanced 2.0.11

D:\phpStudy\WWW>composer create-project yiisoft/yii2-app-advanced advanced 2.0.11
Installing yiisoft/yii2-app-advanced (2.0.11)
  - Installing yiisoft/yii2-app-advanced (2.0.11)
    Loading from cache

Created project in advanced
Loading composer repositories with package information
Updating dependencies (including require-dev)

Could not fetch https://api.github.com/repos/jquery/jquery-dist, please create a GitHub OAuth token to
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+PRI2RL0WMOOREA4+2017
to retrieve a token. It will be stored in "C:/Users/Administrator/AppData/Roaming/Composer/auth.json" f
Token (hidden):

**Comment by sazo** [comment]
Follow https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md :)
