### ISSUE TITLE
Where bower in 2.0.12 advanced ? 

### ISSUE THREAD

**Issue by skvarovski** [yiisoft/yii2-app-advanced#277]
### What steps will reproduce the problem?
install from composer source today

and see 
Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: site.loc/vendor\bower/jquery/dist' 

rename bower-assets to bower solved the problem. It's just me because of the old composer?

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.1
| Operating system | Win10-64bit

**Comment by samdark** [comment]
@SilverFire ?

**Comment by rob006** [comment]
You should probably update `composer-asset-plugin` to 1.3.x line.

**Comment by skvarovski** [comment]
Win10 x64
Composer version 1.4.2 
update fxp/composer-asset-plugin (v1.2.2 => v1.3.1)

try composer install 
and all is OK !!!
