### ISSUE TITLE
Functional test of PJAX

### ISSUE THREAD

**Issue by azjoss** [yiisoft/yii2-app-advanced#278]
### What steps will reproduce the problem?
Try to cover by functional test of login form which is loaded with PJAX on login modal show
```
        $I->see('Welcome!', 'h1');
        $I->click('#loginBtn');
        $I->see('Login', '#modalLogin h4');
        
        // here pjax is loading and form is appeared
      
       $I->submitForm('#loginForm', [
            'LoginForm' => [
                'username' => 'user',
                'password' => '123456',
            ]
        ]);
```

### What's expected?
test success

### What do you get instead?
[FAIL] Form element with '#loginForm' was not found.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11.2
| PHP version   | 7.0.15
| Codeception | 2.3.2
| PHPUnit | 6.1.4 
| Operating system |

**Comment by cebe** [comment]
pjax can not be loaded in functional tests, as no browser with JS is involved.
