### ISSUE TITLE
ListView/Gridview Summary Count Error

### ISSUE THREAD

**Issue by Rjgoolsby** [yiisoft/yii2-app-advanced#284]
I don't know if this is a bug or a misunderstanding by the User. 

If you use a join in an Active Query the summary is wrong with your Gridview or ListView. Here's the real case scenario. 

Migrations:

        $this->createTable('{{%products}}', [
            'id'                    => $this->primaryKey(),
            'name'                  => $this->string()->notNull(),
        ], $tableOptions);

        $this->createTable('{{%productsCategory}}', [
            'id'            => $this->primaryKey(),
            'name'          => $this->string()->notNull(),
        ], $tableOptions);

        $this->createTable('{{%productsCategoryTags}}', [
            'id'            => $this->primaryKey(),
            'productsId'     => $this->integer()->notNull(),
            'categoryId'    => $this->integer()->notNull(),
        ], $tableOptions);
       $this->addForeignKey('fk_productsCategoryTagsproductsId','{{%productsCategoryTags}}', 'productsId','{{%products}}', 'id', 'CASCADE', 'RESTRICT');
        $this->addForeignKey('fk_productsCategoryTagsCategoryId','{{%productsCategoryTags}}', 'categoryId','{{%productsCategory}}', 'id', 'CASCADE', 'RESTRICT');

The reason for 3 tables is because each Product can be unlimited categories but also filterable and searchable. This flexibility is required by the client so we just use a column in products to store a single integer or json object. 

Ok. We'll continue.

### What steps will reproduce the problem?
Add 3 Records to Table productsCategory.
Add 10 Records to Table products (Make sure each Product has a Category Id, your restraints will force the record to be in the table Categories).
Add 20 records to productsCategoryTags. (Add 2 records for each product using 2 of the 3 productsCategory Options).

Create your basic CRUD using gii. 
Adjust your ProductsSearch to also filter by Category ID

`

        //Search Class
        class ProductsSearch extends Products{
                 public $categories;
                 public function rules(){
                         return [
                               [['id'], 'integer'],
                               [[''name','categories'], 'safe'],
                          ];
                  }
                 public function attributes(){
                           // add related fields to searchable attributes
                           return array_merge(parent::attributes(), ['search','categories']);
                  }
                  public function search($params){
                         $query = Products::find()->joinWith('productsCategoryTags');
                         // add conditions that should always apply here

                         $dataProvider = new ActiveDataProvider([
                                'query' => $query,
                          ]);

                         $this->load($params);

                          if (!$this->validate()) {
                                // uncomment the following line if you do not want to return any records when validation fails
                                // $query->where('0=1');
                                return $dataProvider;
                          }
                         // grid filtering conditions
                         $query->orFilterWhere(['like', 'name', $this->name])
                               ->orFilterWhere(['in', 'productsCategoryTags.categoryId', $this->categories]);
                          return $dataProvider;
                }
`

### What's expected?
When I go to the initial Gridview or Listview I expect to see a total summary of 10 records

### What do you get instead?
When I go to the initial Gridview or Listview I expect to see a total summary of 10 records but I get 13. Then it gets worse, if you adjust the pagination, say just for testing purposes, adjust pagination to 2. It doesn't show 2 records on each page. Some pages only have 1 record

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12-dev
| PHP version      | 7.0.18-0
| Operating system | ubuntu0.16.04.1

If this is by design please explain the reasoning and if it isn't please let me know if there's a fix on the way or what is the work around for the summary. Filtering and searching is working as designed, Pagination and the Summary portions however are not. 

Thanks for everyone's hard work.

**Comment by cebe** [comment]
> If you use a join in an Active Query the summary is wrong with your Gridview or ListView. Here's the real case scenario.

if you join, the query may contain duplicate rows, which will result in a count to return more rows than there are unique records. ActiveQuery will filter duplicate records so you see fewer records on a page than the page size. You need to ensure that the result of the join returns no duplicate rows for example by adding `distinct` to the query.

**Comment by Rjgoolsby** [comment]
So User Error. I'd rather it be me than the framework. Thanks!!!!!!

**Comment by Ziggizag** [comment]
Hmm,

I have same case - added "->distinct()" to query but still see less record on page than page size!

**Comment by machour** [comment]
@Ziggizag it was just an example given. You could also try ->groupBy() or asking for help on the forum: https://forum.yiiframework.com/
