### ISSUE TITLE
composer install problem

### ISSUE THREAD

**Issue by sasha6806** [yiisoft/yii2-app-advanced#286]
### What steps will reproduce the problem?
`composer create-project --prefer-dist yiisoft/yii2-app-advanced yii2-advanced
Content-Length mismatch
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Installing yiisoft/yii2-app-advanced (2.0.12)
  - Installing yiisoft/yii2-app-advanced (2.0.12): Downloading (100%)
Created project in yii2-advanced
Loading composer repositories with package information
Updating dependencies (including require-dev)
Content-Length mismatch
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Repository\RepositorySecurityException]
  The contents of https://packagist.org/p/provider-latest%24f4920536ed7674e5fe07492a03dbcaf1f2cd45be677ba1b1ead4d016fc4ec034.json
   do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]`
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      | 7.0.20
| Operating system | windows 10

**Comment by samdark** [comment]
Means your connection is shaky or, in fact, there's MTIM. It's out of scope of Yii. Please report to Composer if you're confident that your connection is OK.
