### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by ak868308** [yiisoft/yii2-app-advanced#287]
see attachment
![screenshot from 2017-07-10 13-09-43](https://user-images.githubusercontent.com/7982249/28027829-2c4c87d0-65b8-11e7-9f24-dfd25a1410c2.png)

While update the access token everything is working fine with current token but this is not working.

**Comment by sheillendra** [comment]
There explained where to go, and you must have a github account.

**Comment by ak868308** [comment]
Hi @sheillendra 
I already have an account :) If I dont have any account how I can post this issue :) 
FYI friend I already created an access token for the same but it shows the same error message every time.

Thanks for your help

**Comment by sheillendra** [comment]
Follow the "Head to url" in the attachment above for generate access token, copy the token and paste in command prompt, you can see the end of text in your attachment.

**Comment by ak868308** [comment]
Hi @sheillendra 
If you look at my attachment I already followed that step. You can also see in the above attachment it says Invalid token and after that composer checking the for lower version and again asked for the same access token!
Thanks

**Comment by sheillendra** [comment]
have you copy and paste the token to prompt?

**Comment by ak868308** [comment]
Yes

**Comment by samdark** [comment]
That's something Composer is failing to do. We can solve it within Yii.
