### ISSUE TITLE
Error on configuration module with absolute path

### ISSUE THREAD

**Issue by Bertagit** [yiisoft/yii2-app-advanced#290]
In my site configurations (frontend/donfig/main-local.php) I need to load an extra-site module from directory which I use to share modules between distinct sites, to do this on 'class' configuration I put the absolute path of modules directory es:
path to site:
/var/www/html/my-site/(yii-advanced-app-directories)
path to share modules:
/var/www/html/common_sites_modules/(my-modules-direcotries)

on config:
`my-module => [
   'class' => '/var/www/html/common_sites_modules/my-module/MyModule'
]`
where `MyModule` is a class module generated by Gii.

When I try to use module instance I receive this error:
`Class /var/www/html/common_sites_modules/my-module/MyModule does not exist`
this is generated in yii2/di/Container.php at the row 422:` $reflection = new ReflectionClass($class);`
Is it a bug or only a configuration error?

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| PHP version      | 7.0.18-0
| Operating system | ubuntu0.16.04.1

Thanks

**Comment by cebe** [comment]
> '/var/www/html/common_sites_modules/my-module/MyModule'

class must be specified with a namespace, not with a path.
