### ISSUE TITLE
Boolean database fields always true according to Yii ActiveRecord models

### ISSUE THREAD

**Issue by dominicfinch** [yiisoft/yii2-app-advanced#298]
### What steps will reproduce the problem?
1) Using a MySQL database, I created a table with a boolean column (defined as BIT(1))
2) Used gii to generate a model of the database table (inherited from ActiveRecord)
3) Wrote a simple controller which loaded data into model class and the model class then accessed the DB table class mentioned in step 2.
4) I populated the database table using a python script I wrote to give me some test data.
5) When I read data back via my Yii model, the boolean field was always returning as true even when a simple SELECT query on the table in question would prove this wasn't the case.

### What's expected?
Boolean model field was always returning true even when the field in the database was in fact false.

### What do you get instead?
e.g.
```
SELECT account_locked FROM users WHERE id=x;      -- Returns false according to the database
$user = Users::findOne(['id' => x]);                               -- $user->account_locked is always true..
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  Current development version - I cloned this repo 2 or 3 days ago. Working off master branch
| PHP version      |    7.1.8
| Operating system |    Windows 7  (64 Bit)

Possible solution: Use TINYINT column type in database to store boolean flags. Gii then uses the integer validator which works correctly.

**Comment by samdark** [comment]
Need exact schema and data you've used to test it.

**Comment by cebe** [comment]
See:

- https://github.com/yiisoft/yii2/issues/9006#issuecomment-127050808
- https://3v4l.org/fchVS PDO converts query data to strings so you end up with a string container a null byte, which is considered true in PHP. Its a bad idea to use BIT(1) in MySQL in combination with PDO imo.

**Comment by samdark** [comment]
I think we need to document it somehow...

**Comment by samdark** [comment]
Is not related to advanced app template. There are notes on the matter in docs.
