### ISSUE TITLE
ContactFormTest tearDown can't be executed

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2-app-advanced#30]
I got a error

```
yii\base\ErrorException: unlink(C:\Users\Evgeniy\Documents\basic\runtime/mail/testing_message.eml): No such file or directory
```

in line https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/codeception/frontend/unit/models/ContactFormTest.php#L24
and in basic app too.

You need to add `@` or the check `is_file`.

**Comment by cebe** [comment]
any reason why it does not exist?

**Comment by githubjeka** [comment]
Sorry in advanced is OK.

In basic https://github.com/yiisoft/yii2-app-basic/blob/master/models/ContactForm.php#L61
