### ISSUE TITLE
@shopify/polaris

### ISSUE THREAD

**Issue by cbepxpa3ym** [yiisoft/yii2-app-advanced#300]
Not able to specify this npm package in composer.json.

https://asset-packagist.org/package/detail?fullname=npm-asset/%40shopify/polaris

That page even looks broken. Package name is stripped.

I got this message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package npm-asset/@shopify/polaris could not be found, it looks like its name is invalid, "@" is not allowed in package names.

Here is the nmp package page: https://www.npmjs.com/package/@shopify/polaris

What to do?

**Comment by schmunk42** [comment]
In your message it looks like even the package-name is not passed correctly to composer ("The requested package npm-asset/ could not be found") - this would be an issue with asset-packagist then. CC: @hiqsol 

But additionally, it is also a limitation from composer. (Tested with an project-name containing @), see also https://getcomposer.org/doc/04-schema.md#name 

```
name : invalid value (vendor/cool/@app-dev), must match [A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*
```

I could not install it using the fxpio-asset-plugin, also.

```
  [InvalidArgumentException]                                                                                                                        
  Could not find package npm-asset/@shopify/polaris at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability   
```

I also tried to [override the name](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#overriding-the-config-of-a-vcs-repository), no luck either CC: @francoispluchino

---

### The bigger picture

It might be possible to convert the @ into something like '--AT--" internally, but this would be pretty hacky to me. Or composer would have to allow this, which is not very likely.

If package name like this are a showing up on npm - I never saw an "@" before 🙄  - it's even more important to consider improvements like https://github.com/yiisoft/yii2/issues/14297#issuecomment-327565136

**Comment by francoispluchino** [comment]
@schmunk42 See the doc [Work with the NPM scopes](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#work-with-the-npm-scopes).

The good format for Composer is:

```
npm-asset/shopify--polaris
```

**Comment by hiqsol** [comment]
```json
npm-asset/shopify--polaris
```
This works with asset-packagist too.
