### ISSUE TITLE
Url encoding problem in reset password email

### ISSUE THREAD

**Issue by fabrizio11** [yiisoft/yii2-app-advanced#302]
### What steps will reproduce the problem?
When resetting password, sometimes it happens that the link is not rendered/encoded properly. 
I got some error logs from a production site. It seems like the reset url sometimes brokes because of the '&' character that is being displayed as &amp; in the address bar.

### What's expected?
I expect to get, for example: 
http://localhost/frontend/web/index.php?r=site%2Freset-password&token=4WUJpPow2Rh7KLu06FKhvjTegHys1sLl_1505470372

### What do you get instead?
The user apparently gets this in the address bar: 
http://localhost/frontend/web/index.php?r=site%2Freset-password&amp;token=4WUJpPow2Rh7KLu06FKhvjTegHys1sLl_1505470372

getting a Bad Request (#400) exception.

I see here the url is html encoded: https://github.com/yiisoft/yii2-app-advanced/blob/master/common/mail/passwordResetToken-html.php

Is it only a problem of the email client? Probably it does not render the html correctly?

**Comment by rob006** [comment]
This is probably client bug. I have similar problems with different systems (not based on Yii) and never been able to reproduce it - URL in email was OK, but i can still find invalid requests in logs. I fixed this by rewrite rule in `.htaccess`:

```
RewriteEngine On
RewriteCond %{QUERY_STRING} (.*)&amp;(.*)
RewriteRule .* %{REQUEST_URI}?%1&%2 [N,R=301]
```

**Comment by fabrizio11** [comment]
Thanks for the reply. 
I tried your solution creating an htaccess inside yii2 root but it didn't work, probably I'm missing something... maybe I have to put that in the web folder?

**Comment by kubisflo** [comment]
I think it depends on your exact apache configuration, but placing it in the web folder should work.
