### ISSUE TITLE
common/config/main.php

### ISSUE THREAD

**Issue by patpwilly** [yiisoft/yii2-app-advanced#304]
Follow installation steps to do the _composer global require "fxp/composer-asset-plugin:^1.3.1"_
run composer update
Enter page that requires bower components, something like Kartik/DatePicker and it fails by looking in the wrong directory.
Bower gets installed to vendor/bower because the composer.json has the _extra_ configuration setup, but Aliases are setup to point to vendor/bower-asset due to this code.

https://github.com/yiisoft/yii2-app-advanced/blame/master/common/config/main.php
Should installation directions change or was this supposed to be held off until 2.1

What is the correct answer to move forward with composer  updates with existing code bases?

| Q                | A
| ---------------- | ---
| 2.0.12|
| 5.6 |
| Windows|

**Comment by schmunk42** [comment]
It depends on your configuration, by default the asset-plugin installs assets to `vendor/bower-asset`, which was overridden by earlier default configs in `composer.json` to `vendor/bower`.

You should be able to **remove** this section from your `composer.json` file:

    "config": {
        "fxp-asset": {
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            },
        }
    }

To move along with the asset-plugin and asset-packagist's defaults ... in the current advanced app template, which is using **asset-packagist.org**, `vendor/bower-asset` is the default, therefore the config you've linked override the default framework paths.

Note: This might fail, if there are assets using an alias like `@vendor/bower/...` but that would be an issue with the asset, as all assets should use `@bower`.

@yiisoft/core-developers We should think about changing this in `setVendorPath` also: https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L460-L466

**Comment by samdark** [comment]
@schmunk42 changing what in `setVendorPath`?

**Comment by schmunk42** [comment]
```
        Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
        Yii::setAlias('@npm', $this->_vendorPath . DIRECTORY_SEPARATOR . 'npm');
```

to 

```
        Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower-asset');
        Yii::setAlias('@npm', $this->_vendorPath . DIRECTORY_SEPARATOR . 'npm-asset');
```

**Comment by samdark** [comment]
It is there already: https://github.com/yiisoft/yii2-app-advanced/blob/master/common/config/main.php. Will be tagged with next release.

**Comment by schmunk42** [comment]
I meant to change the default it in `yii\base\Application` also, would be 

| Location | old default | current default |
|--------|---|---|
| fxpio/cap | bower-asset | bower-asset |
| fxpio/cap (composer.json) | bower | bower-asset (actually: *none*, but falls back to above) |
| asset-packagist | bower-asset | bower-asset |
| **yii\base\Application** | **bower** | **bower** (only one which is different) :x: |
| advanced-app (config.php) | bower (was *none*, falls back to above) | bower-asset |

**Comment by samdark** [comment]
Then it won't be compatible with applications based on older templates.

**Comment by schmunk42** [comment]
> Then it won't be compatible with applications based on older templates.

Yes, it's a BC-break, which would have to be noted in the UPGRADE guide. Not nice, but having the `Application` class with another default is also not good.

The root cause of this issue has been introduced by switching to asset-packagist by default, without having an option to map the path for it, or am I wrong?

Just my 2 cents.

**Comment by samdark** [comment]
No, it's not only BC break. This way we'll force people to drop fxp plugin which is not desirable in some cases. Currently it's all good — old apps work out of the box. New ones too — paths are in app templates.

**Comment by schmunk42** [comment]
> This way we'll force people to drop fxp plugin which is not desirable in some cases.

I don't see how this is someone *forcing* to drop cap.
Anyway, it's fine not to change it in 2.0, because of BC, but consider changing the default in 2.1.

**Comment by samdark** [comment]
Yes. For 2.1 it should be changed.

**Comment by rob006** [comment]
> No, it's not only BC break. This way we'll force people to drop fxp plugin which is not desirable in some cases. 

Paths like `vendor/npm` and `vendor/bower` are yii-specific. fxp plugin uses `vendor/npm-asset` and `vendor/bower-asset` by default. So changing this will not force anyone to drop fxp plugin, but actually make using it even easier (not need to global plugin if you're using only `composer install`, less configuration in `composer.json`).

**Comment by samdark** [comment]
OK. Seems I'm a bit lost. @SilverFire need your help.

**Comment by rob006** [comment]
@samdark I mean that right now only BC stops us from changing paths in `yii\base\Application`. 

I think that this issue can be closed - we could adjust `yii\base\Application` in 2.1.

**Comment by samdark** [comment]
OK.

**Comment by schmunk42** [comment]
I thought about this a again and depending on details of the asset management in 2.1 (see https://github.com/yiisoft/yii2/issues/14862) it might make no sense to adjust paths in such a way.

When assets are handled by native tools like `npm` or `yarn` they should reside in `path/to/node_modules` - although that path can be adjusted, there are various issues about it.
Moreover bower-support might be dropped completely(?) in 2.1

**Comment by samdark** [comment]
From the core? Yes. Most likely it will be dropped. But not from the apps. Web app will come with some kind of asset management pre-made, be it native npm or foxy or anything else.
