### ISSUE TITLE
new install through composer , get The file or directory to be published does not exist: D:\xampp\htdocs\mytest/vendor\bower/jquery/dist

### ISSUE THREAD

**Issue by polinwei** [yiisoft/yii2-app-advanced#308]
### What steps will reproduce the problem?
1. new install through composer create-project --prefer-dist yiisoft/yii2-app-advanced mytest
2. after yii migrate
3. run http://localhost/mytest/frontend/web/
<code>
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: D:\xampp\htdocs\mytest/vendor\bower/jquery/dist
</code>

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |   v2.0.12
| PHP version      | 7.1.7
| Operating system | win7

**Comment by schmunk42** [comment]
Do you have this folder `D:\xampp\htdocs\mytest/vendor\bower/jquery/dist` or one called `bower-asset`? 
Is it OK to have mixed slashes on Win7?

**Comment by polinwei** [comment]
I don't have the `D:\xampp\htdocs\mytest/vendor\bower` , but I have  `D:\xampp\htdocs\mytest\vendor\bower-asset\jquery\dist`

**Comment by polinwei** [comment]
When does the issue occur?
After new install

What do you see?
The file or directory to be published does not exist: D:\xampp\htdocs\mytest/vendor\bower/jquery/dist 

What was the expected result?
Congratulations!
You have successfully created your Yii-powered application.

**Comment by schmunk42** [comment]
Which version of the asset-plugin do you have? `composer global show`

**Comment by polinwei** [comment]
<pre>
D:\xampp\htdocs>composer global show
Changed current directory to C:/Users/polin.wei.GLOBEUNION/AppData/Roaming/Composer
fxp/composer-asset-plugin v1.2.2 NPM/Bower Dependency Manager for Composer
</pre>

**Comment by schmunk42** [comment]
You need at least 1.3 - I recommend to update to 

    composer global require "fxp/composer-asset-plugin:^1.4.1"

**Comment by polinwei** [comment]
It is work. schmunk41 Thanks!!

**Comment by cebe** [comment]
> Is it OK to have mixed slashes on Win7?

yes, thats fine. PHP will handle conversion.
