### ISSUE TITLE
Remote code coverage causing problems

### ISSUE THREAD

**Issue by hofrob** [yiisoft/yii2-app-advanced#317]
### What steps will reproduce the problem?

I did all these steps in a github repo: https://github.com/hofrob/yii2-codecoverage

after cloning do the following:
```
cd app
./dc initialize
./dc composer install
./dc test --coverage
```

Steps to reproduce without using my repo:

1. set up the following docker containers: database, application (php-fpm), web (nginx) ([commit](https://github.com/hofrob/yii2-codecoverage/commit/e2e6b12c04ce90028fa5c726969a24c7d9def569))
1. create a new yii2 advanced app ([commit](https://github.com/hofrob/yii2-codecoverage/commit/5914743f74fa99d17d601aaf9cc18c43857c4cd4))
1. edit db config in [main-local](https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/dev/common/config/main-local.php) ([commit](https://github.com/hofrob/yii2-codecoverage/commit/77424c29c51166aa976af0924d7ba18590c71e06))
1. (for simplicity) remove db config from [test-local](https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/dev/common/config/test-local.php)
1. enable code coverage ([commit](https://github.com/hofrob/yii2-codecoverage/commit/52616d5ab1c3e3e4796e6c69cf5352f77f96d180))
1. composer packages ([commit](https://github.com/hofrob/yii2-codecoverage/commit/0d30ca16eb8be701c92abb330e4cd19c3847ed5a)):  
```
composer remove --dev "codeception/base"  
composer require --dev "codeception/codeception"  
composer require --dev "codeception/c3" 
```
7. enable acceptance test with remote code coverage ([commit](https://github.com/hofrob/yii2-codecoverage/commit/75fe61a135bfe8e7e8a61bf11f1eeb38e0f4d6f9)):
  * include c3.php in every request
  * create action plus route to c3 action
  * for simplicity, change acceptance test browser to PhpBrowser

### What's expected?
Code coverage should be greater than 0

### What do you get instead?
0 lines, 0 files, 0%

### Additional info

No idea if this is connected, but the variable `$settings` in c3.php is sometimes undefined. And somehow codeception/c3.php is not able to write to the log destination. The error is

```
Could not write error to log file (/code/console/runtime/logs/c3tmp/error.txt), original message: Suite acceptance was not loaded
```
Which is the result of `$settings` being undefined as far as I understand.

I'd greatly appreciate input. Maybe it has something to do with the way docker is set up? Maybe we can fix this in the yaml files? We are out of ideas 😄 

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13
| PHP version      | 7.1
| Operating system | docker (linux)

**Comment by schmunk42** [comment]
Related: https://github.com/yiisoft/yii2-app-advanced/issues/234#issuecomment-341988805

**Comment by hofrob** [comment]
Saw the comment. But _remote_ code coverage is not used in this project.

**Comment by bscheshirwork** [comment]
@hofrob if your test namespace (like frontend\test) contain "\" try replace 
```
        $suite = strtr($e->getSuite()->getName(), ['\\' => '.']);
```
I prepare PR in codeception now

**Comment by bscheshirwork** [comment]
see https://github.com/Codeception/Codeception/issues/4610

**Comment by bscheshirwork** [comment]
> Suite acceptance was not loaded
@hofrob 
you must set 
```yml
coverage:
    remote_config: frontend/codeception.yml
```
for pass throw `c3.php` config `frontend`, not common

see https://github.com/bscheshirwork/yii2-app-advanced-rbac/blob/master/frontend/codeception.yml

**Comment by bscheshirwork** [comment]
@hofrob see https://github.com/yiisoft/yii2-app-advanced/issues/234#issuecomment-342433794
work with `include`/`exclude` in frontend/backend `codeception.yml`
```
    include:
        - models/*
        - controllers/*
    exclude:
        - assets/*
        - config/*
        - runtime/*
        - views/*
        - web/*
        - tests/*
```

**Comment by bscheshirwork** [comment]
> Operating system | docker (linux)
https://github.com/hofrob/yii2-codecoverage/blob/75fe61a135bfe8e7e8a61bf11f1eeb38e0f4d6f9/docker/docker-compose.yml#L42

If you use acceptance tests with `c3.php` and have difference in "mount" point between container`s 
in `codecept` run and acceptance browser run 

codeception cannot merge codecoverage and ignored codecoverage from acceptance with "wrong" absolute path. 

https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blame/master/docs/codeception.md#L114-L115

In this case we need set `remote: true`

**Comment by hofrob** [comment]
This mount point `../app/frontend/web:/code/frontend/web` is just for static files. You can remove it completely and the site still works (no CSS and JS of course).

**Comment by hofrob** [comment]
Thanks for all the info and help! I will try all the suggestions and report back.
