### ISSUE TITLE
tests runtime folder not ignored by version control.

### ISSUE THREAD

**Issue by PommeVerte** [yiisoft/yii2-app-advanced#32]
Hey guys. Upon setting up FileCache with the following in my `common/main.php`:

```php
'cache' => [
	'class' => 'yii\caching\FileCache',
],
```
When I run tests on tasks that use the cache the cache files are saved into `tests/codeception/config/runtime`. I'm quite satisfied with this behavior. There is however one issue in that the runtime folder is in no `.gitignore` so running tests locally will result in the runtime folder being picked up by the VCS (git).

I will cover this in our project but was wondering if it wasn't a good idea to do this in the skeleton as well (Since Yii2 covers such cases in `(frontend | backend | console)/runtime`).

I would suggest having a `tests/codeception/runtime` folder with a `tests/codeception/runtime/.gitignore`

**Comment by samdark** [comment]
Will be fixed by https://github.com/yiisoft/yii2-app-advanced/pull/190
