### ISSUE TITLE
.gitignore should not be inside webroot folder

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#324]
Currently .gitignore files can be accessed by website user through a browser which should not be happening.

All .gitignore files inside webroot folder (frontend\web) an its subfolders should be moved outside webroot folder (and the paths inside .gitignore files reconfigured accordingly).

**Comment by PowerGamer1** [comment]
Well, apparently git is unable to store empty folders inside repository. As a work around for that problem for `frontend\web\assets` folder it can be removed from the repository and created by `init` script.

**Comment by samdark** [comment]
What's wrong with having these files accessible?

**Comment by PowerGamer1** [comment]
> What's wrong with having these files accessible?

1. Regardless of the meaning of this file content, when user types http://mysite/.gitignore in the browser he should get a 404 Not Found response simply because this file have no value for the user and is not needed for the webserver to function (and as such should not exist on the webserver in the first place).

2. This particular file exposes the fact that the server code uses git as VCS - not a security risk by itself but still even this information should not be exposed.

**Comment by schmunk42** [comment]
> What's wrong with having these files accessible?

They should not be visible, depending on the setup they may expose file paths, etc..., but that's a web-server configuration issue to me.

Personally, I'd not commit empty folders into the repo (if possible), they should be created with appropriate permissions during installation/setup.

**Comment by samdark** [comment]
Could be done either way, yes. We have composer hooks and we can use these in app templates to create directories necessary in both basic and advanced apps. I don't think having it in `init` is a good idea since these directories are to be created regardless of environment.

**Comment by PowerGamer1** [comment]
> I don't think having it in `init` is a good idea since these directories are to be created regardless of environment.

It is reasonable to assume that in general case one environment may need an empty folder which all other environments won't - for example, some `cache` folder needed in `prod` env to cache something and not needed in `dev` env, etc.

To support such scenarios empty folder creation needs to be handled by `init`, not composer.

**Comment by samdark** [comment]
How about basic app template then?

**Comment by PowerGamer1** [comment]
> How about basic app template then?

I think even the most basic app needs to have a notion of environments and `init` script. As it stands now to deploy to production basic template app for the first time you need:
1) Manually edit `/yii` to disable debug mode.
2) Manually edit `web/index.php` to disable debug mode.
3) Manually edit `config/db.php` to set production server db login/password (**Oh and by the way here we have _another_ problem - in basic app the DB passwords are NOT protected from getting into VSC!**).
4) Manually edit urlManager configuration to setup proper production server name (to be able to send emails with urls to frontend from console app, ect).
5) Manually setup write permissions for dirs. like `runtime`, etc.
6) Probably take care of other stuff different on prod in comparison with dev environment.

Every time when deploying new app version to prod with code changes in `/yii`, `web/index.php`, 'config/*.php` AGAIN manually edit all these config to configure for prod differences.

Conclusion: every app needs to have environments and be able to handle them (through `init` script or whatever means). The concept of environments and related functionality needs to be moved into the Yii2 core.

**Comment by schmunk42** [comment]
> How about basic app template then?

Would be exactly the same for me. Ie. I got rid of all empty folders in [phd5](https://github.com/dmstr/phd5-app).

**Comment by PowerGamer1** [comment]
Observation: currently the empty folders that need to be created by `init` script are the same folders that need to be made writable by `init` script. Might as well make `setWritable` function of `init` script create a folder if it does not exist before making it writable?

**Comment by Faryshta** [comment]
So the idea is to create a `setUnreadable` option on `init` command and make all the .gitignore files `660` ?

**Comment by samdark** [comment]
Yes.

**Comment by Faryshta** [comment]
I am working on a PR. The permissions `0660` and `0600` allow me to read the `.gitignore` file from localhost. `0060` and `0000` doesnt allow me to access the file and send an apache 404 error instead. But I am not able to read the file on a text editor.

I couldnt find on internet another set up for the permissions. Is it ok if localhost can access the `.gitignore` file? Anyone has better permission set up?

**Comment by rob006** [comment]
> make all the .gitignore files 660

It does not make any sense. The problem is not `.gitignore` visibility but its existence. Just remove this file from `web` directory, define ignore rules in root `.gitignore` and create required directories by `init` command.
