### ISSUE TITLE
Compatibility issue with Yii2 tests and Codeception

### ISSUE THREAD

**Issue by davidnewcomb** [yiisoft/yii2-app-advanced#328]
During my work on #327, I discovered that there is a compatibility issue with Yii2 tests and Codeception that you might not be aware of.

Codeception 2.3 changes some of the key names in the test `.yml` files. Specifically `actor` becomes `actor_suffix` and `class_name` becomes `actor` (ref: [Name Changes](http://codeception.com/05-22-2017/codeception-2-3.html#algolia:p:nth-of-type(20)))

Currently Yii2 is using the old way (`actor`/`class_name`) which is BC with the latest 2.3 release of Codeception: but the time will come where you may have to change which versions are supported.

Just a thought!

**Comment by RobinJespersen** [comment]
Related problem:

Today my coverage report failed with the following message:
```
In ErrorHandler.php line 75:
                                                                               
  Declaration of Codeception\Coverage\DummyCodeCoverage::stop($append = true,  
   $linesToBeCovered = Array, array $linesToBeUsed = Array) should be compati  
  ble with SebastianBergmann\CodeCoverage\CodeCoverage::stop($append = true,   
  $linesToBeCovered = Array, array $linesToBeUsed = Array, $ignoreForceCovers  
  Annotation = false)  
```

The reason is this changed line:
https://github.com/sebastianbergmann/php-code-coverage/blob/25209536dbe0b1ded5c3ce8be57e7c79adca25e8/src/CodeCoverage.php#L290

Adding "phpunit/php-code-coverage": "~5.2.4" to my composer.json solved it for me for now.

**Comment by bscheshirwork** [comment]
> but the time will come where you may have to change which versions are supported.

the 2.4 have many changes on yii2 module.

**Comment by davidnewcomb** [comment]
Well you had better get on with it then ;)

**Comment by bscheshirwork** [comment]
IMPORTANT


https://github.com/Codeception/Codeception/commit/bc8433e3da75bc28c47df6f3afc22b9d4f65c0b4#diff-44ec756825174849c255c1ff28011dbaR17

* [Yii2] **Breaking** `$settings['configFile']` now supports absolute paths. In you have defined relative path to config in absolute manner

**Comment by samdark** [comment]
Re-checked:

- global configs are properly using `actor_suffix`.
- `class_name` is now `actor`.
- We're not using relative paths that look like absolute paths.
