### ISSUE TITLE
Avoid to rewrite .git files on environment initialization

### ISSUE THREAD

**Issue by cetver** [yiisoft/yii2-app-advanced#33]
If environment directory placed on different git repository initialization script trying to rewrite it:
```
Start initialization ...

  unchanged yii
   generate .git/COMMIT_EDITMSG
  unchanged .git/info/exclude
      exist .git/FETCH_HEAD
            ...overwrite? [Yes|No|All|Quit]
```
Fix:
rewrite https://github.com/yiisoft/yii2-app-advanced/blob/master/init#L94 to
```
if ($path === '.git' || $path === '.svn' || $path === '.' || $path === '..') {
```

**Comment by LAV45** [comment]
And what makes .git in your environments folder ?

**Comment by cetver** [comment]
Some developers don't have access to production settings. In GIT you can't revoke access from selected directory only for repository itself. For this environment directory placed in another GIT repository.

**Comment by LAV45** [comment]
in this case it is better to use the 
```php 
glob(__DIR__ . '/*'); 
``` 
in place readdir()

**Comment by samdark** [comment]
Decided not to change it in app template. It's quite specific case and could be adjusted manually if needed.

**Comment by cetver** [comment]
Strange decision, "svn" is also quite specific case (not all projects used SVN as VCS), but it skipped.

**Comment by samdark** [comment]
Oh, I was thinking about something totally diffrent :)

**Comment by samdark** [comment]
Fix applied. Thanks!
