### ISSUE TITLE
Aliases for bower and npm in console config

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#330]
Why would `console/config/main.php` have:
```PHP
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
```
?

Perhaps, these aliases were meant to be placed into `backend/config/main.php` instead?

**Comment by samdark** [comment]
These are for console assets compression.
