### ISSUE TITLE
*.dev domains (as suggested in the guide) are redirected to https in chrome 63

### ISSUE THREAD

**Issue by theOtherNir** [yiisoft/yii2-app-advanced#332]
### What steps will reproduce the problem?

1. install an advanced projectaccording to the installation guide 
(https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/README.md)
2. use chrome 63 (or is it just chromium maybe ?)
3. try to browse to the frontend / backend apps

### What's expected?
should be able to view the app

### What do you get instead?
chrome redirects *.dev URLs to HTTPS without attempting HTTP
if HTTPS is not installed then the server connection is refused. see the issue described here : 
https://superuser.com/questions/565409/chrome-how-to-stop-redirect-from-http-to-https
even when deleting the domain security policy, this domain still can't be opened.

#### suggestion
change the suggested domains from .dev to .local (or anything else for that matter)

### Additional info

| Q                | A
| ---------------- | ---
| Browser | Chromium - Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)
| Yii vesion       | 2.0.13.1
| PHP version      | 7.0.22
| Operating system | linux//ubuntu/mint 18.3

**Comment by samdark** [comment]
Just in time! I was wondering why that started to happen in my browser.

**Comment by theOtherNir** [comment]
LOL cool, just bumped into it today but didn't feel comfortable enough to PR etc.

**Comment by samdark** [comment]
Fixed https://github.com/yiisoft/yii2-app-advanced/commit/b4a32666394d107524bfa6037226157f1d093bf1

**Comment by uran1980** [comment]
@SEE

* [Chrome 63 forces .dev domains to HTTPS via preloaded HSTS](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/)
* [Dont use dev for development](https://iyware.com/dont-use-dev-for-development/)
