### ISSUE TITLE
vagrant up ошибка

### ISSUE THREAD

**Issue by aram1991** [yiisoft/yii2-app-advanced#335]
Установил Vagrant 2.0.1
Virtualbox 5.1.3 
Создал github personal token и поставил в файле vagrant-local.yml
При команде vagrant up ошибка.
"There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
* The 'hostmanager' provisioner could not be found.
Vagrant:
* Unknown configuration section 'hostmanager'.
Установил плагин Vagrant Host Manager (через команду "vagrant plugin install vagrant-hostmanager"),проблема не решилься
В чем может быть проблема? 
OS Windows 10

**Comment by samdark** [comment]
Duplicated of #336
