### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by aram1991** [yiisoft/yii2-app-advanced#336]
I installed Vagrant 2.0.1
Virtualbox 5.1.3
Created github personal token and put in the file vagrant-local.yml
The vagrant up command failed.
"There are errors in the configuration of this machine.
the following errors and try again:
vm:

The 'hostmanager' provisioner could not be found.
Vagrant:
Unknown configuration section 'hostmanager'.
I installed the plugin Vagrant Host Manager (via the command "vagrant plugin install vagrant-hostmanager"), the problem did not resolve
What could be the problem?
OS Windows 10

**Comment by zrk4939** [comment]
Your user home folder should not contain Cyrillic characters.

**Comment by DenisAlliswell** [comment]
@zrk4939 brilliantly! Absolutely true, that's the key.
