### ISSUE TITLE
yii2 user migration compatibility problem

### ISSUE THREAD

**Issue by Chico3001** [yiisoft/yii2-app-advanced#339]
I was moving my site and database from my development server:

> Linux mint 18.3 
> PHP 7.0.22-0ubuntu0.16.04.1
> mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64)
> collation utf8mb4_unicode_ci

to a production server to test it 

> PHP 5.6.30
> 5.6.23-cll-lve - MySQL Community Server 

When i uploaded my SQL script i came with this error:

> ALTER TABLE `user`
>   ADD PRIMARY KEY (`id`),
>   ADD UNIQUE KEY `username_UNIQUE` (`username`),
>   ADD UNIQUE KEY `email_UNIQUE` (`email`),
>   ADD UNIQUE KEY `password_reset_token_UNIQUE` (`password_reset_token`),
>   ADD KEY `fk_user_persons1_idx` (`id_person`)
> 
> #1071 - Specified key was too long; max key length is 767 bytes

So i had to limit all varchar lengths on my user table 

Shouldn't this be limited by default on the migration script to prevent this kind of errors?

```
$this->createTable('{{%user}}', [
            'id' => $this->primaryKey(),
            'username' => $this->string(60)->notNull()->unique(),
            'auth_key' => $this->string(32)->notNull(),
            'password_hash' => $this->string(70)->notNull(),
            'password_reset_token' => $this->string(70)->unique(),
            'email' => $this->string(60)->notNull()->unique(),

            'status' => $this->smallInteger()->notNull()->defaultValue(10),
            'created_at' => $this->integer()->notNull(),
            'updated_at' => $this->integer()->notNull(),
        ], $tableOptions);
```

**Comment by samdark** [comment]
The limit depends on the server config (encoding and collation, I guess). Implementing that is very complicated and I don't think it worth the effort (you should have encoding and collation set in migrations anyway).
