### ISSUE TITLE
themeing module not working?

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2-app-advanced#34]
Hi,
in basic application theming modules work currectly for me by configing following: http://www.yiiframework.com/doc-2.0/guide-output-theming.html#theming-modules

but when i setup that configuration in advanced application it's dosent work. my config in frontend:
'view' => [
            'theme' => [
                'pathMap' => [
                    '@frontend/views' => '@themes/test/frontend/views',
                    '@frontend/modules' => '@themes/test/frontend/modules',
                ],
            ],
        ],

first one : '@frontend/views' => '@themes/test/frontend/views', work currectly but second : '@frontend/modules' => '@themes/test/frontend/modules', that's for module dosen't work.
Am i done some thing worng? or it is a bug?

**Comment by samdark** [comment]
How do you render views from modules?

**Comment by hooman-pro** [comment]
yes, i'm in wrong way, 
I was setting a property in model "isBackend" and my module controller divide to front end and back end folders. for views I have same folders. and setting view path by this code:

if ($this->isBackend === true) {
            $this->setViewPath('@modules/' . static::$name . '/views/backend');
            if ($this->controllerNamespace === null) {
                $this->controllerNamespace =  'modules\\' . static::$name . '\controllers\backend';
            }
            
        } else {
            $this->setViewPath('@modules/' .  static::$name . '/views/frontend');
            if ($this->controllerNamespace === null) {
                $this->controllerNamespace =  'modules\\' . static::$name . '\controllers\frontend';
            }
        }
now what should i do to having this structure and them work correctly?

**Comment by hooman-pro** [comment]
the real reson for it: it's module view path is different by theme view path.
in module:
modules/modulename/views/frontend/default/index.php

in theme:
themes/themename/frontend/modules/modulename/views/default/index.php


and i khow if in theme i change it to:
themes/themename/modules/modulename/views/frontend/default/index.php
it will work, 

dose exist any way to work with fist directory path?

**Comment by samdark** [comment]
Closing since long time passed since then...
