### ISSUE TITLE
In Menu Widget not work linkOptions

### ISSUE THREAD

**Issue by mydesign** [yiisoft/yii2-app-advanced#349]
```
[
	'label' => 'Выйти (' . Yii::$app->user->displayName . ')', 
	'url' => ['/user/logout'],
	'linkOptions' => ['data-method' => 'post']
],
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.14
| PHP version      | 7.0
| Operating system | Debian

**Comment by samdark** [comment]
How exactly it doesn't work?

**Comment by mydesign** [comment]
don't add attributes on link, example, "data-method"

`<a href="#">link</a>`

must be

`<a href="#" data-method="post">link</a>`

**Comment by samdark** [comment]
Please check https://github.com/yiisoft/yii2/blob/master/framework/widgets/Menu.php. There's no `linkOptions`.
