### ISSUE TITLE
It seems that @app/config/main.php can not require a file which filename with upper word ?

### ISSUE THREAD

**Issue by haoliangxxx** [yiisoft/yii2-app-advanced#35]
i wanna split 'assetManager setting' part out to `@app/config/assetManager.php`.
but it error and everything ouput till i changed it's name from `assetManager.php` to `asset-manager.php`.
Is it for design purpose ?

**Comment by cebe** [comment]
sounds weird, please show the code you use to include the file.

**Comment by haoliangxxx** [comment]
dir:
```
- @app/config
| - main.php
| - assetManager.php
```

main.php
```
require( __DIR__ . 'assetManager.php');
```

I have tried that in a blank advanced-template, failed;
and a blank basic-template, successed in `web.php`;

**Comment by klimov-paul** [comment]
`require( __DIR__ . 'assetManager.php');` can not work anyhow as `__DIR__` does not contain traiing directory separator.
It should be:
```php
require( __DIR__ . DIRECTORY_SEPARATOR . 'assetManager.php');
```
or:
```php
require( __DIR__ . '/assetManager.php');
```

**Comment by haoliangxxx** [comment]
yes, i forget it, the `/`. but only in the post, not in my code.

**Comment by haoliangxxx** [comment]
Sorry for typo in the post, I did not forget the `/` in my code.
I tried require `assetManager.php` again, It works, somehow.

Sorry for the stupid issue, and thanks for your kind.
