### ISSUE TITLE
布局文件的js文件与视图文件的js顺序

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2-app-advanced#350]
### What steps will reproduce the problem?
我在布局文件(main.php)里面用 $view->registerjsFile(xxxxx) 加载了一个js文件, 并且指定为：POS::END
然后在某个视图文件里面也用$view->registerjsFile(xxxxx)  加载了一个js文件，并且指定为：POS::END

但是在视图文件里面加载的这个js文件，一直是在main里面的那个js文件之前，
请问，如果我想让视图文件里面 registerjsFile的js文件    怎么放在main里面的js之后？

### What's expected?
如何能让在视图文件里面的js文件 放在 布局文件里面的js之后？
### What do you get instead?
如何能让在视图文件里面的js文件 放在 布局文件里面的js之后？

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15
| PHP version      | 7.2.3 64bit  no safe thread version  
| Operating system |  win10 64bit

**Comment by samdark** [comment]
With Yii you can not. Not sure why it matters though.
