### ISSUE TITLE
upgrade existing apps template

### ISSUE THREAD

**Issue by nrob81** [yiisoft/yii2-app-advanced#351]
Hello,

Is there a way to upgrade my existing applications app template yii2-app-advanced v 2.0.8 to recent version without breaking anyrhing?

Thanks!

**Comment by samdark** [comment]
There's no way to upgrade overall. Once template it used, it's all yours.

**Comment by rob006** [comment]
@nrob81 You could try apply a patch: https://github.com/yiisoft/yii2-app-advanced/compare/2.0.8...2.0.14.patch but you will probably get a lot of conflicts and there is no guarantee that everything will work.
