### ISSUE TITLE
How about merge main config in separated file?

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-app-advanced#362]
Like #361 https://github.com/yiisoft/yii2-app-advanced/pull/361/files

for main configs and main params.

i.e. for backend
`backend/web/index.php`
```php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/../../common/config/bootstrap.php';
require __DIR__ . '/../config/bootstrap.php';

$config = require __DIR__ . '/../config/main-merge.php';

(new yii\web\Application($config))->run();
```
`backend/config/main.php`
```php
return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the backend
            'name' => 'advanced-backend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        /*
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        */
    ],
    'params' => [],
];
```

`backend/config/main-merge.php`
```php
<?php
return yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/../../common/config/params.php',
    require __DIR__ . '/../../common/config/params-local.php',
    require __DIR__ . '/../config/params.php',
    require __DIR__ . '/../config/params-local.php'
    require __DIR__ . '/../../common/config/main.php',
    require __DIR__ . '/../../common/config/main-local.php',
    require __DIR__ . '/../config/main.php',
    require __DIR__ . '/../config/main-local.php',
);
```

@samdark your opinion please?

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |@dev
| PHP version      |7.2.4
| Operating system |alpine

**Comment by samdark** [comment]
Why?

**Comment by bscheshirwork** [comment]
Like a https://github.com/yiisoft/yii2-app-advanced/commit/601241c2a9e874b26a6eacc40a80d8ec455f7145 

"Made config merging more explicit"

**Comment by bscheshirwork** [comment]
let's discuss!

**Comment by Coksnuss** [comment]
In case this should gain any interest, I vote for a different naming schema:

Rename `backend/config/main.php` to `backend/config/main-dist.php`
Rename `backend/config/main-merge.php` to `backend/config/main.php`

That said, I would usually vote in favor of this proposal as I prefer explicitness over implicitness. However, in this particular case, I believe that the pattern of merging multiple files files with a common prefix is well known to developers. It is also common practice that the config files are read from an "external" script which then decides on how to merge these files/settings (e.g. in [dotenv](https://github.com/motdotla/dotenv) (`.env`, `.env.local`, ...)). Therefore, I would rather prefer less files in the config directory and refer to the semi-explicit index.php to see how files are merged.

**Comment by samdark** [comment]
I don't think we'll do anything like that in Yii 2.0. In Yii 3.0 there are both merging (via separate composer plugin so it works well out of the box) and environment variables support.
