### ISSUE TITLE
Changes in codeception configs

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-app-advanced#363]
### What steps will reproduce the problem?

see
https://github.com/Codeception/Codeception/pull/4961

https://github.com/Codeception/Codeception/commit/bc8433e3da75bc28c47df6f3afc22b9d4f65c0b4#diff-44ec756825174849c255c1ff28011dbaR17

* [Yii2] **Breaking** `$settings['configFile']` now supports absolute paths. In you have defined relative path to config in absolute manner

Old config can't work? I have error in Travis CI... https://travis-ci.org/yiisoft/yii2-app-advanced/jobs/384708278

### What's expected?

I have no idea how to inject absolute path into yml w/o same environment, like docker container. How to determinate it?
Use env like https://github.com/Codeception/Codeception/issues/4868#issuecomment-390602400 ?

@SilverFire you have configs for yii2-app-basic yii2-app-advanced templates now?

### What do you get instead?
https://github.com/yiisoft/yii2-app-advanced/blob/0e4bc27bc25b8266951d2da5a7c3e87cc6f1a2a9/backend/codeception.yml#L15
https://github.com/yiisoft/yii2-app-advanced/blob/0e4bc27bc25b8266951d2da5a7c3e87cc6f1a2a9/frontend/codeception.yml#L15
https://github.com/yiisoft/yii2-app-advanced/blob/0e4bc27bc25b8266951d2da5a7c3e87cc6f1a2a9/frontend/codeception.yml#L15

**Comment by SilverFire** [comment]
Ehh, I think templates should continue work as before. Will try to check this issue this evening

**Comment by bscheshirwork** [comment]
Thanks!
I try to run within applied changes (absolute path is work) but i have another error... 

Undefined index: afterOpen

**Comment by ratVien** [comment]
In my case this happens when codeception try to handle db exception in Event.php
`// wildcard event names
        $removed = false;
        foreach (self::$_eventWildcards[$name][$class] as $i => $event) {
            if ($event[0] === $handler) {
                unset(self::$_eventWildcards[$name][$class][$i]);
                $removed = true;
            }
        }`
There is empty array in $_eventWildcards not afterOpen
And there is no check for that/ I am not sure it is Yii bug or codeception...
