### ISSUE TITLE
Yii2 changing session name for dividing frontend & backend user login not working

### ISSUE THREAD

**Issue by Michel5588BB** [yiisoft/yii2-app-advanced#364]
Actually, I am trying to change the session "PHPSESSID" to "PHPFRONTSESSID" and "PHPBACKSESSID" respectively for dividing login for users frontend and backend. I have hosted it in GODADDY shared hosting and it was working fine before but not working now. It is not changing the session name it is using same name "PHPSESSID" for frontend and backend.

frontend/config/main.php

```
'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
             'identityCookie' => [
                'name' => '_frontendUser', // unique for frontend
            ]
        ],
         'session' => [
            'name' => 'PHPFRONTSESSID',
            'savePath' => __DIR__ . '/../runtime', // a temporary folder on frontend

        ],
```

**Comment by samdark** [comment]
No info provided. Closing.
