### ISSUE TITLE
PHP version and deployment issues

### ISSUE THREAD

**Issue by dragonabv** [yiisoft/yii2-app-advanced#365]
### What steps will reproduce the problem?
I am trying to deploy my yii2 app on heroku using below article>
https://medium.com/@waqqas/yii-2-automated-deployment-on-heroku-8e4486312c2
This issue was also happening with my local system with PHP7.2
I was also getting (ignore errors) while importing database in phpmyadmin (direct)

### What's expected?
The app is working fine when running with Xampp on PHP5.6 Version
No ignore errors in phpmyadmin (xampp)

### What do you get instead?
```remote:        PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /tmp/build_e6f238015e2bf07043d0b9b4753088e9/vendor/yiisoft/yii2/base/Object.php on line 77
remote:        PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /tmp/build_e6f238015e2bf07043d0b9b4753088e9/vendor/yiisoft/yii2/base/Object.php on line 77
remote:        Script sh post-install-cmd.sh handling the post-install-cmd event returned with error code 255
remote:  !     Push rejected, failed to compile PHP app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to hrm-cv-dev.
remote: 
To https://git.heroku.com/hrm-cv-dev.git
 ! [remote rejected] code_study -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/hrm-cv-dev.git'```

### Additional info

| Yii vesion    : YII2   |
| PHP version : PHP7.2.5     |
| Operating system Linux Mint |

**Comment by dmirogin** [comment]
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved

https://github.com/yiisoft/yii2/issues/14823
