### ISSUE TITLE
Use utf8mb4 as default character set in for MySQL driver (in favor of plain utf8)

### ISSUE THREAD

**Issue by Coksnuss** [yiisoft/yii2-app-advanced#367]
I would like to suggest changing the default character set (and collate) for MySQL tables to `utf8mb4` in favor of plain `utf8` in [m130524_201442_init.php](https://github.com/yiisoft/yii2-app-advanced/blob/97e06d0cd7b6c269db5e9b23dfe00a5f3067eb32/console/migrations/m130524_201442_init.php#L12).

Rationale:
Unicode characters with a size of 4 Bytes became more popular recently. For example, alot of emojis (see [here](https://apps.timwhitlock.info/emoji/tables/unicode)) are required to be stored with 4 Bytes. Also, some users in Telegram (preferably those from India) use multibyte characters in their username which causes an error when trying to store their name in a MySQL table with an `utf8` character set.

The only disadvantage I can think of, is that legacy versions of MySQL do not support this character set. Supposedly, it was introduced in version 5.5.3. Some operating systems might not provide that version in their package repositories (e.g. CentOS 6.x which was released in 2011 and is supported until late 2020).

Suggested patch:
```patch
index 6b649f4..e680fe0 100644
--- a/api/console/migrations/m130524_201442_init.php
+++ b/api/console/migrations/m130524_201442_init.php
@@ -9,7 +9,7 @@ class m130524_201442_init extends Migration
         $tableOptions = null;
         if ($this->db->driverName === 'mysql') {
             // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
-            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
+            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
         }
 
         $this->createTable('{{%user}}', [
```

**Comment by samdark** [comment]
There is another disadvantage. Both max chars in a column and max chars indexed are less than with mb3: https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-conversion.html So you have to specify these all the time.

**Comment by samdark** [comment]
Won't be done in Yii 2.0.x for sure but could be considered for 3.0.

**Comment by Coksnuss** [comment]
> There is another disadvantage. Both max chars in a column and max chars indexed are less than with mb3.

I dont see a problem here as this also only affects older MySQL versions (until 5.7.9).

Developers must already take care of 3-Byte unicode characters when storing data in the database. And since 4-Byte characters become more common, developers should consider their occurrence "normal" instead of as an exception. New versions of MySQL handle them transparently.

From https://dev.mysql.com/doc/refman/8.0/en/char.html :
> InnoDB encodes fixed-length fields greater than or equal to 768 bytes in length as variable-length fields, which can be stored off-page. For example, a CHAR(255) column can exceed 768 bytes if the maximum byte length of the character set is greater than 3, as it is with utf8mb4.

Regarding the index: Same thing: It should only affect MySQL servers up to version 5.7.9. After that, MySQL uses the default row format `DYNAMIC` (see [here](https://dev.mysql.com/doc/refman/5.6/en/glossary.html#glos_dynamic_row_format)) which has an index prefix lengh of 3072 bytes (which is 4-times the size of he index prefix length of 767 used before and thus compensate for the 4-Byte character set).

**Comment by Thoulah** [comment]
5.7.9 and up is not (yet) default for some linux distros. Pushing utf8mb4 at this point in time is gonna cause a lot of drama. I tried using this on my own website (version 5.5.60-0+deb7u1) and it does cause trouble if I don't manually adjust things.
In short: I don't think it is a good idea yet to make this a default.

**Comment by Coksnuss** [comment]
> 5.7.9 and up is not (yet) default for some linux distros.

Yeah, those whose support ends in 2019 or 2020 might still ship with MySQL <= 5.7. 

> I tried using this on my own website (version 5.5.60-0+deb7u1) and it does cause trouble if I don't manually adjust things.

Legitimate objection. Mind to explain what kind of things are causing trouble without manual adjustment? I am just curious as I've never tried to use utf8mb4 with MySQL 5.5.

**Comment by Thoulah** [comment]
If I remember correctly, applying https://github.com/2amigos/yii2-usuario/blob/master/src/User/Migration/m000000_000001_create_user_table.php will fail.
I know and understand that 255 bytes for username or email is not necessary, but I just show a random file in the wild, actively used by people, that will cause issues on 5.5 with utf8mb4.

**Comment by Coksnuss** [comment]
Thanks! In that case, I agree that my proposal is unsuited to be introduced at this point in time.

How about evaluating `DbConnection::getServerVersion()` for a conditional determination of table options?

**Comment by samdark** [comment]
Yes, migrations will fail often because `string(255)`.

**Comment by Thoulah** [comment]
> How about evaluating `DbConnection::getServerVersion()` for a conditional determination of table options?

What would be the performance impact on such a condition?
Is it possible to switch charset to utfmb4 if conditions are right, or does the connection need to made from scratch?

**Comment by samdark** [comment]
DbConnection::getServerVersion() sounds OK.

**Comment by samdark** [comment]
But it's not application issue so closing this one.
