### ISSUE TITLE
The log is too large to report a fatal error

### ISSUE THREAD

**Issue by makcent** [yiisoft/yii2-app-advanced#369]
### What steps will reproduce the problem?
Open the permanent process and capture third party data
### What's expected?
Log logs one by one, do not write files after merging.
### What do you get instead?
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194312 bytes) in /usr/local/nginx/html/maicoo/vendor/yiisoft/yii2-debug/LogTarget.php on line 123

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.6
| PHP version             |7.1
| Operating system        |centos

**Comment by makcent** [comment]
@samdark 
```
public function actionCurl()
    {
        $redis = Yii::$app->redis;
        for ($i=1; $i<=5000; $i++) {
             $result = HttpHelp::curl('https://xxxxx/questions?page='.$i);

            if (!$result['s']) {
              preg_match_all('/<div class="summary">.+?<h2 class="title"><a href="(.+?)">(.+?)<\/a><\/h2>(.+?)<\/div>/s', $result['d'], $match);
               foreach ($match[0] as $key => $value) {
                    preg_match_all('/<a class="tag" .+?>(.+?)<\/a>/s', $match[3][$key], $tags);
                    $queue = array(
                        'title' => $match[2][$key],
                        'path'  => "https://segmentfault.com".$match[1][$key],
                        'tags' => preg_replace("/(\s|\&nbsp\;|　|\xc2\xa0)/","", strip_tags(implode(',', $tags[1]))),
                    );
                    $redis->rpush('problem_list', json_encode($queue));
               }
              
            }
        }
    }
```

 <h2>Allowed memory size of 104857600 bytes exhausted (tried to allocate 4194312 bytes)</h2>
<div class="element">
            <span class="item-number">1.</span>
            <span class="text">in /usr/local/nginx/html/maicoo/vendor/yiisoft/yii2-debug/LogTarget.php</span>
            <span class="at">
                at line                <span class="line">123</span>
            </span>
                    </div>

**Comment by samdark** [comment]
Aha. I've got it. You can increase memory reserve for that via configuring `errorHandler` component: https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L39
