### ISSUE TITLE
how to install an extension without composer

### ISSUE THREAD

**Issue by JorgeLiu** [yiisoft/yii2-app-advanced#370]
### What steps will reproduce the problem?
how to install an extension without composer
i try to add in vendor\composer\autoload_psr4.php like
`'Qcloud\\Sms\\'=>array($vendorDir . '/Qcloud/Sms/src'),`
it does't work ,but yii2.0.13 can work properly

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15
| PHP version      | 7.2
| Operating system |win10+iis

**Comment by samdark** [comment]
Better configure composer. Installing manually is a huge pain.
