### ISSUE TITLE
Yii2 app advanced and Yii 2.0.15

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2-app-advanced#371]
It's ok Yii 2.0.14 for create-project?

### What steps will reproduce the problem?
Install latest Yii2.
```
composer create-project --prefer-dist yiisoft/yii2-app-advanced .
```
### What's expected?
```
Installing yiisoft/yii2-app-advanced (2.0.15.1)
  - Installing yiisoft/yii2-app-advanced (2.0.15.1): Downloading (100%)    
```

### What do you get instead?
```
Installing yiisoft/yii2-app-advanced (2.0.14)
  - Installing yiisoft/yii2-app-advanced (2.0.14): Downloading (100%)    
```

### Additional info
| Q                | A
| ---------------- | ---
| Yii vesion       | Latest
| PHP version      | 7.1
| Operating system | Ubuntu 17.10

**Comment by samdark** [comment]
Yes. It's fine.
