### ISSUE TITLE
[DOCs] No quick link to edit on github, and wrong link to repository in footer

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii2-app-advanced#374]
In the Getting Started guide, e.g. https://www.yiiframework.com/doc/guide/2.0/en/start-workflow, at the bottom of every page, there is a link that says "Edit on github" which is a shortcut to fork and edit the docs.

I'd expect to find the same here: 
https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/start-installation

but it's not there.

Additionally, the link "Report a bug" in the footer, wrongly links to the yiisoft/yii2 repository instead of this one.

**Comment by teo1978** [comment]
And I'm afraid I reported this on the wrong repo, partially because of the issue itself.

**Comment by rob006** [comment]
This should be reported to https://github.com/yiisoft-contrib/yiiframework.com

**Comment by teo1978** [comment]
> This should be reported to https://github.com/yiisoft-contrib/yiiframework.com

Wow, that was hard to find.

**Comment by rob006** [comment]
Yeah, there should be some link to this repo on https://www.yiiframework.com/report-issue.

**Comment by cebe** [comment]
Added a website section on https://www.yiiframework.com/report-issue
