### ISSUE TITLE
Strange login/signup behavior when email is not activated

### ISSUE THREAD

**Issue by deanpress** [yiisoft/yii2-app-advanced#376]
### What steps will reproduce the problem?

1. Turn on email activation requirement in config
2. Create an account on the front-end
3. Don't activate email
4. Try logging in
5. Try creating an account

### What's expected?
When you try to log in to a non-activated account, you should receive a warning that the email is not activated (possibly with the opportunity to re-send activation link).
When you try to register, the same email should appear.

### What do you get instead?
Currently if an email address is not activated, then:
1. User cannot login: Message: "This e-mail address is not found".
2. User cannot register new account. Message: "This e-mail address is already in use".

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | `app-advanced` latest (based on `trntv/yii2-starter-kit`)
| PHP version      | 7.2

**Comment by samdark** [comment]
There's no such functionality in this template. Please report to trntv/yii2-starter-kit
