### ISSUE TITLE
The build of yii2-app-advanced is failing

### ISSUE THREAD

**Issue by ddinchev** [yiisoft/yii2-app-advanced#378]
The build of this project is failing with Codeception errors. I'm experiencing problems with codeception versions 2.4.2, 2.4.3, 2.4.4 on my functional tests as well - could you fix the project build with the latest codeception version so it stays as a template of how tests should be configured to work, at least for those most basic cases.

**Comment by Faryshta** [comment]
phpunit 7.2 included some BC breaks which the codeception mantainers dont know how to resolve yet. https://github.com/Codeception/Codeception/issues/5092

I advice to modify your `composer.json` to include the following

```json
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.4.0",
        "phpunit/phpunit": "~7.1.0",
        "codeception/verify": "~1.0.0"
    }
```

@samdark shall I make a PR about this? I dont know how long will codeception take to fix this

**Comment by samdark** [comment]
Yes, I think so.

**Comment by ddinchev** [comment]
Codeception build has been failing for a while now, even before the `2.4.4` BC release. Now there is `2.4.5` - can you make the `yii2-app-advanced` build with that version, not `2.4.0` that is months old and misses several important fixes?

**Comment by Faryshta** [comment]
@ddinchev send pr
