### ISSUE TITLE
No explanation given about "test-local.php" files in dev environment

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii2-app-advanced#383]
This page:

https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/structure-environments

explains what environments are, the structure of the `dev` and `prod` environments, and how the config files `main.php`, `main-local.php`, `params.php`, `params-local.php` from several directories are loaded, in which order, etc.

However, it says nothing about what the files `test.php and `test-local.php` are, when they are loaded, and how they interact with other configuration files. I have no idea what they are for, I don't think it's obvious by looking at them, and I don't find anything in the docs. If there's something in the docs elsewhere, I find it hard to find and I'd expect to find a link here at the abovementioned page.

**Comment by sheillendra** [comment]
An explanation of this can be found here: https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-testing.md
