### ISSUE TITLE
The backend doesn't look very much like a backend

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii2-app-advanced#385]
I installed the advanced project template and I started trying out the front-end and the back-end.

Out of the box:
- in the front-end, I can navigate without being logged in
- I can sign up and log in and I see whether I am logged in or not
- In the back-end, I can't do anything until I log in

So far so good. This is what I expected.

However, what I did NOT expect is that:
- on the backend, I can log in with any user
- after I log in into the backend, it looks a lot like the front-end

I would expect there to be some mechanism, out of the box (and of course documented in the guide), for defining "admin" users allowed to log into the backend. An easy one could be an application parameter with an array of usernames, and only these would be allowed to log in into the backend. This is simple enough that the developer can either use it as is, expand on it, or replace it altogether with whatever fit their needs.

Secondly, once logged in at the backend, I would expect it to look more like a backend. It is almost identical to the front-end, with the same "welcome" and "lorem ipsum" stuff, except it lacks the menu items such as "Contact us" and "about". That is confusing.

Something that I think would be both a good example of a backend and also a starting point for real-life applications, would be to have CRUD management of Users.

**Comment by samdark** [comment]
These are good concerns but we've decided to drop advanced app template in the next major Yii version.

**Comment by teo1978** [comment]
Oh shoot, once again I'm wasting my time learning something that is already being abandoned! (just like it was with yii1.1, but at the time yii2 wasn't ready to be used either)

I hope this is in favour of one single unified not-so-basic app template that will inherit many of the features that are currently in the advanced template? (I disliked the double template from the beginning, especially because of the difficulty of following the getting started guide with the advanced app template)

**Comment by teo1978** [comment]
Please tell me that Yii3 will at least be fully backward compatible

**Comment by samdark** [comment]
Nope, it won't be.

**Comment by teo1978** [comment]
WTF Ok, I'm done with Yii then. Not going to waste effort learning something that is already obsolete, when the replacement isn't ready either, and with no hope of being able to migrate later. 
Again.

**Comment by rob006** [comment]
@teo1978 Yii 2.0 was released ~4 years ago. If releasing new major release with BC breaks every 4-5 years is too frequent for you, you should end up with programming. Or at least go to some ancient and/or dead technology, which still needs some people to support old but working existing solutions (COBOL may be a good shot :D).

**Comment by teo1978** [comment]
Wait a moment, maybe this was just a misunderstanding.

>> **fully** backward compatible
>
> Nope, it won't be.

I should have said **_mostly_** backwards-compatible, as in "you can replace 2.x with 3.0 on a given app, some things may break and need fixing but it's doable". Kind of like upgrading from PHP 4.x to 5.x or from PHP 5.x to 7.x.

Is that the case, or is it just like from Yii 1.x to Yii2?

**Comment by samdark** [comment]
Yes. Mostly — yes. There will be changes and major breaks but overall it's not another framework as 2.0 was to 1.1.

**Comment by teo1978** [comment]
Phew!

**Comment by teo1978** [comment]
Anyway, getting back to the issue at hand, if you are dropping the advanced app template completely, I wish there would be some hints in the docs about the direction you are taking, and recomendations. I guess some features are going to be incorporated into the basic app template, others are going to be dropped completely because you have come to the conclusion they were bad ideas. Would be good to know which are which.

**Comment by samdark** [comment]
Sure. Docs will be there.

**Comment by teo1978** [comment]
Just to clarify, I would expect that kind of information to be in the _current_ docs.

**Comment by samdark** [comment]
Well, we can't handle it all perfectly. Doing whatever we can.
