### ISSUE TITLE
I can't install yii2 advanced on my PC, the error 502 bad gateway, I am using Windows 10 64x vagrant and virtual box the newest version, but I see the error with nginx

### ISSUE THREAD

**Issue by Scarpion0990** [yiisoft/yii2-app-advanced#389]
I can't install yii2 advanced on my PC, the error 502 bad gateway, I am using Windows 10 64x vagrant and virtual box the newest version, but I see the error with nginx

**Comment by Scarpion0990** [comment]
I have done all instructions for windows and why I can't run the my yii2 advanced on my PC? is there any person with this problem?

**Comment by tomlutzenberger** [comment]
5xx codes are server errors, which means that something in your web server config is wrong or broken. This might help you: https://www.lifewire.com/502-bad-gateway-error-explained-2622939

Otherwise search google for "502 bad gateway apache" (or nginx)

**Comment by Scarpion0990** [comment]
If I see welcome page of nginx instead of my site?

**Comment by tomlutzenberger** [comment]
You either got the wrong URL (usually http://localhost/YOUR_PROJECT) or you need to configure your server blocks: https://www.nginx.com/resources/wiki/start/topics/examples/server_blocks/

**Comment by Scarpion0990** [comment]
I installed yii advanced with vagrant and virtual box I have done instructions which are given here, unfortunately it doesn't work, when I write vagrant up in shell there is no problem but when you write in browser yii2advanced.test, I see welcome page nginx, I am using windows, where I did wrong thing?

**Comment by tomlutzenberger** [comment]
Hard to tell. To me it looks like a web server configuration issue. I recommend asking on [StackOverflow](https://stackoverflow.com)
