### ISSUE TITLE
advanced/console/web" does not exist

### ISSUE THREAD

**Issue by smarttang** [yiisoft/yii2-app-advanced#393]
sorry, why ?
![image](https://user-images.githubusercontent.com/4961402/45266172-51299900-b489-11e8-9857-3c24ac1f2927.png)

![image](https://user-images.githubusercontent.com/4961402/45266180-6bfc0d80-b489-11e8-8d2a-1924246b33f7.png)

**Comment by samdark** [comment]
In advanced app there are two webroots. You have to specify explicitly which one you want to run.

**Comment by smarttang** [comment]
how to pecify explicitly which one you want to run?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/ServeController.php#L37

**Comment by samdark** [comment]
It's part of the framework, correct.

**Comment by rob006** [comment]
You can fix this in config using `controllerMap`:

```php
'controllerMap' => [
	'serve' => [
		'class' => ServeController::class,
		'docroot' => '@frontend/web`,
	],
],
```

or pass this as option to command:

    ./yii serve --docroot="@frontend/web"


Related https://github.com/yiisoft/yii2/issues/14656

**Comment by smarttang** [comment]
OK! thank @all !

**Comment by smarttang** [comment]
> You can fix this in config using `controllerMap`:
> 
> ```
> 'controllerMap' => [
> 	'serve' => [
> 		'class' => ServeController::class,
> 		'docroot' => '@frontend/web`,
> 	],
> ],
> ```
> 
> or pass this as option to command:
> 
> ```
> ./yii serve --docroot="@frontend/web"
> ```
> Related [yiisoft/yii2#14656](https://github.com/yiisoft/yii2/issues/14656)

![image](https://user-images.githubusercontent.com/4961402/45497003-3e74d400-b7a9-11e8-934a-fb908361b8d8.png)

**Comment by rob006** [comment]
This is `yii\console\controllers\ServeController` - you should either use FQN here or import this class using `use` statement. 

You also don't need to use both solutions - you can skip config adjustment if you're using `./yii serve --docroot="@frontend/web"` command.

**Comment by smarttang** [comment]
> o don't need to use bo

OK!I try again! thx..

**Comment by hei0323** [comment]
谢谢！有帮助

**Comment by buttflattery** [comment]
@rob006 what if i am using the `public_html` directory on the root of the project as the webroot for all of my apps in an `advanced-app` ? would the `./yii serve --docroot="@frontend/web"` throw a 404 for css and js assets ? as it would search in the `frontend/web` and the actual assets are in the `public_html/` for the `frontend`
