### ISSUE TITLE
[yii\base\InvalidConfigException] Failed to instantiate component or class "db".

### ISSUE THREAD

**Issue by dharma017** [yiisoft/yii2-app-advanced#404]
Hi I am unable to connect MongoDB in Unit Testing to work with fixture data. For Unit Testing with codeception, same mongodb connection is working. Please help me to solve this issue.

### What steps will reproduce the problem?
To reproduce implement [Fixtures](http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html) feature in [Yii2 advanced template](https://github.com/yiisoft/yii2-app-advanced) with [Codeception](http://codeception.com/for/yii) Unit Testing.

Code file attached as follows.
[fixture.log](https://github.com/yiisoft/yii2/files/1614042/fixture.log)
[UserFixture.php.txt](https://github.com/yiisoft/yii2/files/1614043/UserFixture.php.txt)
[LoginFormTest.php.txt](https://github.com/yiisoft/yii2/files/1614044/LoginFormTest.php.txt)

### What is the expected result?
Fixture to work with MongoDb connection in Unit Testing and yii console command.

### What do you get instead?
```
root@1a3d00a6fe60:/var/www/rest.testsite.com# ./vendor/bin/codecept run unit -c common
Codeception PHP Testing Framework v2.3.7
Powered by PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Common\tests.unit Tests (1) ---------------------------------------------------------------------------------------------------------------------------------------------------------
E LoginFormTest: Fixture user (0.11s)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.42 seconds, Memory: 12.00MB

There was 1 error:

---------
1) LoginFormTest: Fixture user
 Test  tests/unit/models/LoginFormTest.php:testFixtureUser

  [yii\base\InvalidConfigException] Failed to instantiate component or class "db".

#1  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Instance.php:139
#2  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/DbFixture.php:42
#3  /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/BaseObject.php:108
#4  yii\base\BaseObject->__construct
#5  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php:375
#6  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php:156
#7  /var/www/rest.testsite.com/vendor/yiisoft/yii2/BaseYii.php:349
#8  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:208
#9  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:145
#10 /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:112

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1
| Operating system |Ubuntu 16.04.2 LTS

**Comment by XzAeRo** [comment]
Is there any clue to what may be happening? If no one is working on this issue I will try to spend some time to fix it.

**Comment by machour** [comment]
@XzAeRo please go ahead.

**Comment by alfredleo** [comment]
@XzAeRo any clues yet?

**Comment by XzAeRo** [comment]
@alfredleo I kind of have a solution, but for some reason it's kind of hard to understand _why_ it doesn't work in the first place.

I hope to send a PR this week, since I kind of need this fixed for a related project.

**Comment by XzAeRo** [comment]
Okay, so I've been working on this issue literally 2 days straight and I can't fix it.

What I've gathered so far:

- This problem triggers while testing using fixtures.
- It breaks from codeception 2.4.1+, so codeception 2.4.1 is the culprit in introducing this "bug".
- Related and relevant issues: https://github.com/Codeception/Codeception/issues/5120 https://github.com/Codeception/Codeception/issues/5064 https://github.com/yiisoft/yii2/issues/16877
- Rearranging modules order in the codeception config files doesn't seem to improve or offer any relevant improvement.
- In the codeception 2.4.1 changelogs it says "`[Yii2] Request flow and database transactions refactored`" as one of the key changes in that release, so I assume that something related to that refactor changed something internally on codeception that breaks the Yii2 compatibility.

I'm going to resume work on this after the weekend but so far, it doesn't directly relates to this project in specific, maybe more to the `yii2` or `codeception` projects.

**Comment by machour** [comment]
@XzAeRo have you tried to `git bisect` inside vendor/codeception/codeception to see exactly what commit broke it?

**Comment by XzAeRo** [comment]
@machour I wanted to start doing that before I stopped working today, but I figured it would be better if I start fresh next week...

**Comment by XzAeRo** [comment]
I finally found the culprit:

- The bug was introduced in this commit: https://github.com/Codeception/Codeception/commit/b574ef21a011621dd57b6446a770255566204853#diff-938f756d763fc21aace78bb43ea26870R362
- The function [`resetApplication()`](https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Lib/Connector/Yii2.php#L99-L111), is the one that resets the configuration of the application `Yii::$app`, therefore the "no db" error, there's no config.
- This function is called in the [Yii2 module of Codeception in the `_after` function](https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Module/Yii2.php#L336-L365). I'm not sure yet where the chain of calls starts, but is triggered while using Fixtures (or ActiveFixtures).

Commenting the `resetApplication()` call in the `_after()` function fixes the problem.

I'm not sure if this issue needs to be kept here, since this looks like an issue with Codeception and the Yii2 module/connector.

**Comment by pvassiliou** [comment]
The change proposed by @VasylDmytruk worked for me. Many thanks :+1:
