### ISSUE TITLE
,when use array_merge the configurations file, the components.db.attributes key will be change and not expected

### ISSUE THREAD

**Issue by CreatNameHard** [yiisoft/yii2-app-advanced#406]
### What steps will reproduce the problem?
the components.db.attributes key is number,when use array_merge the config file, the components.db.attributes key will be change and not expected
```
<?php
return yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/main.php',
    require __DIR__ . '/main-local.php',
    require __DIR__ . '/test.php',
    [
        'id' => 'app-tests',
        'components' => [
            'db' => [
                'class' => 'yii\db\Connection',
                'dsn' => 'mysql:host=120.77.158.58;dbname=test_xiepinhui',
                'username' => 'xph_test',
                'password' => 'xph.qwe',
                'charset' => 'utf8mb4',
                'tablePrefix' => 'shopxph_',
                'attributes' => [
                    PDO::ATTR_ORACLE_NULLS => PDO::NULL_TO_STRING,
                    PDO::ATTR_PERSISTENT => false,
                ]

            ]
        ],

    ]
```
### What's expected?

I want to be able to overwrite configuration files when they are merged, just like normal configurations for components.db.attributes.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11.6
| PHP version      | 5.6
| Operating system | centos 6.5

**Comment by MysteryDragon** [comment]
Well, if I understand this issue correctly on my sleepy head, it's standard PHP behavior after all: `array_merge()` will change integer array keys, yep. `ArrayHelper::merge()` is just wrapper with some adjustments.

PDO::ATTR_ORACLE_NULLS = 11
PDO::ATTR_PERSISTENT = 12

So it's all about your config merge strategy.
You have `+` operator too for arrays, it might help.

Just some random example:
`db-local.php` contains environment-specific configuration:
```
<?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=120.77.158.58;dbname=test_xiepinhui',
    'username' => 'xph_test',
    'password' => 'xph.qwe',
    'charset' => 'utf8mb4',
    'tablePrefix' => 'shopxph_',
    'attributes' => [
        PDO::ATTR_ORACLE_NULLS => PDO::NULL_TO_STRING,
        PDO::ATTR_PERSISTENT => false,
    ],
];
```

`db.php` contains common configuration.

Now in your place:
```
$db = require __DIR__ . '/db.php';
$dbLocal = require __DIR__ . '/db-local.php';

return yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/main.php',
    require __DIR__ . '/main-local.php',
    require __DIR__ . '/test.php',
    [
        'id' => 'app-tests',
        'components' => [
            'db' => $dbLocal + $db,
        ],
    ],
];
```

**Comment by CreatNameHard** [comment]
> Well, if I understand this issue correctly on my sleepy head, it's standard PHP behavior after all: `array_merge()` will change integer array keys, yep. `ArrayHelper::merge()` is just wrapper with some adjustments.
> 
> PDO::ATTR_ORACLE_NULLS = 11
> PDO::ATTR_PERSISTENT = 12
> 
> So it's all about your config merge strategy.
> You have `+` operator too for arrays, it might help.
> 
> Just some random example:
> `db-local.php` contains environment-specific configuration:
> 
> ```
> <?php
> 
> return [
>     'class' => 'yii\db\Connection',
>     'dsn' => 'mysql:host=120.77.158.58;dbname=test_xiepinhui',
>     'username' => 'xph_test',
>     'password' => 'xph.qwe',
>     'charset' => 'utf8mb4',
>     'tablePrefix' => 'shopxph_',
>     'attributes' => [
>         PDO::ATTR_ORACLE_NULLS => PDO::NULL_TO_STRING,
>         PDO::ATTR_PERSISTENT => false,
>     ],
> ];
> ```
> `db.php` contains common configuration.
> 
> Now in your place:
> 
> ```
> $db = require __DIR__ . '/db.php';
> $dbLocal = require __DIR__ . '/db-local.php';
> 
> return yii\helpers\ArrayHelper::merge(
>     require __DIR__ . '/main.php',
>     require __DIR__ . '/main-local.php',
>     require __DIR__ . '/test.php',
>     [
>         'id' => 'app-tests',
>         'components' => [
>             'db' => $dbLocal + $db,
>         ],
>     ],
> ];
> ```

**Thank you! This problem has been solved. You're too good.**
