### ISSUE TITLE
Error with web path in docker apache.

### ISSUE THREAD

**Issue by gugatxr** [yiisoft/yii2-app-advanced#409]
### What steps will reproduce the problem?

```
docker-compose run --rm backend composer install
docker-compose run --rm backend /app/init
docker-compose run --rm backend yii migrate
docker-compose up -d
``` 
### What's expected?

See the Yii Home when open http://localhost:21080/

### What do you get instead?

Forbidden page from apache

### Additional info

The apache config file is point to ` /app/web`
One solution is change the Dockerfile

```
FROM yiisoftware/yii2-php:7.2-apache

ENV APACHE_DOCUMENT_ROOT /var/www/html

RUN sed -ri -e 's!/app/web!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/app/web!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Create a symlink for apache (if `/var/www/html` is available)
RUN rm -rf /var/www/html && ln -s /app/backend/web/ /var/www/html || true
```

| Q                 | A
| ---------------- | ---
| Yii vesion     | 2.0.14
| PHP version| 7.2
| Operating system | ubuntu

**Comment by samdark** [comment]
@schmunk42 would you please look into it?

**Comment by creep3r** [comment]
I mentioned this here #347

Got that working by changing default mountpoint to /app/web (as in yii2-docker package)
[creep3r/yii2-app-advanced/commit/3b61b71c776baf982944ca6b1a13aae3c926eca2](https://github.com/creep3r/yii2-app-advanced/commit/ea0e53c95e9f1c8a42b95ca548dfb84254a90200)

**Comment by schmunk42** [comment]
Please have a look at the above PR.

I haven't tried it, but I don't understand how changing the mount-point would work.
In general the directory structure is not ideal for Docker images, we might do some more iterations on this.

**Comment by creep3r** [comment]
@schmunk42 I don't think replacing the (rm + ln) hack with sed is better solution. Since we rely on package yii2-docker, there is no need to overwrite apache conf until we want to implement more complex configuration, e.g. separate vhost config for backend & frontend.

**Comment by schmunk42** [comment]
We had several problems with `rm` and `ln` (eg. not even able to build on some systems), what do you dislike with `sed`?

As said the structure `frontend` + `backend` + `common` is not ideal anyway.

**Comment by creep3r** [comment]
@schmunk42 I don't like the procedure at all. There is no need to change path which was just set with building `FROM yiisoftware/yii2-php:7.2-apache`. Also you do think it is useful or necessary to run two apache services for some reason in "minimal docker setup" case?

@samdark  IMHO shouldn't be closed yet, can/should I open new PR to suggest different approach?

**Comment by samdark** [comment]
Sure.

**Comment by schmunk42** [comment]
> Also you do think it is useful or necessary to run two apache services for some reason in "minimal docker setup" case?

There's `frontend` and `backend` in the advanced template, personally I never use that; but running those in the same container complicates things much more, IMHO.

**Comment by gugatxr** [comment]
I use one container for both and works fine until now =D

**Comment by creep3r** [comment]
@gugatxr Yea, me too. I think duplicate Dockerfiles are ambigous. Routing between frontend/backend/... apps can be done with htaccess, just like Im used to.
