### ISSUE TITLE
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using

### ISSUE THREAD

**Issue by Buliwyfa** [yiisoft/yii2-app-advanced#425]
### What steps will reproduce the problem?
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application

### What's expected?
That all was installed with no errors

### What do you get instead?
A warning:
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      | 7.2.16
| Operating system | Windows 2019

**Comment by Buliwyfa** [comment]
The error/warning is related to the PHPUnit version on composer which is realted to PHP version used

	PHPUnit version	PHP Version		composer
	----------		       ---------------		-------------------------
	PHPUnit 8		PHP 7.2 / 7.3		"phpunit/phpunit": "^8"
	PHPUnit 7		PHP 7.1			"phpunit/phpunit": "^7"
	PHPUnit 6		PHP 7.0			"phpunit/phpunit": "^6"
	PHPUnit 5		PHP 5.6			"phpunit/phpunit": "^5"

Also, please note that PHP 7.1 is no longer actively supported. 
https://secure.php.net/supported-versions.php

**Comment by samdark** [comment]
That is expected since we need to support older PHP versions.

**Comment by clarenceli419** [comment]
I am using php7.3.6.
But same problem.
Can anyone tell me the reason?

**Comment by Salehin24** [comment]
solution ?...

**Comment by samdark** [comment]
If you don't need to support older versions, raise PHP requirement and PHPUnit version in composer.json.
