### ISSUE TITLE
setReplyTo for sendEmail

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-app-advanced#426]
### What steps will reproduce the problem?
gmail smtp got some problems with default settings 
https://github.com/yiisoft/yii2-app-advanced/blob/bde11637da2b4b01be6497ca9e7f75db03ff5f77/frontend/models/ContactForm.php#L51-L60

how about add `setReplyTo`?
```php
    public function sendEmail($email)
    {
        return Yii::$app->mailer->compose()
            ->setTo($email)
            ->setFrom([$this->email => $this->name])
            ->setReplyTo([$this->email => $this->name])
            ->setSubject($this->subject)
            ->setTextBody($this->body)
            ->send();
    }

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by machour** [comment]
What is the problem exactly? Using it without problems on my side.

**Comment by bscheshirwork** [comment]
I see message sender is a "ThisName <smtpuser@gmail.com>" instead of "ThisName <thisemail@gmail.com>"

**Comment by machour** [comment]
Why is your smtpuser different than thisemail? Can you show your configuration for the mail component?

**Comment by bscheshirwork** [comment]
this is correct workflow. 
smtp user is "norely@domain.com" - all email from applications
$this->email is field of feedback form. This is end-user email.

**Comment by bscheshirwork** [comment]
So. I can't reply to end-user email. I can't see it anyway

**Comment by rob006** [comment]
This:

```php
->setFrom([$this->email => $this->name])
->setReplyTo([$this->email => $this->name])
```

does not make much sense in most cases. It is relevant only when your SMTP server overrides "from" field to disallow spoof sender (like gmail). But then it is better to put real sender email in your "from" field:

```php
->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
->setReplyTo([$this->email => $this->name])
```

**Comment by machour** [comment]
Agreed, we wan't to use the smtp user as From most of the time, and not send emails on behalf of the form submitter.

**Comment by rob006** [comment]
> Agreed, we want to use the smtp user as From most of the time, and not send emails on behalf of the form submitter.

But right now emails are sent on behalf of the form submitter. This still should be fixed, just not in a way that `setReplyTo` duplicates `setFrom`, because it does not have much sense in most cases.
