### ISSUE TITLE
Opportunity to select target directory for the environment files

### ISSUE THREAD

**Issue by Ovsyanka** [yiisoft/yii2-app-advanced#427]
I am making my yii2 application to be able to be "[dockerized](https://www.docker.com/)" and I gonna separate **source code** of the application and all **other data**, including environment code and configs, static data, runtime data and etc. As I see, `init` script doesn't allow to put target environment files anywhere but in root project directory. And considering the principle described above the project root directory could be 'readonly'.

It would be nice to have the opportunity to select the target directory(es) for the environment files. What do you think about it?

**Comment by samdark** [comment]
Once the app is created, it's all yours. You can adjust it for your particular case.

**Comment by Ovsyanka** [comment]
I know this =) I asked you about this ability implemented in the app template.

As I see you don't think that it would be useful, so I will not make a PR.

**Comment by samdark** [comment]
Correct. That's not a bad thing but I'm not sure it will be applicable to every project created.
