### ISSUE TITLE
Кривые руки. Вопрос кому пальцы править.

### ISSUE THREAD

**Issue by YurchenkoAndrew** [yiisoft/yii2-app-advanced#428]
При последнем обновлении advanced шаблона, перестала работать регистрация из "коробки".
Вопрос кому стучать по пальцам для исправления.
Добавили подтверждение регистрации по почте, а доработать было видимо не судьба.
Основной плюс данного фреймворка, быстрота развертывания. Ее убили. Не хорошо ребят, отбираете положительное.

**Comment by samdark** [comment]
В последнем релизе не трогали ничего, связанного с регистрацией: https://github.com/yiisoft/yii2-app-advanced/compare/2.0.17...master

Что именно не работает?

**Comment by YurchenkoAndrew** [comment]
> В последнем релизе не трогали ничего, связанного с регистрацией: [2.0.17...master](https://github.com/yiisoft/yii2-app-advanced/compare/2.0.17...master)
> 
> Что именно не работает?

На момент написания поста, не работала регистрация из коробки. Так как, в обновлении добавлено подтверждение по e-mail. А в конфигах не прописан не встроенный "mailer", хотя его не сложно сразу бы прописать, для работы как мне кажется из коробки. 
Конечно это не сложно сделать и самому. Но вот из коробки уже приложение не хочет работать как раньше. Пока куда нибудь "напильником" не залезешь. Возможно, что то еще, я на данный момент не помню. Поправил регистрацию конечно у себя сам. Но думаю все же можно сразу это сделать при установки приложения из коробки. Там пару строчек кода внести в исходник.

**Comment by samdark** [comment]
> Так как, в обновлении добавлено подтверждение по e-mail.

Нет. Я дал ссылку на diff. Не было там оно добавлено. Там правки касаются исключительно формы для обратной связи.

> не хочет работать как раньше

На какой версии работало?

Как именно воспроизвести проблему?

>  Там пару строчек кода внести в исходник.

Pull request сделаете?

**Comment by YurchenkoAndrew** [comment]
> > Так как, в обновлении добавлено подтверждение по e-mail.
> 
> Нет. Я дал ссылку на diff. Не было там оно добавлено. Там правки касаются исключительно формы для обратной связи.
Честно я возможно не туда пишу. Я через композер скачал стандартом произвел установку.
> 
> > не хочет работать как раньше
> 
> На какой версии работало?
Устанавливал композером с оф документации. Сегодня та же проблема.
> 
> Как именно воспроизвести проблему?
Установить композером, не работает регистрация.
> 
> > Там пару строчек кода внести в исходник.
> 
> Pull request сделаете?
Не очень знаком с гитом. Строки:
В конфиг добавить в компоненты подключение "mailer" и транспорт файла на локалку:

        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
        ],
Все. Я почему и спросил, не ужели сразу это не возможно было добавить в исходник?

**Comment by samdark** [comment]
Вы делали `./init` после установки?

- https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/dev/common/config/main-local.php#L11
- https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/prod/common/config/main-local.php#L11

**Comment by YurchenkoAndrew** [comment]
> Вы делали `./init` после установки?
> 
> * https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/dev/common/config/main-local.php#L11
> * https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/prod/common/config/main-local.php#L11

Да, конечно. ) Это же все равно, что сесть на гошок не сняв штаны... ))

**Comment by samdark** [comment]
> то mailer не знает куда обращаться как я понял

Нет. Если нет этой строки, то мейлер будет реально мейлить, а не писать в файл для отладки. Чтобы мейлить, у вас должен быть настроен мейлер в операционной системе. Если это не так, мы тут ничем помочь не можем.
