### ISSUE TITLE
Будет ли когда нибудь в шаблоне advanced полноценная поддержка bootstrap 4?

### ISSUE THREAD

**Issue by YurchenkoAndrew** [yiisoft/yii2-app-advanced#430]
Привет ребят. Сегодня возникла необходимость воспользоваться решением Yii на шаблоне Advanced. И с большим огорчением при начале работ выяснилось, что шаблон слишком устарел по технологическому обеспечению. До сих пор в нем используется устаревшая версия Bootstrap.
Посмотрел решения подобного вопроса по переходу на текущую версию bootstrap 4, без костылей это не возможно на данный момент. Да и хранение устаревшего кода в репозитории Yii2 считаю худшей практикой.
Вопрос будет ли когда нибудь поддержка графического фреймворка в шаблоне на уровне современных реалий? Я имею в виду без танец с бубном и работой в дефолтных модулях идущих с фреймворком.

| Q                | A
| ---------------- | ---
| Yii vesion  2.0.19     |
| PHP version  7.3    |
| Operating system Win 10 |

**Comment by samdark** [comment]
Нет, не будет.
