### ISSUE TITLE
Swiftmailer wrong configuration

### ISSUE THREAD

**Issue by Elwizard84** [yiisoft/yii2-app-advanced#435]
### What steps will reproduce the problem?
Configuring Swiftmailer in common -> main-local.php like so:

```php
'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'mainserver.gp.local',
                'username' => 'it@gp.local',
                'password' => '******',
                'port' => '25',
                'encryption' => 'none',
            ],
            'useFileTransport' => false,
        ],
```

### What's expected?
To be able to send emails, and that Swiftmailer receives the correct configuration.

### What do you get instead?

```php
1. in \vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php at line 269
260261262263264265266267268269270271272273274275276277278            $options['socket']['bindto'] = $this->params['sourceIp'].':0';
        }
 
        if (isset($this->params['stream_context_options'])) {
            $options = array_merge($options, $this->params['stream_context_options']);
        }
        $streamContext = stream_context_create($options); echo "NANA" . $host . ':' . $this->params['port'];
        $this->stream = @stream_socket_client($host.':'.$this->params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
        if (false === $this->stream) {
            throw new Swift_TransportException(
                'Connection could not be established with host '.$this->params['host'].
                ' ['.$errstr.' #'.$errno.']'
                );
        }
        if (!empty($this->params['blocking'])) {
            stream_set_blocking($this->stream, 1);
        } else {
            stream_set_blocking($this->stream, 0);
        }
```

### Additional info
Debugging StreamBuffer.php and setting the mail server manually there gets things working.
manual value is this: "mainserver.gp.local:25"

Outputing the value of $host.':'.$this->params['port'] results in:
none://mainserver.gp.local:25

which does not work.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.022
| PHP version      | 7.1.22
| Operating system | Windows 10

**Comment by Elwizard84** [comment]
I got this working by emptying the 'encryption' property instead of filling with 'none'.

I'm leaving this issue open because of the need for filtering this for accepted values ,and throwing an informative exception about it instead of a generic connection failure.

**Comment by samdark** [comment]
We are passing configuration directly to \Swift_SmtpTransport so in order to get this check it's better to report to https://github.com/swiftmailer/swiftmailer/issues
