### ISSUE TITLE
phpunit-mock-objects is abandoned

### ISSUE THREAD

**Issue by yht** [yiisoft/yii2-app-advanced#437]
### What steps will reproduce the problem?

`composer create-project --prefer-dist yiisoft/yii2-app-advanced yii2-app-advanced`

### What's expected?

There're no error or warning.

### What do you get instead?

```
....
codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
codeception/base suggests installing stecman/symfony-console-completion (For BASH autocompletion)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | current
| PHP version      | 7.0.33-0+deb9u3
| Operating system | Debian GNU/Linux 9.9 (stretch)

**Comment by samdark** [comment]
How would you fix it?

**Comment by rob006** [comment]
The same as https://github.com/yiisoft/yii2-app-basic/issues/210

**Comment by samdark** [comment]
Solved in latest version of the template.

**Comment by yht** [comment]
> 
> 
> Solved in latest version of the template.

Thx!
