### ISSUE TITLE
Is there a way to form routes like `http://api.app.com/v1/controller/action?params` ?

### ISSUE THREAD

**Issue by haoliangxxx** [yiisoft/yii2-app-advanced#44]
It is a question.

I used advanced-template, and made directories like this:

```
- project-root-directory
    -- common
    -- v1
    -- v2
```
I know that I can easily use **two domain**:
  
     `apiv1.app.com`  for `project/v1/web` and  `apiv2.app.com`  for `project/v2/web`

I have tried using **modules**, but I found that way is nested and complex, I do not want it.

Is there a way to form routes like  `api.app.com/v1/controller/action?params`.

I tried rewrite in nginx server block like this:
```
server {
    server_name api.app.o;
    root /srv/http/project-root-directory;
    location / {
        index index.php;
        rewrite ^/v1(.*)$ /v1/web/index.php?$1 last;
        return 403;
    }
    location ~ \.php$ {
        fastcgi_pass   unix:/run/php-fpm/php-fpm.sock;
        fastcgi_index  index.php;
        include        fastcgi.conf;
    }
}
```
That only execute `v1\controller\SiteController::index()`, even i request like `api.app.o/v1/a/b/c?d=f`.

**Comment by githubjeka** [comment]
> It is a question.

It is a bug traker. Please go to offical forum or chat or group or stacoverflow....
