### ISSUE TITLE
Plugin yiisoft/yii2 composer couldnot be initialized class not found : yii\composer\plugin

### ISSUE THREAD

**Issue by freeze000** [yiisoft/yii2-app-advanced#448]
### What steps will reproduce the problem?
I try to install Yii2 with Vagrant on this manual https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#manual-for-windows-users

### What's expected?
I expect successfully complete provision/once-as-vagrant.sh

### What do you get instead?
throws an error like this
Plugin yiisoft/yii2 composer could not be initialized class not found: yii\composer\plugin

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | Yii2 2.0.26
| PHP version      | PHP 7.0
| Operating system | WINDOWS 7

**Comment by cebe** [comment]
There seems to be a bug in VirtualBox: https://www.virtualbox.org/ticket/18776

**Comment by samdark** [comment]
Any idea if we can do a workaround from our side?

**Comment by cebe** [comment]
it is possible to configure the shared directory to use NFS instead of vboxfs. vboxfs however works out of the box, while NFS needs a private network setup and might need custom adjustments in different environments. Also it does not work on windows...

**Comment by samdark** [comment]
Sounds like we can't do anything except waiting for the bug to be fixed.

**Comment by samdark** [comment]
@freeze000 meanwhile try downgrading guest additions as suggested in the ticket @cebe linked to.

**Comment by cebe** [comment]
looks like laravel homestead are doing some workarounds here:

https://github.com/laravel/homestead/issues/1240#issuecomment-513567997

have no time to dig into this right now, maybe someone else can find something in there.

**Comment by cebe** [comment]
Seems there is a timing issue:

https://github.com/laravel/homestead/issues/1240#issuecomment-513989365

**Comment by RCooLeR** [comment]
--prefer-source
