### ISSUE TITLE
PHPDoc @var tags in views parameters order

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#45]
Every single view file in the project (views/*) has an incorrect order of parameters in @var tag, for ex. in frontend/views/site/about:
```
/* @var $this yii\web\View */
```
But according to the PHPDoc spec in different sources (see links below) it should be:
```
/* @var yii\web\View $this */
```
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#824-var
http://phpdoc.org/docs/latest/references/phpdoc/tags/var.html

**Comment by samdark** [comment]
It is because of NetBeans that doesn't work properly with `type $var` format.

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/3793
