### ISSUE TITLE
the composer package version has a version conflict between codeception/phpunit-wrapper and symfony/event-dispatcher

### ISSUE THREAD

**Issue by aslackers** [yiisoft/yii2-app-advanced#454]
```shell
Uncaught TypeError: Argument 1 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an object, string given, called in app-path/vendor/codeception/phpunit-wrapper/src/Listener.php on line 135 and defined in app-path/vendor/symfony/event-dispatcher/EventDispatcher.php:48
```

my `composer.json`:
```php
...
"require-dev": {
        "yiisoft/yii2-debug": "~2.1.0",
        "yiisoft/yii2-gii": "~2.1.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/codeception": "^4.0",
        "codeception/module-asserts": "^1.0",
        "codeception/module-yii2": "^1.0",
        "codeception/module-filesystem": "^1.0",
        "phpunit/phpunit": "~5.7.27 || ~6.5.5",
        "codeception/verify": "~0.5.0 || ~1.1.0",
        "symfony/browser-kit": ">=2.7 <=4.2.4"
    },
...
```

It's because in the `codeception/phpunit-wrapper/src/Listener.php`:
```php
$this->dispatcher->dispatch('suite.end', new SuiteEvent($suite));
```

but in `symfony/event-dispatcher` it's defined:
```php
public function dispatch(object $event, string $eventName = null): object;
```

**Comment by RichardPillay** [comment]
> ```shell
> Uncaught TypeError: Argument 1 passed to Symfony\Component\EventDispatcher
> ...
> It's because in the `codeception/phpunit-wrapper/src/Listener.php`:
> 
> ```

I'm facing the same problem, and got around it by changing the order of the dispatcher->dispatch calls. However, it is a codeception issue - could you report it on the codeception/codeception github as well?

**Comment by RichardPillay** [comment]
Just as a matter of interest, the github repository for Codeception shows the code has been changed, but doing a composer upgrade doesn't get it. It's probably not been released yet.
