### ISSUE TITLE
Configuration and environments doc clarification

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2-app-advanced#46]
Some quotes from https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md:
> •Each team member has its own configuration options. Committing such config will affect other team members.
> •Production database password and API keys should not end up in the repository.

> config files suffixed with  -local.php . These are added to  .gitignore  and never added to source code repository.

It would be nice to explicitly state that:
1) team member config goes into -local files of dev environment.
2) Production database password goes into the -local files of prod environment.
Unless my understanding is incorrect and then a proper explanation should be provided.

**Comment by samdark** [comment]
Done. Thanks!
