### ISSUE TITLE
docker-compose run --rm backend yii migrate doesn't work

### ISSUE THREAD

**Issue by michalrogalskiappwise** [yiisoft/yii2-app-advanced#462]
I'm trying to start Yii2 advanced project using docker. This is my first project in Yii2 and I don't know what might be the problem.

There are a few commands in a DockerFile in a frontend directory. These enable me to download npm, composer etc.

I'm running the following command in console:

`docker-compose run --rm backend php init`

Everything is just fine, so I'm changing access data in the main-local.php file:

`'components' => [`
        `'db' => [`
`        'class' => 'yii\db\Connection',`
`        'dsn' => 'mysql:host=127.0.0.1;port=3396;dbname=pdo_local',`
`        'username' => 'root',`
`        'password' => 'root',`
`        'charset' => 'utf8',`
`        'enableQueryCache' => false,`
`        'emulatePrepare' => false,`
`    ]`
`]`

I'm running the next command:

`docker-compose run --rm backend yii migrate`

and there is an ERROR:

`usermod: no changes`
`Yii Migration Tool (based on Yii v2.0.32)`

`Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "db".'`

`in /app/vendor/yiisoft/yii2/di/Container.php:449`

`Stack trace:`
`#0 /app/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container->getDependencies('db')`
`#1 /app/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('db', Array, Array)`
`#2 /app/vendor/yiisoft/yii2/di/Instance.php(167): yii\di\Container->get('db')`
`#3 /app/vendor/yiisoft/yii2/di/Instance.php(137): yii\di\Instance->get(NULL)`
`#4 /app/vendor/yiisoft/yii2/console/controllers/MigrateController.php(183):` `yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\db\\Connecti...')`
`#5 /app/vendor/yiisoft/yii2/base/Controller.php(155): yii\console\controllers\MigrateController-`
`->beforeAction(Object(yii\base\InlineAction))`
`#6 /app/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array)`
`#7 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)`
`#8 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate',` `Array)`
`#9 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application`
`->runAction('migrate', Array)`
`#10 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application-`
`->handleRequest(Object(yii\console\Request))`
`#11 /app/vendor/yiisoft/yii2/yii(37): yii\base\Application->run()`
`#12 {main}`

_Originally posted by @michalrogalskiappwise in https://github.com/yiisoft/yii2-app-advanced/issues/458#issuecomment-603517115_

**Comment by samdark** [comment]
Seems you don't have database configured.

**Comment by michalrogalskiappwise** [comment]
How can I configure that ? Isn't data in file main-local.php sent to configuration ?

**Comment by samdark** [comment]
Yes, it should.

**Comment by michalrogalskiappwise** [comment]
So why isn't it ? Is there something I can do about it ?

**Comment by samdark** [comment]
@schmunk42 any ideas?

**Comment by schmunk42** [comment]
Your database does not run in the PHP container, it should be reachable via:

```
'dsn' => 'mysql:host=mysql;port=3396;dbname=pdo_local',
```

**Comment by michalrogalskiappwise** [comment]
doesn't work. 
But in documentation 'dns' key looks like 

'dsn' => 'mysql:host=127.0.0.1;dbname=demo',

[https://www.yiiframework.com/doc/api/2.0/yii-db-connection ](url)

**Comment by schmunk42** [comment]
> 'dsn' => 'mysql:host=127.0.0.1;dbname=demo',

That's for a non-dockerized setup, are you using the `docker-compose.yml` from this repo?

**Comment by michalrogalskiappwise** [comment]
Yes. Ok, you are right.

**Comment by michalrogalskiappwise** [comment]
@schmunk42 Thanks for your help.

That configuration is right. When I run application everything is correct.
But I have a problem with migration in console, because I'm still getting this error.

`usermod: no changes`
`Yii Migration Tool (based on Yii v2.0.32)`

`Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "db".`

The problem is with the function get in class vendor\yiisoft\yii2\base\Module.php

`758    public function has($id, $checkInstance = false)`
`759    {`
`760			// debug - (isset($this->module) is false`
`761        return parent::has($id, $checkInstance) || `
` (isset($this->module) && $this->module->has($id, $checkInstance));`
`762    }`

Where can I look for a solution? That problem only appears, when I want to execute migration from console.

**Comment by schmunk42** [comment]
Does your config on the console maybe differ from the web config?
Why is the config on the console invalid?
