### ISSUE TITLE
 Migrate | Exception 'yii\base\InvalidConfigException'- 'Failed to instantiate component or class "db".'

### ISSUE THREAD

**Issue by smelike** [yiisoft/yii2-app-advanced#463]
### What steps will reproduce the problem?
> yii migrate 

### What's expected?
execute the migration successfully

### What do you get instead?

Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "db".'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | This is Yii version 2.0.32.
| PHP version      | PHP 7.3.16 
| Operating system | CentOS 7

**Comment by smelike** [comment]
> [root@VM_0_6_centos migrations]# /usr/share/nginx/yii2-back/vendor/bin/yii migrate
Yii Migration Tool (based on Yii v2.0.32)

Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "db".'

in /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/di/Container.php:449

Stack trace:
#0 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container->getDependencies('db')
#1 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('db', Array, Array)
#2 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/di/Instance.php(167): yii\di\Container->get('db')
#3 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/di/Instance.php(137): yii\di\Instance->get(NULL)
#4 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/console/controllers/MigrateController.php(183): yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\db\\Connecti...')
#5 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/base/Controller.php(155): yii\console\controllers\MigrateController->beforeAction(Object(yii\base\InlineAction))
#6 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array)
#7 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#8 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#9 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#10 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /usr/share/nginx/yii2-back/vendor/yiisoft/yii2/yii(37): yii\base\Application->run()
#12 {main}

**Comment by smelike** [comment]
Yeah. I have config db comments in common/config/main.php

`'db' => [
			'class' => 'yii\db\Connection',
			'dsn' => 'mysql:host=127.0.0.1;dbname=huaxiabaihuo',
			'username' => 'root',
			'password' => '',
			'charset' => 'utf8'
		],`

**Comment by samdark** [comment]
So the only change is that you've adjusted database name?

**Comment by smelike** [comment]
> So the only change is that you've adjusted database name?

I use the advanced template for my application.
What else info do you need?

**Comment by samdark** [comment]
Unfortunately, I can't reproduce the issue. Likely it's a server-specific thing but it's impossible to guess.
