### ISSUE TITLE
Missing "class" on docs/guide/topic-link-backend-frontend.md

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2-app-advanced#466]
### What steps will reproduce the problem?

Just try to follow the documentation on [https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-link-backend-frontend.md](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-link-backend-frontend.md) yourself ;)

### What's expected?
For it to not throw an exception following the documentation outlined.

### What do you get instead?

```
Invalid Configuration – yii\base\InvalidConfigException
The configuration for the "urlManagerFrontend" component must contain a "class" element.
```

### Additional info

Doesn't matter, but here it is anyways :)

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.35
| PHP version      | 7.3.3
| Operating system | MacOS Catalina 10.15.3

At the very least, this doc page should showcase defining the `class` element in the config, because it 100% does not work without it.

A pull request will be attached to this issue.

---

On a side note, even defining the class element won't produce a working URL manager when dealing with a sub-domain. The url manager doesn't magically know the root url of another app on another sub-domain. So following the docs (and adding the class) still doesn't result in the proper URL being used.

Use case situation: frontend is the primary domain (example.tld) and backend is a sub-domain (backend.example.tld). -- If you create a custom url manager on the frontend to the backend, the generated links are not correct. They will be missing the sub-domain from the url.

In a sub-domain setup, you need to also define the `hostInfo` element.

In the following example, I have auto-loaded (in` composer.json`) a custom functions file with functions to generate the proper root URLs ( for frontend, backend, etc).

So you can do something like this:

```
'urlManagerFrontend' => [
    'class' => 'yii\web\UrlManager',
    'hostInfo' => getFrontendDomain(),
    // ...
],
```

You could hard-code the URL, create aliases, however you want to handle it. I chose to create a custom functions file that gets autoloaded by Composer. It is just cleaner and easier to manage.

For anyone wanting to do the same, add this to your `composer.json` and create the corresponding file:

```
"autoload": {
    "files": [
        "common/functions.php"
    ]
}
```

I use DotEnv, so you will have to modify this a bit for it to work for you, but this illustrates how I determine the domains.

**common/functions.php**
```
<?php

function getUrlScheme()
{
    return (env('USE_HTTPS') === true) ? 'https' : 'http';
}

// example: https://example.tld
function getFrontendDomain()
{
    return getUrlScheme() . '://' . env('FRONTEND_DOMAIN');
}

// example: https://backend.example.tld
function getBackendDomain()
{
    return getUrlScheme() . '://' . env('BACKEND_DOMAIN');
}
```

You could, in `common/config/bootstrap.php` create aliases instead.

```
Yii::setAlias('@httpScheme', 'https');
Yii::setAlias('@frontendDomain', 'example.tld');
Yii::setAlias('@backendDomain', 'backend.example.tld');
```

Then in the custom functions file, use `Yii::getAlias()` instead of my `env()` function. The result is the same, but using DotEnv is so much better. It is a shame Yii2 _STILL_ doesn't use it, but it's easy to setup yourself.

Since the assumed and default setup is for frontend and backend to be a domain or sub-domain setup, I don't see how the docs match what is expected. Leaving a gap and problems for newbies to Yii2.

I am not sure how to best document the rest of this. However, at the very least, these docs need to show people they need to define the `class` element on a custom named URL manager.

**Comment by samdark** [comment]
> I am not sure how to best document the rest of this

Exactly the way you did. It's almost perfect. Append it to the guide, use URLs from `params.php` instead of dotenv and do a pull request. I'll merge it.

btw., we're adopting reading environmental variables via `getenv()` and promoting their use in Yii 3. A question about DotEnv. Doesn't it fill environment variables from files and that's it?

**Comment by WadeShuler** [comment]
Ok, I think I have a good baseline idea of what you are wanting. I will whip it up shortly and create a new PR.

I honestly haven't used Yii2 in about a year, went on a Laravel and Wordpress spree lol. That (hostInfo) is how I used to do it on my yii2 member's system. I actually am in the process of updating it now. I removed the `init` and environments usage completely (along with all the `-local` files) and replaced it with DotEnv. I have a question about the best route to integrate DotEnv, at the earliest entrypoint.. but I will ask about that later when I have the code pushed.

---

As for DotEnv

It would completely replace the `init` process and the use of environments (and `-local` files).

Your config is stored in an `.env` file. You can actually have multiple env files, it can be named whatever you want. So you can tell DotEnv to load the file named (`yii.config`). The configs can override each other, so you can have a root environment and override it on certain conditions.

I recommend you look at how [Laravel](https://github.com/laravel/laravel/) handles them. Symfony uses them too. While Laravel uses a lot of Symfony packages, they don't use it for the env handling. They use the one from [vlucas](https://github.com/vlucas).

The PHP DotEnv package I recommend is [https://github.com/vlucas/phpdotenv](https://github.com/vlucas/phpdotenv). No need to re-invent the wheel.

Laravel uses their own function, `env()`, which is a wrapper for `gentenv()`. 

The reason why is... ALL of the values in the env file are loaded as strings.

```
APP_DEBUG=true
ACCOUNT_NUM=null
```

In order for it to make logical sense to the programmer, `env('APP_DEBUG')` should actually be a boolean when we interact with it.

So the `env()` function does 2 things. It allows you to pass a default value if it isn't set:
```
env('APP_TIMEZONE', 'UTC');        // defaults to UTC
```

Most importantly, it can convert the value to a `boolean` or `null` if they are supposed to be.

Here is a function I use. It is modified from Laravel, so do what you want with that. I am just posting it as an example.

```
if ( ! function_exists('env') ) {
    /**
     * Gets the value of an environment variable.
     *
     * Slightly modified version from Laravel.
     *
     * @param  string  $key
     * @param  mixed  $default
     * @return mixed
     *
     * @credit https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Env.php
     */
    function env($key, $default = null)
    {
        if ( isset($_ENV[$key] ) ) {
            $value = $_ENV[$key];
            switch (strtolower($value)) {
                case 'true':
                case '(true)':
                    return true;
                case 'false':
                case '(false)':
                    return false;
                case 'empty':
                case '(empty)':
                    return '';
                case 'null':
                case '(null)':
                    return null;
            }

            if ( preg_match('/\A([\'"])(.*)\1\z/', $value, $matches) ) {
                return $matches[2];
            }

            return $value;
        }

        return $default;
    }
}
```

I will take a look at the progress of yii3 when I get a chance.

**Comment by samdark** [comment]
> Your config is stored in an .env file.

And that is very wrong except you're doing it in development environment. Also, it's basically the same as php configs except you've changed the format. Environment, ideally, should be securely stored in something like Hashicorp Vault or passed to a Docker image when it's started.

As for vlucas/phpdotenv, we're using it in Yii 3 composer config plugin. It is, indeed, handy to override environment variables for local development server.

Adding type-casting sounds interesting.

**Comment by WadeShuler** [comment]
I have PR #468 up for going into more detail on the guide, `topic-link-backend-frontend`.

You said to use the URLs from `params`, but the params aren't available at this stage (within the config array, before it's passed into the Application's constructor). Also, the bootstrap files aren't managed by init/environments. So we are a bit limited with a dynamic implementation to prevent them from hard-coding the URLs. The way I set forth gets around those limitations and still allows the developer to make use of init/environments to rotate the domains based on the environment. Maybe you see a better way now that it's laid out.

Yes, the proper use of the `.env` file is locally with the environment variables set at the server level for production. This is understood even with Laravel. However, all of the guides, extensions, everything reference "add this to your .env file". It just is a baseline for documentation, and it limits excess Github issues.

All DotEnv does is parse the `.env` file and put the values into the environment via `putenv()`. So if you already have them set (ie: Docker container) then it isn't necessary. You could load an empty `.env` file or skip loading it all together.
