### ISSUE TITLE
gii getting  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

### ISSUE THREAD

**Issue by grmankar** [yiisoft/yii2-app-advanced#473]
### What steps will reproduce the problem?
Generating models from gii
### What's expected?
It product error "SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''"
### What do you get instead?
php yii gii/model --tableName=* --modelClass=common\models

### Additional info
This is Yii version 2.0.36.
https://i.imgur.com/Lw6TqJa.png
![Screenshot-20200730111827-1918x937](https://user-images.githubusercontent.com/10545660/88885618-762e7d00-d256-11ea-9cec-8d64eef37192.png)

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.36.
| PHP version      | php 7.4
| Operating system | Ubuntu

**Comment by samdark** [comment]
Would you please try 2.0.37@dev?

**Comment by samdark** [comment]
Should be fixed by now.
