### ISSUE TITLE
backend/Dockerfile

### ISSUE THREAD

**Issue by juppwerner** [yiisoft/yii2-app-advanced#489]
### What steps will reproduce the problem?

Install yii2-app-advanced following the instructions "Installing using Docker"
Run step `docker-compose run --rm backend composer install`

### What's expected?

Get composer install running

### What do you get instead?

composer is complaining to expect PHP 7.3 minimum

### Additional info

The solution is to change from php:7.2 to php:7.4 ind `backend/Dockerfile`:

`FROM yiisoftware/yii2-php:7.4-apache`

| Q                | A
| ---------------- | ---
| Yii version       | Yii2 
| PHP version      |
| Operating system | Docker

**Comment by bizley** [comment]
Same for frontend

**Comment by samdark** [comment]
@juppwerner would you like to make a pull request? That would speed up things a bit.
