### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by mahdi-moradi** [yiisoft/yii2-app-advanced#494]
Hello
When I want to install Yii via composer, I get an error.
Package fxp/composer-asset-plugin at version ~1.1.1 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
I have tried to do this in several ways.
The official guide says to use "fxp/composer-asset-plugin:~1.1.1"
in Yii3 demo says to use "foxy/foxy:^1.1.0"
Of course, both do not work.
in Yii forum says, You need to switch to yiisoft/yii2-composer
After all, which method is correct?

### What steps will reproduce the problem?
Instalation
### What's expected?
Update dependencies
### What do you get instead?
Installation failed

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.40
| PHP version      | 8.0.1
| Operating system | Ubuntu 20.04

**Comment by mahdi-moradi** [comment]
@samdark

**Comment by bizley** [comment]
Official guide only mentiones `composer-asset-plugin` and as a second option, mainly for backward compatibility. Preffered way is to use [asset-packagist](https://asset-packagist.org/) as it is stated both in the Guide and in the advanced app docs.
