### ISSUE TITLE
Installation notes improvement suggestion

### ISSUE THREAD

**Issue by MikeBrice** [yiisoft/yii2-app-advanced#497]
A little more detail, if added, would make this help very helpful. To simply state "To login into the application, you need to first sign up assumes a lot of intuition for those new to the product I would suggest.

A suggested improvement:

After having successfully opened the frontend home page, create a user by selecting the Sign Up menu option at the top of the frontend home page.
Provide the requested credentials, and complete the data entry with the Signup button.
You will be presented with a message:
"Thank you for registration. Please check your inbox for verification email."
stating that a confirmation email has been sent, however the default settings for the mailer prevents the sending of a real email.
Instead, an eml format file is created in the directory @frontend/runtime/mail
Either open this file with a mail client such as Outlook or Thunderbird, or use a text editor to retrieve the URL which is used to confirm the User creation.
The URL will need to be modified as follows:

delete ‘=’ and \n at the end of every line (Linux) 
delete ‘=’ at the end of every line (Windows) 

change ‘=3D’ to ‘=’

Paste this URL into a browser tab to complete the User creation. You will be presented with the message:
Your email has been confirmed!
and you will automatically be logged in to the frontend application.
The same credentila can then be used to login to the backedn application.

This has been created from a number of suggestions I found with the generous help of Madame Google.

| Q                | A
| ---------------- | ---
| Yii version       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
Sounds alright. Would you please create a pull request with these changes?

**Comment by MikeBrice** [comment]
Here is a slightly modified version of the proposed explanation text:

After having successfully opened the frontend home page, create a user by selecting the Sign Up menu option at the top of the frontend home page.
Provide the requested credentials, and complete the data entry with the Signup button.
You will be presented with a message:
"Thank you for registration. Please check your inbox for verification email."
stating that a confirmation email has been sent, however the default settings for the mailer prevents the sending of a real email.
Instead, an eml format file is created in the directory @frontend/runtime/mail. Either open this file with a mail client such as Outlook or Thunderbird, or use a text editor to retrieve the URL which is used to confirm the User creation. The URL will need to be modified as follows:
delete ‘=’ and \n at the end of every line (Linux)
delete ‘=’ at the end of every line to create a single line (Windows)
change ‘=3D’ to ‘=’
Paste this URL into a browser tab to complete the User creation. You will be presented with the message:
Your email has been confirmed!
and you will automatically be logged in to the frontend application. The same credentials can then be used to login to the backend application.
