### ISSUE TITLE
Acceptance Test not working with Selenium 3.141.59 as descibed in Manual

### ISSUE THREAD

**Issue by gb5256** [yiisoft/yii2-app-advanced#499]
### What steps will reproduce the problem?
Follow the instruction on:
https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-testing.md

### What's expected?
Acceptance tests are running

### What do you get instead?
when running this:

   java -jar ~/selenium-server-standalone-3.141.59.jar -enablePassThrough false

Selenium claims that -enablePassThrough is not valid anymore.
But also without I do not get acceptance testing to work

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.41.1
| PHP version      | 8.0.3
| Operating system | Ubuntu 18.04

**Comment by schmunk42** [comment]
If you want to use a recent selenium version, make sure to upgrade codeception and webdriver (as high as possible)

see also https://github.com/php-webdriver/php-webdriver/issues/469#issuecomment-584188056
