### ISSUE TITLE
yii is missing from root yii.bat not working

### ISSUE THREAD

**Issue by izemize** [yiisoft/yii2-app-advanced#50]
Hi

yii is missing from root, and yii.bat not working on windows:

C:\Users\gaben\.....hu>yii.bat

Could not open input file: C:\Users\gaben\.......hu\yii

**Comment by izemize** [comment]
I forgot init step, sorry.

So php /path/to/yii-application/init --env=Production --overwrite=All

Fixed this problem.

**Comment by upingli** [comment]
That means script yii is no long need?
