### ISSUE TITLE
Vagrant image is too old

### ISSUE THREAD

**Issue by N1kolayS** [yiisoft/yii2-app-advanced#502]
I tried install php7.3 in Vagrant image. I tried use ppa:ondrej/php for install php7.3.
But Repository ppa:ondrej/php not support ubuntu 16.04
https://github.com/oerdnj/deb.sury.org/issues/1567

P.S. Sorry for my English )

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       latest
| PHP version     7.3
| Operating system Windows 10

**Comment by samdark** [comment]
@N1kolayS do you have time to update it and make a pull request?
