### ISSUE TITLE
new session id on every page request

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2-app-advanced#513]
### What steps will reproduce the problem?

clean install with composer:
composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-advanced D:\web\www\yii2test-dev\app

### What's expected?

same session id when page is refreshed

### What do you get instead?

new id

### Additional info

Also tested with php 8.0.6 same problem
If project is created with --stability=stable - there is no problem with the session id.

| Q                | A
| ---------------- | ---
| Yii version    | 2.0.44-dev.
| PHP version      | 8.1.0
| Operating system | Windows 10

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/19067

**Comment by samdark** [comment]
Should be fixed now.

**Comment by samdark** [comment]
Please re-check.
