### ISSUE TITLE
"composer update "  takes too much time almost 2 hours .. finally send an error

### ISSUE THREAD

**Issue by cloudinventors** [yiisoft/yii2-app-advanced#53]
Error : 
[Composer\DependencyResolver\SolverProblemsException]                                                       
    Problem 1                                                                                                 
      - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.     
      - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.      
      - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.x-dev, dev-master].  
  Potential causes:                                                                                           
   - A typo in the package name                                                                               
   - The package is not available in a stable-enough version according to your minimum-stability setting      
     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.            
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by samdark** [comment]
It seems you forgot to install fxp plugin globally: http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer

**Comment by cebe** [comment]
no, the problem is that the current master of the advanced app requires yii2>=2.0.6 which is not yet released.

**Comment by cebe** [comment]
this will be solved with the upcoming release which will happen the next days

**Comment by cloudinventors** [comment]
I have installed fxp plugin globally. still getting such error deprecation notice.  please refer this snapshot.
![error](https://cloud.githubusercontent.com/assets/12658927/8892436/080dd7b8-3377-11e5-91f3-20f134c42a30.png)

**Comment by samdark** [comment]
As @cebe said, the problem will be resolved with the next release. Till then you can replace `yiisoft/yii2: *` with `~2.0.5` or a specific commit.

**Comment by cloudinventors** [comment]
Sir, i did as above but still composer update is taking more than an hour. composer diagnose works perfect . i have installed assets plugin too . here is my json , and composer updating snapshot . please have a look . thanks in advance.
![problem](https://cloud.githubusercontent.com/assets/12658927/8894978/332df078-33e9-11e5-8696-e159a13b3f2b.png)

**Comment by cebe** [comment]
the window on the left shows that composer is installing packages. if that is slow it is most likely caused by your internet connection.
