### ISSUE TITLE
Vendor

### ISSUE THREAD

**Issue by faradoxuz** [yiisoft/yii2-app-advanced#55]
Where is the vendor directory?

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for issue reporting. Thanks!

**Comment by faradoxuz** [comment]
ok,thanks, I solved it,

**Comment by faradoxuz** [comment]
Я не мог найти vendor директорию, но потом скачивал с сайта yii, там есть, спасибо

**Comment by LAV45** [comment]
скачай себе [composer](https://getcomposer.org/download/) 
закинь его в папку с проектом и запусти из консоли
```
$ php composer.phar install
```
