### ISSUE TITLE
yii migrate Error

### ISSUE THREAD

**Issue by qipengwei** [yiisoft/yii2-app-advanced#558]
### What steps will reproduce the problem?
Appears when you run the **yii migrate** command

### What's expected?

Yii : 2.0.33
mac os: 12.6.6 
php : 5.6.40
mysql: 5.7.33

### What do you get instead?

Error: Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers'

### Additional info

my database config

```php
'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=192.168.1.30;dbname=apitpldb',
            'username' => 'root',
            'password' => 'password',
            'charset' => 'utf8'
 ]
```
| Q                | A
| ---------------- | ---
| Yii version       |
| PHP version      |
| Operating system |

**Comment by bizley** [comment]
I'm afraid in that case you are that developer that the message is referring to. Please check if your db server can handle `utf8` charset. Also I recommend upgrading your php.

**Comment by qipengwei** [comment]
> 恐怕在这种情况下，您就是该消息所指的开发人员。请检查您的数据库服务器是否可以处理`utf8`字符集。另外我建议升级你的 php.ini。

I upgraded to php 7.4 and mysql 8.0.30 and it still didn't work

**Comment by qipengwei** [comment]
> 恐怕在这种情况下，您就是该消息所指的开发人员。请检查您的数据库服务器是否可以处理`utf8`字符集。另外我建议升级您的 php.ini。

And changing the default character set of the database to utf8 according to the tips in this article still won't work https://ourcodeworld.com/articles/read/1828/how-to-solve-pdo-connection-error-sqlstatehy000-2054-server-sent-charset-unknown-to-the-client

**Comment by bizley** [comment]
Not sure why it didn't help but this is something you need to investigate yourself. Maybe you did not upgrade you console version and using it instead? Don't know, too many potential causes. Please try our forum and other sources. I see there are many topic regarding this on SO as well. I'm pretty sure it will be resolved in no time.
