### ISSUE TITLE
yii2 migration

### ISSUE THREAD

**Issue by faradoxuz** [yiisoft/yii2-app-advanced#56]
Hello, I am trying to something with migration.
when I run "php yii migrate" I am getting 
"Exception 'ReflectionException' with message 'Class db does not exist'
in /var/www/yii2.uz/vendor/yiisoft/yii2/di/Container.php:415"
what is problem

**Comment by samdark** [comment]
Do you have database connection defined for console application?

**Comment by LAV45** [comment]
I think, the legs grow from here https://github.com/yiisoft/yii2-app-advanced/issues/55

**Comment by faradoxuz** [comment]
Yes I have, I tried input dab connection both in /console/config/main.php and /console/config/main-local.php. what is the problem?

**Comment by faradoxuz** [comment]
Александр, у меня проблема с миграция, помогите пожалуйста. конфиг для консоль приложение все настроил, но говорить "Class db not found"

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for issue tracking.
