### ISSUE TITLE
can not install and update yii2-app

### ISSUE THREAD

**Issue by Pashkinz92** [yiisoft/yii2-app-advanced#57]
Hello, I am trying run the command `<composer create-project --prefer-dist yiisoft/yii2-app-advanced yii2-application>`. I get error message `<[UnexpectedValueException]
  Could not parse version constraint <=2.*: Invalid version string "2.*">` This problem began to appear with version yii2.0.6

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/9231

**Comment by Pashkinz92** [comment]
Thanks :+1:
