### ISSUE TITLE
Can't build/install the advanced template project

### ISSUE THREAD

**Issue by eberon** [yiisoft/yii2-app-advanced#59]
I can't build or install the advanced template project due to the following error. Is this a yii2 project bug or an advanced template project bug (or something else)?

I cannot get the yii2 advanced template application to build. I have not specified a stability flag -- but the default should be stable, yes?

$ composer --version
Composer version 1.0-dev (bd2d7eba05dc6a51dbbad780b6f0eb505accba75) 2015-07-31 08:06:09

$ composer create-project --prefer-dist yiisoft/yii2-app-advanced yii2-advanced
Installing yiisoft/yii2-app-advanced (2.0.4)
  - Installing yiisoft/yii2-app-advanced (2.0.4)

Created project in yii2-advanced
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.4 -> satisfiable by yiisoft/yii2[2.0.4, 2.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html

```
composer global require "fxp/composer-asset-plugin:~1.0.0"
```

?

**Comment by mnglkhn** [comment]
composer global require "fxp/composer-asset-plugin:~1.0.1"

there is a bug in FXP and you need to use 1.0.1 instead of 1.0.0


On Sun, Aug 2, 2015 at 11:16 AM, Alexander Makarov <notifications@github.com

**Comment by samdark** [comment]
`~1.0.0` means latest stable version of 1.0.x.
