### ISSUE TITLE
Missing class attribute in debug and gii

### ISSUE THREAD

**Issue by pragmas** [yiisoft/yii2-app-advanced#61]
https://github.com/yiisoft/yii2/issues/6795#issuecomment-127913745

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/blob/d36fdc1f67d8f4655c2b88c17ac9520ec4074c99/environments/dev/frontend/config/main-local.php#L15
https://github.com/yiisoft/yii2-app-advanced/blob/d36fdc1f67d8f4655c2b88c17ac9520ec4074c99/environments/dev/frontend/config/main-local.php#L18
