### ISSUE TITLE
Upgrade test environment for Codeception 2.1

### ISSUE THREAD

**Issue by codeskull** [yiisoft/yii2-app-advanced#62]
[Codeception 2.1](http://codeception.com/06-30-2015/codeception-2.1-is-here.html) brought some little changes that should be implemented.

**Comment by samdark** [comment]
Could you work on it?

**Comment by Edofre** [comment]
@codeskull What changes would these be? Updating codeception to 2.1 and building/running all the tests works without any problems here.
