### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by agarb7** [yiisoft/yii2-app-advanced#64]
Are there any plans to add Vagrantfile in repo? 
I think it would be nice for developers to have configured web server and database out of the box.

**Comment by samdark** [comment]
I'm not against it but it's not a priority.

**Comment by LAV45** [comment]
@see https://github.com/yiisoft/yii2/tree/docker-build

**Comment by cebe** [comment]
that is not really related, `docker-build` branch is about creating containers for yii framework unit tests.

**Comment by SilverFire** [comment]
Implemented by https://github.com/yiisoft/yii2-app-advanced/commit/fec06983278b4f1c821c3d1116b04910aa03328c
