### ISSUE TITLE
Cannot logout when Javascript is disabled

### ISSUE THREAD

**Issue by mytskine** [yiisoft/yii2-app-advanced#73]
Both frontend and backend require the logout request to use a POST verb. Yet the top menu uses a simple HTML link, with an extra HTML attribute that Javascript uses to forge a POST request. When JS is disabled in the web browser, clicking on the logout link sends to an error page.

I can see 2 ways out:

1. Warn the final user that Javascript is required in the demo application.
2. Remove the "verbs" filter at the top of `(backend|frontend)/controllers/SiteController.php`.
    A slight variant is to comment these lines, so that the filtering capacity is still visible, but is disabled by default with a short explanation.

**Comment by samdark** [comment]
3. Make logout button a form with `method=post` and style it as a link.

**Comment by cebe** [comment]
- http://stackoverflow.com/questions/1367409/how-to-make-button-look-like-a-link
- http://jsfiddle.net/adardesign/5vHGc/

**Comment by mytskine** [comment]
@cebe This are the first links Google gives for those keywords, but, as yii2-app-advanced uses Bootstrap3, we can simply use the class "btn btn-link".

The PR above keeps the REST behavior without requiring JavaScript on the client side.
The code isn't very pretty for a scaffolding application, but i can't see how to do better: I know of no easy way in Yii2 to convert a GET link to POST. So I had to pass raw HTML to the Nav menu and fiddle with the non-semantic classes of Boostrap.
