### ISSUE TITLE
Namespaces mess

### ISSUE THREAD

**Issue by stratoss** [yiisoft/yii2-app-advanced#78]
I'm checking the sample codeception tests, and ```$actor``` variable in [AboutPage.php](https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/codeception/frontend/_pages/AboutPage.php) is defined as
``` * @property \codeception_frontend\AcceptanceTester|\codeception_frontend\FunctionalTester $actor```.
I can't find where the namespace ```codeception_frontend``` is defined. I guess it should be ```tests\codeception\frontend```.

**Comment by samdark** [comment]
It's defined by codeception itself.

**Comment by stratoss** [comment]
Well, I installed codeception as per the readme file, but the IDE could not find this namespace, and it is not defined anywhere in codeception/yii sources... What am I missing?

**Comment by samdark** [comment]
It's kida magical. Try actually running it.

**Comment by stratoss** [comment]
It runs well, but the IDE is complaining about it, and auto-completing doesn't work. Thank you anyway, samdark.
