### ISSUE TITLE
Codeception tests fail when app is in a vagrant box

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2-app-advanced#81]
Followed the test instructions for Yii2 advanced application. Everything up to the `codecept build` works as intended. However when running the actual tests this is the results:

[vagrant@localhost frontend]$ codecept run
Codeception PHP Testing Framework v2.1.3
Powered by PHPUnit 4.8.10 by Sebastian Bergmann and contributors.

Tests\codeception\frontend.acceptance Tests (5) ---
Ensure that signup works (acceptance\SignupCest::testUserSignup) Fail
Ensure that about works (AboutCept) Fail
Ensure that contact works (ContactCept) Fail
Ensure that home page works (HomeCept) Fail
Ensure login page works (LoginCept) Fail

---

Tests\codeception\frontend.functional Tests (5) ---
Ensure that signup works (functional\SignupCest::testUserSignup) Ok
Ensure that about works (AboutCept) Ok
Ensure that contact works (ContactCept) Ok
Ensure that home page works (HomeCept) Ok
Ensure login page works (LoginCept) Ok

---

Tests\codeception\frontend.unit Tests (8) ---
Trying to test contact (unit\models\ContactFormTest::testContact)... <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Call to undefined function tests\codeception\frontend\unit\models\expect()&#039; 

in /var/www_vagrant/yii2-advanced-app/tests/codeception/frontend/unit/models/ContactFormTest.php:42

Stack trace:
#0 phar:///usr/bin/codecept/vendor/codeception/specify/src/Codeception/Specify.php(97): ::call_user_func_array:{phar:///usr/bin/codecept/vendor/codeception/specify/src/Codeception/Specify.php:97}()
#1 phar:///usr/bin/codecept/vendor/codeception/specify/src/Codeception/Specify.php(50): tests\codeception\frontend\unit\models\ContactFormTest-&gt;specifyExecute()
#2 /var/www_vagrant/yii2-advanced-app/tests/codeception/frontend/unit/models/ContactFormTest.php(43): tests\codeception\frontend\unit\models\ContactFormTest-&gt;specify()
#3 phar:///usr/bin/codecept/vendor/phpunit/phpunit/src/Framework/TestCase.php(886): tests\codeception\frontend\unit\models\ContactFormTest-&gt;testContact()
#4 phar:///usr/bin/codecept/vendor/phpunit/phpunit/src/Framework/TestCase.php(886): ReflectionMethod-&gt;invokeArgs()
#5 phar:///usr/bin/codecept/vendor/phpunit/phpunit/src/Framework/TestCase.php(746): PHPUnit_Framework_TestCase-&gt;runTest()
#6 phar:///usr/bin/codecept/vendor/phpunit/phpunit/src/Framework/TestResult.php(601): PHPUnit_Framework_TestCase-&gt;runBare()
#7 phar:///usr/bin/codecept/vendor/phpunit/phpunit/src/Framework/TestCase.php(702): PHPUnit_Framework_TestResult-&gt;run()
#8 phar:///usr/bin/codecept/vendor/phpunit/phpunit/src/Framework/TestSuite.php(735): PHPUnit_Framework_TestCase-&gt;run()
#9 phar:///usr/bin/codecept/src/Codeception/PHPUnit/Runner.php(89): PHPUnit_Framework_TestSuite-&gt;run()
#10 phar:///usr/bin/codecept/src/Codeception/SuiteManager.php(153): Codeception\PHPUnit\Runner-&gt;doEnhancedRun()
#11 phar:///usr/bin/codecept/src/Codeception/Codecept.php(203): Codeception\SuiteManager-&gt;run()
#12 phar:///usr/bin/codecept/src/Codeception/Codecept.php(172): Codeception\Codecept-&gt;runSuite()
#13 phar:///usr/bin/codecept/src/Codeception/Command/Run.php(262): Codeception\Codecept-&gt;run()
#14 phar:///usr/bin/codecept/src/Codeception/Command/Run.php(189): Codeception\Command\Run-&gt;runSuites()
#15 phar:///usr/bin/codecept/vendor/symfony/console/Command/Command.php(259): Codeception\Command\Run-&gt;execute()
#16 phar:///usr/bin/codecept/vendor/symfony/console/Application.php(878): Symfony\Component\Console\Command\Command-&gt;run()
#17 phar:///usr/bin/codecept/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application-&gt;doRunCommand()
#18 phar:///usr/bin/codecept/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application-&gt;doRun()
#19 phar:///usr/bin/codecept/codecept(34): Symfony\Component\Console\Application-&gt;run()
#20 /usr/bin/codecept(7): ::unknown()

Hardware has fe.yii2-advanced-app.dev and be.yii2-advanced-app.dev pointed to vagrant machine; both load in a browser no problem. I can even navigate around the application. But the tests die :(.

**Comment by memclutter** [comment]
Are you sure that you have the composer packages **codeception/specify** and **codeception/verify** ?

Try running

```
composer global require "codeception/specify=*" 
composer global require "codeception/verify=*"
   ```
