### ISSUE TITLE
Advanced Template installation issue [ErrorException] touch(): Utime failed: Permission denied

### ISSUE THREAD

**Issue by ksncool** [yiisoft/yii2-app-advanced#82]
I am using YII2 for my project,I have created a project(advanced template) using composer, now I need to start another project, firstly I have update composer(composer self-update), it is fine. now I am trying to complete installation process of YII2 advanced template on my lampp using composer, on the step Configuring Composer getting following error,

[ErrorException]

touch(): Utime failed: Permission denied

can someone help me, why the problem is occur in 2nd time installation? thanks

can you check this http://stackoverflow.com/q/33119025/5443859

**Comment by samdark** [comment]
Well, you don't have enough permissions to write to the file.
