### ISSUE TITLE
Yii not resolve aliases from common/config/bootstrap.php in GII

### ISSUE THREAD

**Issue by andreymeretsky** [yiisoft/yii2-app-advanced#87]
> Aliases are used to represent file paths or URLs so that you don't have to hard-code absolute paths or URLs in your project. An alias must start with the @ character to be differentiated from normal file paths and URLs.

When I put in "View Path" on gii generator http://mysite.com/gii/controller 
path like "frontend/views/users"  Gii said 
> Unable to create the directory 'frontend/views/users'.
When I change alias to @frontend in common/config/bootstrap.php Gii works correctly. 

If I made a mistake somewhere - show me where please :smiley: 

Besides I don't understand why aliases in bootstrap.php made without "@" which contradicts documentation rules.

**Comment by samdark** [comment]
`@` is added automatically.
