### ISSUE TITLE
I cant add extra fields in step registration user

### ISSUE THREAD

**Issue by pcimagenca** [yiisoft/yii2-app-advanced#89]
Hi, I cant add extra fields directly in core, my files modified are: 

i modified my init migration file for add mynewfield 

later  in  app/common/models/user.php 
class User extends \yii\db\ActiveRecord implements IdentityInterface
{

    public $mynewfield;

......

later in app/frontend/models/signupForm.php
at start the class SignupForm

public $mynewfield;

in public function signup()
    {  if (  $this->validate() &&  Yii::$app->request->post()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->mynewfield= $this->mynewfield;

and my view add the new field, but in the process of registration mynewfield is empty, what i can do for add my extra field without others extensions.

**Comment by pcimagenca** [comment]
some step is bad in my adding new field?

**Comment by samdark** [comment]
That's expected. For AR models only DB fields are safe for mass assignment by default.

**Comment by pcimagenca** [comment]
then only can add extra fields with extensions :+1:
