### ISSUE TITLE
init command stopped creating assets folders

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2-app-advanced#92]
Recently I noticed that `init` command stopped creating folders `backend/assets` and `frontend/assets`. The permissions for creating folders are OK. What's the problem? Is it a bug or this feature was removed? I have to do it manually now.

**P.S.** This happens on both local and production servers, nothing has changed on local server in terms of permissions. Previously these folders were creating without problems.

**Comment by samdark** [comment]
init was never creating these. Composer post-install hook did. Nothing changed in this regard.

**Comment by bizley-code** [comment]
Looks like the hook has been removed in https://github.com/yiisoft/yii2-app-advanced/commit/81a08d50739fc2c4f36ca03824dc2a830de7499e

**Comment by samdark** [comment]
Oh...

**Comment by arogachev** [comment]
I started new project today, and after `php init` command run `frontend/web/assets` and `backend/web/assets` were created successfully. Weird...
