### ISSUE TITLE
Gii generated relations that point to the same model, cannot update

### ISSUE THREAD

**Issue by macmilan** [yiisoft/yii2-app-advanced#95]
I have posted [this] (http://stackoverflow.com/questions/33904400/setting-a-value-of-referenced-table-from-yii2-activeform) on stackoverflow.
I didn't receive any answer, so I thought that this may be a good place to ask.
Although, I am Yii newbie, I am quite capable of conceptualizing. I have tracked this down to traits or behaviors.
In pure transaction approach I would hold the values in local variables and then insert/update as needed, but I want to use Yii's approach. Eg. how do I tell the ActiveForm renderer that first text field refers to text.content column, but as question.
Please, just point me in the right direction and I would be more than grateful.
Don't be to harsh on me!

**Comment by samdark** [comment]
Nope, it's not good place to ask since GitHub is for bug reports. Please get to forums or IRC. Thanks!
