### ISSUE TITLE
Enable pretty urls by default

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2-app-advanced#98]
I think this part of the config:

```
'urlManager' => [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
],
```

should be not commented and included by default because it's used more often.

**Comment by SilverFire** [comment]
Maybe, but it was commented by default not accidentally, i think. Anybody knows why?

**Comment by samdark** [comment]
It wasn't there at all in the beginning because if you're using a server such as Apache, you won't be able to use the app at all with pretty URLs enabled and `.htaccess` missing. Then people asked to add commented out version to start with apps faster.

**Comment by SilverFire** [comment]
Ok, I thought about this, but was unsure. Than I think we should close the issue
